<?php 
return array(
	'13' => array(
		'title' => '员工档案',
		'fields' => 'id,name',
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'User',
		'checkformodel' => NULL,
		'filed' => 'name',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'16' => array(
		'title' => 'LD行业档案',
		'fields' => 'orderno,name',
		'fields_china' => array(
			'orderno' => '编号',
			'name' => '名称',
		),
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoEjs',
		'checkformodel' => 'MisAutoEjs',
		'filed' => 'name',
		'filed1' => 'name',
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'17' => array(
		'title' => '区域档案',
		'fields' => 'orderno,name,id',
		'fields_china' => array(
			'orderno' => '编号',
			'name' => '名称',
		),
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoMji',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => 'name',
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'18' => array(
		'title' => 'LD金融机构档案',
		'fields' => 'jinrongjigoumingchen,orderno',
		'fields_china' => array(
			'jinrongjigoumingchen' => '金融机构名称',
			'orderno' => '编号',
		),
		'checkforfields' => '&#39;jinrongjigoumingchen&#39;=>&#39;金融机构名称&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoSft',
		'checkformodel' => 'MisAutoSft',
		'filed' => 'jinrongjigoumingchen',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'25' => array(
		'title' => '计量单位参照',
		'fields' => 'zhudanwei,huansuanlv,fudanwei,orderno',
		'checkforfields' => '&#39;zhudanwei&#39;=>&#39;主单位&#39;,&#39;huansuanlv&#39;=>&#39;换算率&#39;,&#39;fudanwei&#39;=>&#39;辅单位&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoIqe',
		'checkformodel' => 'MisAutoIqe',
		'filed' => 'zhudanwei',
		'filed1' => 'zhudanwei',
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'26' => array(
		'title' => '企业资产负债表项目参照',
		'fields' => 'zhanghufangxiang,orderno,name,id',
		'checkforfields' => '&#39;zhanghufangxiang&#39;=>&#39;账户方向&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoObt',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => NULL,
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'27' => array(
		'title' => 'LD行业(标准)',
		'fields' => 'orderno,pid,name,id',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;pid&#39;=>&#39;所属行业&#39;,&#39;name&#39;=>&#39;行业名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisSaleProfession',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => NULL,
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'd2ec621557607d9cf5607c7fcbfa399c' => array(
		'title' => '基础资料归档目录',
		'fields' => 'leixing,orderno,beizhu,name',
		'checkforfields' => '&#39;leixing&#39;=>&#39;类型&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoNmp',
		'checkformodel' => 'MisAutoNmp',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'29ebce89a49496676634dcce50ad636b' => array(
		'title' => '抵质押资料类型',
		'fields' => 'orderno,name,shangji,beizhu',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;shangji&#39;=>&#39;上级&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoYks',
		'checkformodel' => 'MisAutoYks',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'af3d1397db31f4ff63c46fa435ac2b66' => array(
		'title' => '报审资料清单',
		'fields' => 'orderno,name,shangji,bixuanxiang,beizhu',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;shangji&#39;=>&#39;上级&#39;,&#39;bixuanxiang&#39;=>&#39;必选项&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoAvk',
		'checkformodel' => 'MisAutoAvk',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'd535c6e89086ed9608a38aae8ef4adea' => array(
		'title' => '基础资料规定目录-业务资料',
		'fields' => 'orderno,beizhu,name',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoNmp',
		'checkformodel' => 'MisAutoNmp',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => 'KOexu+WeiyDljIXlkKsgJ+S4muWKoei1hOaWmScp',
		'rulesinfo' => 'YToyOntzOjc6ImxlaXhpbmciO2E6MTp7aTowO2E6MTE6e3M6NDoibmFtZSI7czo3OiJsZWl4aW5nIjtzOjY6InN5bWJvbCI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjY6Iuexu+WeiyI7czo3OiJzaG93dmFsIjtzOjEyOiLkuJrliqHotYTmlpkiO3M6MzoidmFsIjthOjE6e2k6MDtzOjE6IjEiO31zOjc6ImNvbnRyb2wiO3M6Njoic2VsZWN0IjtzOjY6IndpZGdldCI7czoxMzoicm9sZXRleHRpbnNldCI7czo0OiJzb3J0IjtpOjA7czo3OiJsZWZ0aXB0IjtOO3M6ODoicmlnaHRpcHQiO047czo5OiJjZW50ZXJ0aXAiO047fX1zOjY6Im1hcHNxbCI7YToxOntpOjA7YToyOntzOjQ6Im5hbWUiO3M6Mzoic3FsIjtzOjM6InNxbCI7czowOiIiO319fQ==',
		'rules' => 'leixing in(1)',
		'condition' => 'leixing in(1)',
		'status' => '1',
		'level' => '15',
	),
	'e1bb85021873c2672b21597bd2f99d7a' => array(
		'title' => '基础资料归档目录-风控资料',
		'fields' => 'orderno,beizhu,name',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoNmp',
		'checkformodel' => 'MisAutoNmp',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => 'KOexu+WeiyDljIXlkKsgJ+mjjuaOp+i1hOaWmScp',
		'rulesinfo' => 'YToyOntzOjc6ImxlaXhpbmciO2E6MTp7aTowO2E6MTE6e3M6NDoibmFtZSI7czo3OiJsZWl4aW5nIjtzOjY6InN5bWJvbCI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjY6Iuexu+WeiyI7czo3OiJzaG93dmFsIjtzOjEyOiLpo47mjqfotYTmlpkiO3M6MzoidmFsIjthOjE6e2k6MDtzOjE6IjIiO31zOjc6ImNvbnRyb2wiO3M6Njoic2VsZWN0IjtzOjY6IndpZGdldCI7czoxMzoicm9sZXRleHRpbnNldCI7czo0OiJzb3J0IjtpOjA7czo3OiJsZWZ0aXB0IjtOO3M6ODoicmlnaHRpcHQiO047czo5OiJjZW50ZXJ0aXAiO047fX1zOjY6Im1hcHNxbCI7YToxOntpOjA7YToyOntzOjQ6Im5hbWUiO3M6Mzoic3FsIjtzOjM6InNxbCI7czowOiIiO319fQ==',
		'rules' => 'leixing in(2)',
		'condition' => 'leixing in(2)',
		'status' => '1',
		'level' => '15',
	),
	'ea6f9534781e772d8b07db66f6ed3475' => array(
		'title' => '反担保措施类型',
		'fields' => 'orderno,name,shangji,beizhu',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;shangji&#39;=>&#39;上级&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoGkf',
		'checkformodel' => 'MisAutoGkf',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'57847cbfcc0bffcf3d99c29c4f720d27' => array(
		'title' => '合同类型',
		'fields' => 'orderno,name,beizhu',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoWyj',
		'checkformodel' => 'MisAutoWyj',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'440ca5e6608b2dbd1ca1e0f906077bb7' => array(
		'title' => '主体规模',
		'fields' => 'mingchen,orderno,beizhu',
		'checkforfields' => '&#39;mingchen&#39;=>&#39;名称&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;beizhu&#39;=>&#39;备注&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoRrf',
		'checkformodel' => 'MisAutoRrf',
		'filed' => 'orderno',
		'filed1' => 'orderno',
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'41dc92f8586ba69e459d910b0329672e' => array(
		'title' => '项目列表',
		'fields' => 'orderno,name,typeid,zt,hy,cyl,sjid',
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;项目名称&#39;,&#39;typeid&#39;=>&#39;业务类型&#39;,&#39;zt&#39;=>&#39;主体&#39;,&#39;hy&#39;=>&#39;行业&#39;,&#39;cyl&#39;=>&#39;产业链&#39;,&#39;sjid&#39;=>&#39;商机编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoEbm',
		'checkformodel' => 'MisAutoEbm',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'4abfefbcb9d5e10ac9ed50966f04424e' => array(
		'title' => '客户档案基本参照',
		'fields' => 'kehumingchen,quyu,zhutixingzhi,guimo,huodetujing,xingye,chanyelian,orderno',
		'checkforfields' => '&#39;kehumingchen&#39;=>&#39;客户名称&#39;,&#39;quyu&#39;=>&#39;区域&#39;,&#39;zhutixingzhi&#39;=>&#39;主体性质&#39;,&#39;guimo&#39;=>&#39;规模&#39;,&#39;huodetujing&#39;=>&#39;获得途径&#39;,&#39;xingye&#39;=>&#39;行业&#39;,&#39;chanyelian&#39;=>&#39;产业链&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoCbj',
		'checkformodel' => 'MisAutoCbj',
		'filed' => 'kehumingchen',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'73e5f3c14c563053c4730e1e21b4d470' => array(
		'title' => 'ND合作银行档案',
		'fields' => 'orderno,yinxingmingchen,suoshuyinxing,yinxingzhanghao,yinxingdizhi,baozhengjinzhanghao,baozhengjinzhanghumi,shouxinedu,yingfuyinxingbaozhen,yingshoukehubaozheng,shouxinqixian,danbizuigaoe,teshuwenbenjiyaoqiu',
		'checkforfields' => '&#39;orderno&#39;=>&#39;单据编号&#39;,&#39;yinxingmingchen&#39;=>&#39;银行名称&#39;,&#39;suoshuyinxing&#39;=>&#39;所属银行&#39;,&#39;yinxingzhanghao&#39;=>&#39;银行账号&#39;,&#39;yinxingdizhi&#39;=>&#39;银行地址&#39;,&#39;baozhengjinzhanghao&#39;=>&#39;保证金账号&#39;,&#39;baozhengjinzhanghumi&#39;=>&#39;保证金账户名&#39;,&#39;shouxinedu&#39;=>&#39;授信额度&#39;,&#39;yingfuyinxingbaozhen&#39;=>&#39;应付银行保证金比例&#39;,&#39;yingshoukehubaozheng&#39;=>&#39;应收客户保证金比例&#39;,&#39;shouxinqixian&#39;=>&#39;授信期限&#39;,&#39;danbizuigaoe&#39;=>&#39;单笔最高额&#39;,&#39;teshuwenbenjiyaoqiu&#39;=>&#39;特殊文本及要求&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoIxk',
		'checkformodel' => 'MisAutoIxk',
		'filed' => 'yinxingmingchen',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'6ba36af0b259d11ebcb06595cedf255f' => array(
		'title' => '公司信息',
		'fields' => 'orderno,name,juridicalperson,address,tel,fax,bankid,bank',
		'checkforfields' => '&#39;orderno&#39;=>&#39;公司编码&#39;,&#39;name&#39;=>&#39;公司名称&#39;,&#39;juridicalperson&#39;=>&#39;法人&#39;,&#39;address&#39;=>&#39;公司地址&#39;,&#39;tel&#39;=>&#39;联系电话&#39;,&#39;fax&#39;=>&#39;传真&#39;,&#39;bankid&#39;=>&#39;开户银行&#39;,&#39;bank&#39;=>&#39;银行账号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisSystemCompany',
		'checkformodel' => 'MisSystemCompany',
		'filed' => 'name',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'8480a35d9adc2bb33c6fbbfc6a3413a3' => array(
		'title' => '反担保措施参照',
		'fields' => 'orderno,xiangmubianhao,xiangmumingchen,kehu,cuoshileixing,zuojia',
		'checkforfields' => '&#39;orderno&#39;=>&#39;反担保措施编号&#39;,&#39;xiangmubianhao&#39;=>&#39;项目编号&#39;,&#39;xiangmumingchen&#39;=>&#39;项目名称&#39;,&#39;kehu&#39;=>&#39;客户&#39;,&#39;cuoshileixing&#39;=>&#39;措施类型&#39;,&#39;zuojia&#39;=>&#39;作价&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoByp',
		'checkformodel' => 'MisAutoByp',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'd67014c26ab138fbe05d120175971dc3' => array(
		'title' => '批复单参照',
		'fields' => 'xiangmumingchen,xiangmubianma,orderno',
		'checkforfields' => '&#39;xiangmumingchen&#39;=>&#39;项目名称&#39;,&#39;xiangmubianma&#39;=>&#39;项目编码&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoDap',
		'checkformodel' => 'MisAutoDap',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'08451ff379e2b0cdba40133024867fe0' => array(
		'title' => '评估机构参照',
		'fields' => 'pinggujigoumingchen,orderno',
		'checkforfields' => '&#39;pinggujigoumingchen&#39;=>&#39;评估机构名称&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoNoa',
		'checkformodel' => 'MisAutoNoa',
		'filed' => 'pinggujigoumingchen',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'5e4dded11e8e1c26d22373cf35b19872' => array(
		'title' => '用款生单',
		'fields' => 'bencishenqingyongkuanjine,orderno',
		'checkforfields' => '&#39;bencishenqingyongkuanjine&#39;=>&#39;本次申请用款金额&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoWkj',
		'checkformodel' => 'MisAutoWkj',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'e8a96255b0a8521839e7daff9833258f' => array(
		'title' => '项目基本参照',
		'fields' => 'kehumingchen,zhuti,xingye,xiangmumingchen,chanyelian,daikuanyongtu,yixiangyinxing,yixiangdanbaofeilv,zhengshidanbaofeilv,yinxinglilv,shenqingjine,pingshenjine,shenqingyewuqixian,pingshenqixian,huaikuanfangshi,baozhengjinzhanghao,zaibaojine,shidaidaichang,daichangjine,dangqiankehmc,xiangmujieduan,xiangmubianma,shangjibianhao,canzhaoxiangmubianha,zhudiao,fudiao,kehudizhi,youbian,hezuoyinxing,yifangkuanjine,orderno,shengyujine',
		'checkforfields' => '&#39;kehumingchen&#39;=>&#39;客户名称&#39;,&#39;zhuti&#39;=>&#39;主体&#39;,&#39;xingye&#39;=>&#39;行业&#39;,&#39;xiangmumingchen&#39;=>&#39;项目名称&#39;,&#39;chanyelian&#39;=>&#39;产业链&#39;,&#39;daikuanyongtu&#39;=>&#39;贷款用途&#39;,&#39;yixiangyinxing&#39;=>&#39;意向银行&#39;,&#39;yixiangdanbaofeilv&#39;=>&#39;意向担保费率&#39;,&#39;zhengshidanbaofeilv&#39;=>&#39;正式担保费率&#39;,&#39;yinxinglilv&#39;=>&#39;银行利率&#39;,&#39;shenqingjine&#39;=>&#39;申请金额&#39;,&#39;pingshenjine&#39;=>&#39;评审金额&#39;,&#39;shenqingyewuqixian&#39;=>&#39;申请业务期限&#39;,&#39;pingshenqixian&#39;=>&#39;评审期限&#39;,&#39;huaikuanfangshi&#39;=>&#39;还款方式&#39;,&#39;baozhengjinzhanghao&#39;=>&#39;保证金账号&#39;,&#39;zaibaojine&#39;=>&#39;在保金额&#39;,&#39;shidaidaichang&#39;=>&#39;是代带偿&#39;,&#39;daichangjine&#39;=>&#39;代偿金额&#39;,&#39;dangqiankehmc&#39;=>&#39;当前客户名称&#39;,&#39;xiangmujieduan&#39;=>&#39;项目阶段&#39;,&#39;xiangmubianma&#39;=>&#39;项目编码&#39;,&#39;shangjibianhao&#39;=>&#39;商机编号&#39;,&#39;canzhaoxiangmubianha&#39;=>&#39;参照项目编号&#39;,&#39;zhudiao&#39;=>&#39;主调&#39;,&#39;fudiao&#39;=>&#39;辅调&#39;,&#39;kehudizhi&#39;=>&#39;客户地址&#39;,&#39;youbian&#39;=>&#39;邮编&#39;,&#39;hezuoyinxing&#39;=>&#39;合作银行&#39;,&#39;yifangkuanjine&#39;=>&#39;已放款金额&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;shengyujine&#39;=>&#39;剩余金额&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoPvb',
		'checkformodel' => 'MisAutoPvb',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'42e7bd4b40a7f633e18f95ed243e45e4' => array(
		'title' => 'ND主合同',
		'fields' => 'hezuoyinxing,yongkuandanhao,jiekuanjine,jiekuanhetonghao,baozhenghetonghao,zhuangtai,weituodaikuanjiekuanhetonghao,weituodaikuanweituohetonghao,kehubianma,xiangmubianma,orderno',
		'checkforfields' => '&#39;hezuoyinxing&#39;=>&#39;合作银行&#39;,&#39;yongkuandanhao&#39;=>&#39;用款单号&#39;,&#39;jiekuanjine&#39;=>&#39;借款金额&#39;,&#39;jiekuanhetonghao&#39;=>&#39;借款合同号&#39;,&#39;baozhenghetonghao&#39;=>&#39;保证合同号&#39;,&#39;zhuangtai&#39;=>&#39;状态&#39;,&#39;weituodaikuanjiekuanhetonghao&#39;=>&#39;委托贷款借款合同号&#39;,&#39;weituodaikuanweituohetonghao&#39;=>&#39;委托贷款委托合同号&#39;,&#39;kehubianma&#39;=>&#39;客户编码&#39;,&#39;xiangmubianma&#39;=>&#39;项目编码&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoMwt',
		'checkformodel' => 'MisAutoMwt',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'b83070c4f315560461b0270fcc53b0cf' => array(
		'title' => '存出保证金生单',
		'fields' => 'orderno,fangkuanyinxing,baozhengjinlv',
		'checkforfields' => '&#39;orderno&#39;=>&#39;单据编号&#39;,&#39;fangkuanyinxing&#39;=>&#39;放款银行&#39;,&#39;baozhengjinlv&#39;=>&#39;保证金率&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoCnx',
		'checkformodel' => 'MisAutoCnx',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'0ac1f63ef44b0acb913e035ec333d3a4' => array(
		'title' => '批复放款参照end',
		'fields' => 'orderno,xiangmubianma',
		'checkforfields' => '&#39;orderno&#39;=>&#39;批复单号&#39;,&#39;xiangmubianma&#39;=>&#39;项目编码&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoDap',
		'checkformodel' => 'MisAutoDap',
		'filed' => 'xiangmubianma',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'proid' => '982',
		'fieldback' => '7070,7071,7072,7104,7105',
		'dt' => array(
			'mis_auto_wrmve_sub_datatable21' => array(
				'title' => '反担保措施明细',
				'datename' => 'mis_auto_wrmve_sub_datatable21',
				'list' => array(
					'fandanbaocuoshibanha' => array(
						'title' => '反担保措施编号',
						'category' => 'lookup',
						'length' => '30',
					),
					'fandanbaocuoshxinx' => array(
						'title' => '反担保措施信息',
						'category' => 'text',
						'length' => '60',
					),
					'taxiangquanzhengbianhao' => array(
						'title' => '他项权证编号',
						'category' => 'text',
						'length' => '100',
					),
					'zuojia' => array(
						'title' => '作价',
						'category' => 'text',
						'length' => '18,6',
					),
					'beizhu' => array(
						'title' => '备注',
						'category' => 'text',
						'length' => '90',
					),
				),
			),
		),
	),
	'26e13cb905ab56a671c919626122067d' => array(
		'title' => '人员档案参照',
		'fields' => 'id,orderno,name,sex,deptid,worktype,chinaid',
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;员工编号&#39;,&#39;name&#39;=>&#39;姓名&#39;,&#39;sex&#39;=>&#39;性别&#39;,&#39;deptid&#39;=>&#39;部门&#39;,&#39;worktype&#39;=>&#39;岗位&#39;,&#39;chinaid&#39;=>&#39;身份证号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelManagement',
		'checkformodel' => 'MisHrPersonnelManagement',
		'filed' => 'name',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'ce52fb8a98fed91856a0fba847cc0cee' => array(
		'title' => '批复反担保措施生单',
		'fields' => 'orderno,xiangmubianma,kehumingchen,xiangmumingchen,pifujine,pifuqixian',
		'checkforfields' => '&#39;orderno&#39;=>&#39;批复编号&#39;,&#39;xiangmubianma&#39;=>&#39;项目编码&#39;,&#39;kehumingchen&#39;=>&#39;客户名称&#39;,&#39;xiangmumingchen&#39;=>&#39;项目名称&#39;,&#39;pifujine&#39;=>&#39;批复金额&#39;,&#39;pifuqixian&#39;=>&#39;批复期限&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoDap',
		'checkformodel' => 'MisAutoDap',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'proid' => '982',
		'fieldback' => '7070,7071,7072,7104,7105',
		'dt' => array(
			'mis_auto_wrmve_sub_datatable21' => array(
				'title' => '反担保措施明细',
				'datename' => 'mis_auto_wrmve_sub_datatable21',
				'list' => array(
					'fandanbaocuoshibanha' => array(
						'title' => '反担保措施编号',
						'category' => 'lookup',
						'length' => '30',
					),
					'fandanbaocuoshxinx' => array(
						'title' => '反担保措施信息',
						'category' => 'text',
						'length' => '60',
					),
					'taxiangquanzhengbianhao' => array(
						'title' => '他项权证编号',
						'category' => 'text',
						'length' => '100',
					),
					'zuojia' => array(
						'title' => '作价',
						'category' => 'text',
						'length' => '18,6',
					),
					'beizhu' => array(
						'title' => '备注',
						'category' => 'text',
						'length' => '90',
					),
				),
			),
		),
	),
	'bae8f0d56beab587072b16269ed3b7e4' => array(
		'title' => '用款通知书参照',
		'fields' => 'orderno,xiangmubianma,kehumingchen,xiangmumingchen,fangkuanyinxing,baozhengjinlv,baozhengjinjine,fangkuanjine,zongdanbaojine,yiyongkuanjine,shengyudanbaojine',
		'checkforfields' => '&#39;orderno&#39;=>&#39;单据编号&#39;,&#39;xiangmubianma&#39;=>&#39;项目编码&#39;,&#39;kehumingchen&#39;=>&#39;客户名称&#39;,&#39;xiangmumingchen&#39;=>&#39;项目名称&#39;,&#39;fangkuanyinxing&#39;=>&#39;放款银行&#39;,&#39;baozhengjinlv&#39;=>&#39;保证金率&#39;,&#39;baozhengjinjine&#39;=>&#39;保证金金额&#39;,&#39;fangkuanjine&#39;=>&#39;放款金额&#39;,&#39;zongdanbaojine&#39;=>&#39;总担保金额&#39;,&#39;yiyongkuanjine&#39;=>&#39;已用款金额&#39;,&#39;shengyudanbaojine&#39;=>&#39;剩余担保金额&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoYtd',
		'checkformodel' => 'MisAutoYtd',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'orderno',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'c1a42f64173760e5501d9794b56d65a9' => array(
		'title' => '批复放款参照视图',
		'fields' => 'id,orderno,xiangmubianma,fangkuanriqi,fangkuanjine',
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoDap',
		'filed' => 'orderno',
		'val' => 'orderno',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'viewname' => 'pf_fk_views',
		'viewtype' => '1',
	),
);

?>