<?php 
return array(
	'debit' => array(
		'remark' => '基础设置-财务相关-会计科目，模型',
		'status' => '1',
		'name' => '基础设置-财务相关-会计科目，模型',
		'conftype' => '0',
		'level' => '15',
		'debit' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'credit' => array(
		'remark' => '基础设置-财务相关-会计科目，模型',
		'status' => '1',
		'name' => '基础设置-财务相关-会计科目，模型',
		'conftype' => '0',
		'level' => '15',
		'credit' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'sex' => array(
		'remark' => '通用-性别类数组',
		'status' => '1',
		'name' => '通用-性别类数组',
		'conftype' => '0',
		'level' => '15',
		'sex' => array(
			'0' => '女',
			'1' => '男',
		),
	),
	'status' => array(
		'remark' => '通用-状态类数组',
		'status' => array(
			'-1' => '禁用',
			'0' => '锁定',
			'1' => '正常',
		),
		'name' => '通用-状态类数组',
		'conftype' => '0',
		'level' => '15',
	),
	'positivestatus' => array(
		'remark' => '人事基本资料-转正状态，模型-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '人事基本资料-转正状态，模型-MisHrPersonnelPersonInfo',
		'conftype' => '0',
		'level' => '15',
		'positivestatus' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'working' => array(
		'remark' => '人事基本资料-离职状态，模型-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '人事基本资料-离职状态，模型-MisHrPersonnelPersonInfo',
		'conftype' => '0',
		'level' => '15',
		'working' => array(
			'0' => '离职',
			'1' => '在职',
		),
	),
	'workkind' => array(
		'remark' => '人事基本资料-工种，模型-MisHrPersonnelPersonInfo  这里是有问题的。如果是checkbox的话。组合出来的sql是 workkind in （非技，技术，实习）',
		'status' => '1',
		'name' => '人事基本资料-工种，模型-MisHrPersonnelPersonInfo  这里是有问题的。如果是checkbox的话。组合出来的sql是 workkind in （非技，技术，实习）',
		'conftype' => '0',
		'level' => '15',
		'workkind' => array(
			'1' => '技术',
			'2' => '非技',
			'3' => '实习',
			'4' => '普工',
		),
	),
	'reportmaintain' => array(
		'remark' => '人事工伤管理-工伤认定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'status' => '1',
		'name' => '人事工伤管理-工伤认定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'conftype' => '0',
		'level' => '15',
		'reportmaintain' => array(
			'是' => '离职',
			'非' => '在职',
		),
	),
	'elcomercioreport' => array(
		'remark' => '人事工伤管理-商保报案，模型-MisHrPersonnelIndustrialInjuryInfo',
		'status' => '1',
		'name' => '人事工伤管理-商保报案，模型-MisHrPersonnelIndustrialInjuryInfo',
		'conftype' => '0',
		'level' => '15',
		'elcomercioreport' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'maimidentify' => array(
		'remark' => '人事工伤管理-伤残鉴定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'status' => '1',
		'name' => '人事工伤管理-伤残鉴定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'conftype' => '0',
		'level' => '15',
		'maimidentify' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'interviewfirst' => array(
		'remark' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'conftype' => '0',
		'level' => '15',
		'interviewfirst' => array(
			'0' => '不合格',
			'1' => '合格',
			'2' => '放入人才库',
			'3' => '待定',
			'4' => '未面试',
		),
	),
	'interviewagain' => array(
		'remark' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'conftype' => '0',
		'level' => '15',
		'interviewagain' => array(
			'0' => '不合格',
			'1' => '合格',
			'2' => '放入人才库',
			'3' => '待定',
			'4' => '未面试',
		),
	),
	'introducemethod' => array(
		'remark' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'conftype' => '0',
		'level' => '15',
		'introducemethod' => array(
			'1' => '网络面试',
			'2' => '现场招聘',
			'3' => '内部介绍',
			'4' => '校园招聘',
			'5' => '猎头招聘',
			'6' => '其他方式',
		),
	),
	'quittype' => array(
		'remark' => '人事招骋 模型-MisHrPersonnelQuitInfo',
		'status' => '1',
		'name' => '人事招骋 模型-MisHrPersonnelQuitInfo',
		'conftype' => '0',
		'level' => '15',
		'quittype' => array(
			'19' => '辞职',
			'20' => '自离',
			'21' => '其他',
		),
	),
	'limittype' => array(
		'remark' => '人事员工合同 合同期限',
		'status' => '1',
		'name' => '人事员工合同 合同期限',
		'conftype' => '0',
		'level' => '15',
		'limittype' => array(
			'固定期' => '固定期',
			'无固定期' => '无固定期',
		),
	),
	'employeecontracttype' => array(
		'remark' => '人事员工合同 合同类型',
		'status' => '1',
		'name' => '人事员工合同 合同类型',
		'conftype' => '0',
		'level' => '15',
		'employeecontracttype' => array(
			'合同' => '合同',
			'协议' => '协议',
		),
	),
	'employeecontractstatus' => array(
		'remark' => '人事员工合同 合同状态',
		'status' => '1',
		'name' => '人事员工合同 合同状态',
		'conftype' => '0',
		'level' => '15',
		'employeecontractstatus' => array(
			'0' => '合同中',
			'1' => '已结束',
		),
	),
	'type' => array(
		'remark' => '人事外联合同管理 模型-MisHrOutsideBargain',
		'status' => '1',
		'name' => '人事外联合同管理 模型-MisHrOutsideBargain',
		'conftype' => '0',
		'level' => '15',
		'type' => array(
			'1' => '招聘合同',
			'2' => '工伤合同',
			'3' => '其他合同',
		),
	),
	'unittype' => array(
		'remark' => '产品单位 模型-MisProductUnit',
		'status' => '1',
		'name' => '产品单位 模型-MisProductUnit',
		'conftype' => '0',
		'level' => '15',
		'unittype' => array(
			'0' => '整数型',
			'1' => '浮点型',
		),
	),
	'leavetype' => array(
		'remark' => '人事外请假管理 模型-MisHrPersonnelLeaveInfo',
		'status' => '1',
		'name' => '人事外请假管理 模型-MisHrPersonnelLeaveInfo',
		'conftype' => '0',
		'level' => '15',
		'leavetype' => array(
			'1' => '招聘合同',
			'2' => '年假',
			'3' => '病假',
			'4' => '事假',
			'5' => '丧假',
			'6' => '婚假',
			'7' => '工伤假',
			'8' => '培训假',
			'9' => '补休',
			'10' => '其他',
			'53' => '现场招骋',
			'55' => '现场招骋',
			'60' => '锐成猎头',
		),
	),
	'yjzgltype' => array(
		'remark' => '外经证管理 模型-MisFinanceProjectWaijingzheng',
		'status' => '1',
		'name' => '外经证管理 模型-MisFinanceProjectWaijingzheng',
		'conftype' => '0',
		'level' => '15',
		'yjzgltype' => array(
			'1' => '合作方',
			'2' => '一般项目',
			'5' => '其他',
		),
	),
	'yuetongcard' => array(
		'remark' => '派车申请 模型-MisRequestCar',
		'status' => '1',
		'name' => '派车申请 模型-MisRequestCar',
		'conftype' => '0',
		'level' => '15',
		'yuetongcard' => array(
			'0' => '不需要',
			'1' => '需要',
		),
	),
	'dnbzgltype' => array(
		'remark' => '电脑配制管理 模型-MisComputer',
		'status' => '1',
		'name' => '电脑配制管理 模型-MisComputer',
		'conftype' => '0',
		'level' => '15',
		'dnbzgltype' => array(
			'1' => '台式机',
			'2' => '笔记本',
			'3' => '相机',
			'4' => '服务器',
			'5' => '打印机',
			'6' => '网络设备',
			'7' => '电话机',
			'8' => '其他',
		),
	),
	'dyxxorganization' => array(
		'remark' => '党员信息 模型-MisHrPartOrganization',
		'status' => '1',
		'name' => '党员信息 模型-MisHrPartOrganization',
		'conftype' => '0',
		'level' => '15',
		'dyxxorganization' => array(
			'1' => '正式',
			'2' => '预备',
		),
	),
	'dyxxadministration' => array(
		'remark' => '党员信息 模型-MisHrPartOrganization',
		'status' => '1',
		'name' => '党员信息 模型-MisHrPartOrganization',
		'conftype' => '0',
		'level' => '15',
		'dyxxadministration' => array(
			'1' => '是',
			'2' => '候选',
			'3' => '否',
		),
	),
	'yuangongBz' => array(
		'remark' => '员工基础资料管理 模型-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '员工基础资料管理 模型-MisHrPersonnelPersonInfo',
		'conftype' => '0',
		'level' => '15',
		'yuangongBz' => array(
			'1' => '监管',
			'2' => '守护',
			'3' => '押运',
			'4' => '行政',
			'5' => '驾驶员',
			'6' => '普通队员',
			'7' => '技术人员',
		),
	),
	'HrOutsideBargainHT' => array(
		'remark' => '人事外联合同 模型-MisHrOutsideBargain',
		'status' => '1',
		'name' => '人事外联合同 模型-MisHrOutsideBargain',
		'conftype' => '0',
		'level' => '15',
		'HrOutsideBargainHT' => array(
			'1' => '招聘合同',
			'2' => '工伤合同',
			'3' => '其他合同',
		),
	),
	'MisHrInvitereFormZP' => array(
		'remark' => '人员招聘管理 模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人员招聘管理 模型-MisHrInvitereForm',
		'conftype' => '0',
		'level' => '15',
		'MisHrInvitereFormZP' => array(
			'1' => '网络招聘',
			'2' => '现场招聘',
			'3' => '内部介绍',
			'4' => '校园招聘',
			'5' => '猎头招聘',
			'6' => '其他方式',
		),
	),
	'SystemLogSelect' => array(
		'remark' => '系统日志-SystemLog',
		'status' => '1',
		'name' => '系统日志-SystemLog',
		'conftype' => '0',
		'level' => '15',
		'SystemLogSelect' => array(
			'0' => '异常',
			'1' => '更新',
			'2' => '删除',
		),
	),
	'bxkctype' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'conftype' => '0',
		'level' => '15',
		'bxkctype' => array(
			'通用素质' => '通用素质',
			'企业文化' => '企业文化',
			'专业类' => '专业类',
			'管理类' => '管理类',
			'安全生产' => '安全生产',
		),
	),
	'bxkcclasssource' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'conftype' => '0',
		'level' => '15',
		'bxkcclasssource' => array(
			'企业内部' => '企业内部',
			'外训机构' => '外训机构',
			'院校' => '院校',
			'其他' => '其他',
		),
	),
	'bxkclevel' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'conftype' => '0',
		'level' => '15',
		'bxkclevel' => array(
			'无' => '无',
			'初级' => '初级',
			'中级' => '中级',
			'高级' => '高级',
		),
	),
	'bxkctrainform' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'conftype' => '0',
		'level' => '15',
		'bxkctrainform' => array(
			'讲座' => '讲座',
			'参观学习' => '参观学习',
			'视频' => '视频',
			'在岗学习' => '在岗学习',
			'其他' => '其他',
		),
	),
	'bxkcassessment' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'conftype' => '0',
		'level' => '15',
		'bxkcassessment' => array(
			'口试' => '口试',
			'笔试' => '笔试',
			'实操演练' => '实操演练',
			'其他' => '其他',
		),
	),
	'levels' => array(
		'remark' => '文章管理-MisKnowledgeManage',
		'status' => '1',
		'name' => '文章管理-MisKnowledgeManage',
		'conftype' => '0',
		'level' => '15',
		'levels' => array(
			'0' => '未知级别',
			'1' => 'A级',
			'2' => 'B级',
			'3' => 'C级',
			'4' => 'D级',
		),
	),
	'applicationtype' => array(
		'remark' => '人事申请管理-MisHrPersonnelApplicationInfo',
		'status' => '1',
		'name' => '人事申请管理-MisHrPersonnelApplicationInfo',
		'conftype' => '0',
		'level' => '15',
		'applicationtype' => array(
			'编制内申请' => '编制内申请',
			'编制外申请' => '编制外申请',
		),
	),
	'politicsstatus' => array(
		'remark' => '员工基础资料管理-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '员工基础资料管理-MisHrPersonnelPersonInfo',
		'conftype' => '0',
		'level' => '15',
		'politicsstatus' => array(
			'群众' => '群众',
			'团员' => '团员',
			'党员' => '党员',
		),
	),
	'ismarry' => array(
		'remark' => '员工基础资料 - 婚姻状况',
		'status' => '1',
		'name' => '员工基础资料 - 婚姻状况',
		'conftype' => '0',
		'level' => '15',
		'ismarry' => array(
			'未婚' => '未婚',
			'已婚' => '已婚',
			'离异' => '离异',
			'丧偶' => '丧偶',
		),
	),
	'probationcycle' => array(
		'remark' => '员工基础资料 - 婚姻状况',
		'status' => '1',
		'name' => '员工基础资料 - 婚姻状况',
		'conftype' => '0',
		'level' => '15',
		'probationcycle' => array(
			'1' => '1个月',
			'2' => '2个月',
			'3' => '3个月',
			'4' => '4个月',
			'5' => '5个月',
			'6' => '6个月',
			'7' => '7个月',
			'8' => '8个月',
			'9' => '9个月',
			'10' => '10个月',
			'11' => '11个月',
			'12' => '12个月',
		),
	),
	'linkonecontent' => array(
		'remark' => '绩效评估管理-MisHrPersonnelAppraisalInfo',
		'status' => '1',
		'name' => '绩效评估管理-MisHrPersonnelAppraisalInfo',
		'conftype' => '0',
		'level' => '15',
		'linkonecontent' => array(
			'0' => '未评估',
			'1' => '已评估',
		),
	),
	'business_type' => array(
		'remark' => '车辆管理加油记录-MisCarAddOilInfo',
		'status' => '1',
		'name' => '车辆管理加油记录-MisCarAddOilInfo',
		'conftype' => '0',
		'level' => '15',
		'business_type' => array(
			'0' => '圈钱',
			'1' => '加油',
			'2' => '异地圈钱',
		),
	),
	'MisTaskInformation_executingstatus' => array(
		'remark' => '任务动态 模型-MisTaskInformation',
		'status' => '1',
		'name' => '任务动态 模型-MisTaskInformation',
		'conftype' => '0',
		'level' => '15',
		'MisTaskInformation_executingstatus' => array(
			'0' => '未启动',
			'1' => '未查看',
			'2' => '已查看',
			'3' => '进行中',
			'4' => '终止',
			'5' => '打回',
			'6' => '结束',
		),
	),
	'fixed' => array(
		'remark' => '行政的日常维护记录-MisLogistcsFixLog',
		'status' => '1',
		'name' => '行政的日常维护记录-MisLogistcsFixLog',
		'conftype' => '0',
		'level' => '15',
		'fixed' => array(
			'1' => '修复',
			'2' => '未修复',
			'3' => '报废',
			'4' => '外修',
			'5' => '报告状态',
		),
	),
	'falut_type' => array(
		'remark' => '行政的日常维护记录-MisLogistcsFixLog',
		'status' => '1',
		'name' => '行政的日常维护记录-MisLogistcsFixLog',
		'conftype' => '0',
		'level' => '15',
		'falut_type' => array(
			'1' => '结排水',
			'2' => '电路',
			'3' => '电气设备',
			'4' => '其它',
		),
	),
	'makeinvoicetype' => array(
		'remark' => '发票信息',
		'status' => '1',
		'name' => '发票信息',
		'conftype' => '0',
		'level' => '15',
		'makeinvoicetype' => array(
			'1' => '普通发票',
			'2' => '增值税发票',
		),
	),
	'projectmakeinvoicetype' => array(
		'remark' => '发票信息',
		'status' => '1',
		'name' => '发票信息',
		'conftype' => '0',
		'level' => '15',
		'projectmakeinvoicetype' => array(
			'2' => '增值税发票',
			'3' => '地税服务费',
			'4' => '地税建安发票',
		),
	),
	'financemakeinvoicetype' => array(
		'remark' => '发票信息 便于财务开票查看',
		'status' => '1',
		'name' => '发票信息 便于财务开票查看',
		'conftype' => '0',
		'level' => '15',
		'financemakeinvoicetype' => array(
			'1' => '普通发票',
			'2' => '增值税发票',
			'3' => '地税服务费',
			'4' => '地税建安发票',
		),
	),
	'chargetypelist' => array(
		'remark' => '发票开具方式',
		'status' => '1',
		'name' => '发票开具方式',
		'conftype' => '0',
		'level' => '15',
		'chargetypelist' => array(
			'1' => '月',
			'2' => '年',
			'3' => '季度',
			'4' => '全款',
			'5' => '半年',
		),
	),
	'persontype' => array(
		'remark' => '人力资源 -人事招聘 -人员类型',
		'status' => '1',
		'name' => '人力资源 -人事招聘 -人员类型',
		'conftype' => '0',
		'level' => '15',
		'persontype' => array(
			'1' => '普通',
			'2' => '特殊',
		),
	),
	'equipmenttype' => array(
		'remark' => '办公设备的类型MisWorkFacilityManage',
		'status' => '1',
		'name' => '办公设备的类型MisWorkFacilityManage',
		'conftype' => '0',
		'level' => '15',
		'equipmenttype' => array(
			'1' => '电脑',
			'2' => '打印机',
			'3' => '空调',
			'4' => '文件柜',
			'5' => '其他',
		),
	),
	'customertype' => array(
		'remark' => '部门类型配置',
		'status' => '1',
		'name' => '部门类型配置',
		'conftype' => '0',
		'level' => '15',
		'customertype' => array(
			'1' => '人力防范',
			'2' => '技术防范',
			'3' => '民爆守押',
		),
	),
	'customervitalityid' => array(
		'remark' => '客户状态',
		'status' => '1',
		'name' => '客户状态',
		'conftype' => '0',
		'level' => '15',
		'customervitalityid' => array(
			'正常' => '正常',
			'流失' => '流失',
		),
	),
	'oaarchivesmanagetype' => array(
		'remark' => '档案管理类型：MisOaArchivesManage',
		'status' => '1',
		'name' => '档案管理类型：MisOaArchivesManage',
		'conftype' => '0',
		'level' => '15',
		'oaarchivesmanagetype' => array(
			'1' => '文书',
			'2' => '业务',
		),
	),
	'specialemployeemanagepoliticsstatus' => array(
		'remark' => '特殊人员管理MisBusinessSpecialEmployeeManage',
		'status' => '1',
		'name' => '特殊人员管理MisBusinessSpecialEmployeeManage',
		'conftype' => '0',
		'level' => '15',
		'specialemployeemanagepoliticsstatus' => array(
			'1' => '团员',
			'2' => '群众',
			'3' => '党员',
			'4' => '预备党员',
			'5' => '其他',
		),
	),
	'carsource' => array(
		'remark' => '国产还是进口',
		'status' => '1',
		'name' => '国产还是进口',
		'conftype' => '0',
		'level' => '15',
		'carsource' => array(
			'1' => '国产',
			'2' => '进口',
		),
	),
	'airconditioningsystem' => array(
		'remark' => '空调系统',
		'status' => '1',
		'name' => '空调系统',
		'conftype' => '0',
		'level' => '15',
		'airconditioningsystem' => array(
			'1' => '其他',
			'2' => '制冷',
			'3' => '采暖',
		),
	),
	'abs' => array(
		'remark' => '防抱制动装置(ABS)',
		'status' => '1',
		'name' => '防抱制动装置(ABS)',
		'conftype' => '0',
		'level' => '15',
		'abs' => array(
			'0' => '无',
			'1' => '有',
		),
	),
	'carbelong' => array(
		'remark' => '车辆信息',
		'status' => '1',
		'name' => '车辆信息',
		'conftype' => '0',
		'level' => '15',
		'carbelong' => array(
			'2' => '公共所有',
		),
	),
	'carcolour' => array(
		'remark' => '车辆颜色配置',
		'status' => '1',
		'name' => '车辆颜色配置',
		'conftype' => '0',
		'level' => '15',
		'carcolour' => array(
			'银色' => '银色',
			'黄色' => '黄色',
			'灰色' => '灰色',
			'蓝色' => '蓝色',
			'白色' => '白色',
			'红色' => '红色',
			'黑色' => '黑色',
			'其他' => '其他',
		),
	),
	'fueltype' => array(
		'remark' => '燃料种类',
		'status' => '1',
		'name' => '燃料种类',
		'conftype' => '0',
		'level' => '15',
		'fueltype' => array(
			'0号柴油' => '0号柴油',
			'93号汽油' => '93号汽油',
			'97号汽油' => '97号汽油',
		),
	),
	'responsibility' => array(
		'remark' => '伤病管理',
		'status' => '1',
		'name' => '伤病管理',
		'conftype' => '0',
		'level' => '15',
		'responsibility' => array(
			'1' => '6个月',
			'2' => '12个月',
			'3' => '24个月',
		),
	),
	'healback' => array(
		'remark' => '伤病管理--治愈情况',
		'status' => '1',
		'name' => '伤病管理--治愈情况',
		'conftype' => '0',
		'level' => '15',
		'healback' => array(
			'1' => '治疗中',
			'2' => '已治愈',
			'3' => '未开始',
			'4' => '已超期',
		),
	),
	'agreetypeid' => array(
		'remark' => '入职办理 ,合约性质',
		'status' => '1',
		'name' => '入职办理 ,合约性质',
		'conftype' => '0',
		'level' => '15',
		'agreetypeid' => array(
			'1' => '合同',
			'2' => '兼职',
			'3' => '自主择业',
			'4' => '4050',
			'5' => '退休',
		),
	),
	'accounttype' => array(
		'remark' => '员工管理 户口类型',
		'status' => '1',
		'name' => '员工管理 户口类型',
		'conftype' => '0',
		'level' => '15',
		'accounttype' => array(
			'0' => '城镇',
			'1' => '农村',
		),
	),
	'top' => array(
		'remark' => '系统公告,是否置顶',
		'status' => '1',
		'name' => '系统公告,是否置顶',
		'conftype' => '0',
		'level' => '15',
		'top' => array(
			'1' => '是',
			'2' => '否',
		),
	),
	'commit' => array(
		'remark' => '系统公告,提交状态',
		'status' => '1',
		'name' => '系统公告,提交状态',
		'conftype' => '0',
		'level' => '15',
		'commit' => array(
			'1' => '已发布',
			'2' => '待审核',
			'3' => '审核未通过',
			'4' => '已终止',
			'5' => '新建',
		),
	),
	'hurtcondition' => array(
		'remark' => '工伤 伤势情况',
		'status' => '1',
		'name' => '工伤 伤势情况',
		'conftype' => '0',
		'level' => '15',
		'hurtcondition' => array(
			'1' => '轻微',
			'2' => '一般',
			'3' => '严重',
			'4' => '死亡',
			'5' => '其他',
		),
	),
	'disposestage' => array(
		'remark' => '工伤处理阶段',
		'status' => '1',
		'name' => '工伤处理阶段',
		'conftype' => '0',
		'level' => '15',
		'disposestage' => array(
			'1' => '准备资料',
			'2' => '社保认定中',
			'3' => '待康复',
			'4' => '评残或放弃',
			'5' => '报销',
			'6' => '冲账',
			'7' => '完结',
		),
	),
	'auditstatus' => array(
		'remark' => '工伤处理阶段',
		'status' => '1',
		'name' => '工伤处理阶段',
		'conftype' => '0',
		'level' => '15',
		'auditstatus' => array(
			'1' => '审核通过',
			'0' => '审核未通过',
		),
	),
	'linkprefix' => array(
		'remark' => '网址前缀',
		'status' => '1',
		'name' => '网址前缀',
		'conftype' => '0',
		'level' => '15',
		'linkprefix' => array(
			'1' => 'http://',
			'2' => 'https://',
		),
	),
	'roleinexp' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => NULL,
		'conftype' => '0',
		'level' => '15',
		'roleinexp' => array(
			'1' => '等于',
			'2' => '不等于',
			'3' => '大于',
			'4' => '大于等于',
			'5' => '小于',
			'6' => '小于等于',
		),
	),
	'roleexp' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => NULL,
		'conftype' => '0',
		'level' => '15',
		'roleexp' => array(
			'1' => '=',
			'2' => '!=',
			'3' => '&gt;',
			'4' => '&gt;=',
			'5' => '&lt;',
			'6' => '&lt;=',
		),
	),
	'roletextinexp' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => '流程管理规则符号',
		'conftype' => '0',
		'level' => '15',
		'roletextinexp' => array(
			'1' => '等于',
			'2' => '不等于',
			'3' => '包含',
			'4' => '不包含',
			'5' => '大于',
			'6' => '大于等于',
			'7' => '小于',
			'8' => '小于等于',
		),
	),
	'roletextinset' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => '流程管理规则符号',
		'conftype' => '0',
		'level' => '15',
		'roletextinset' => array(
			'1' => '=',
			'2' => '!=',
			'3' => 'in',
			'4' => 'not in',
			'5' => '&gt;',
			'6' => '&gt;=',
			'7' => '&lt;',
			'8' => '&lt;=',
		),
	),
	'roleremind' => array(
		'remark' => '提醒条件',
		'status' => '1',
		'name' => '提醒条件',
		'conftype' => '0',
		'level' => '15',
		'roleremind' => array(
			'1' => '=',
			'2' => '!=',
			'3' => '>',
			'4' => '>=',
			'5' => '<',
			'6' => '<=',
		),
	),
	'phoneflag' => array(
		'remark' => '手机发送信息状态',
		'status' => '1',
		'name' => '手机发送信息状态',
		'conftype' => '0',
		'level' => '15',
		'phoneflag' => array(
			'0' => '未发送',
			'1' => '已发送',
		),
	),
	'employeeStatus' => array(
		'remark' => '人事 员工档案',
		'status' => '1',
		'name' => '人事 员工档案',
		'conftype' => '0',
		'level' => '15',
		'employeeStatus' => array(
			'1' => '转正',
			'2' => '离职',
			'3' => '请假',
			'4' => '异动',
		),
	),
	'computerfault' => array(
		'remark' => '电脑维护',
		'status' => '1',
		'name' => '电脑维护',
		'conftype' => '0',
		'level' => '15',
		'computerfault' => array(
			'1' => '系统',
			'2' => '硬件',
			'3' => '软件',
			'4' => '网络',
			'5' => '病毒感染',
			'6' => '其他',
		),
	),
	'statementreadstatus' => array(
		'remark' => '工作报告阅读',
		'status' => '1',
		'name' => '工作报告阅读',
		'conftype' => '0',
		'level' => '15',
		'statementreadstatus' => array(
			'0' => '未读',
			'1' => '已读',
		),
	),
	'forleavetype' => array(
		'remark' => '员工离职类别',
		'status' => '1',
		'name' => '员工离职类别',
		'conftype' => '0',
		'level' => '15',
		'forleavetype' => array(
			'95' => '辞退',
			'94' => '离职',
		),
	),
	'isinjob' => array(
		'remark' => '招聘是否入职',
		'status' => '1',
		'name' => '招聘是否入职',
		'conftype' => '0',
		'level' => '15',
		'isinjob' => array(
			'0' => '未入职',
			'1' => '已入职',
		),
	),
	'dealstatus' => array(
		'remark' => '协同事项 处理状态',
		'status' => '1',
		'name' => '协同事项 处理状态',
		'conftype' => '0',
		'level' => '15',
		'dealstatus' => array(
			'1' => '待发事项',
			'2' => '已发事项',
			'3' => '已办事项',
		),
	),
	'secretlevel' => array(
		'remark' => '协同事项 保密程度',
		'status' => '1',
		'name' => '协同事项 保密程度',
		'conftype' => '0',
		'level' => '15',
		'secretlevel' => array(
			'1' => '普通',
			'2' => '机密',
			'3' => '绝密',
		),
	),
	'urgentlevel' => array(
		'remark' => '协同事项 紧急程度',
		'status' => '1',
		'name' => '协同事项 紧急程度',
		'conftype' => '0',
		'level' => '15',
		'urgentlevel' => array(
			'1' => '普通',
			'2' => '紧急',
			'3' => '特急',
		),
	),
	'instancedostatus' => array(
		'remark' => '协同事项审核状态',
		'status' => '1',
		'name' => '协同事项审核状态',
		'conftype' => '0',
		'level' => '15',
		'instancedostatus' => array(
			'0' => '未处理',
			'1' => '已查看',
			'2' => '审核通过',
			'3' => '终止流程',
		),
	),
	'expensespaymethod' => array(
		'remark' => '报销支付类型',
		'status' => '1',
		'name' => '报销支付类型',
		'conftype' => '0',
		'level' => '15',
		'expensespaymethod' => array(
			'1' => '现金',
			'2' => '转工资卡',
			'3' => '冲借款',
		),
	),
	'apptype' => array(
		'remark' => 'app应用类型',
		'status' => '1',
		'name' => 'app应用类型',
		'conftype' => '0',
		'level' => '15',
		'apptype' => array(
			'1' => '办公应用',
			'2' => '个人应用',
			'3' => '网管工具',
			'4' => '快递查询',
			'5' => '休闲娱乐',
			'6' => '最新应用',
			'7' => '我的添加',
		),
	),
	'workplan' => array(
		'remark' => '工作计划',
		'status' => '1',
		'name' => '工作计划',
		'conftype' => '0',
		'level' => '15',
		'workplan' => array(
			'1' => '日计划',
			'2' => '周计划',
			'3' => '月计划',
		),
	),
	'operation' => array(
		'remark' => '设备 库存查看',
		'status' => '1',
		'name' => '设备 库存查看',
		'conftype' => '0',
		'level' => '15',
		'operation' => array(
			'1' => '添加',
			'2' => '修改',
			'3' => '申请',
			'4' => '异动',
			'5' => '归还',
		),
	),
	'operationdis' => array(
		'remark' => '设备 库存分布',
		'status' => '1',
		'name' => '设备 库存分布',
		'conftype' => '0',
		'level' => '15',
		'operationdis' => array(
			'1' => '申请',
			'2' => '异动',
		),
	),
	'county' => array(
		'remark' => '所属区县',
		'status' => '1',
		'name' => '所属区县',
		'conftype' => '0',
		'level' => '15',
		'county' => array(
			'渝中区' => '渝中区',
			'沙坪坝区' => '沙坪坝区',
			'江北区' => '江北区',
			'渝北区' => '渝北区',
			'南岸区' => '南岸区',
			'九龙坡区' => '九龙坡区',
			'大渡口区' => '大渡口区',
			'巴南区' => '巴南区',
			'北碚区' => '北碚区',
			'万州区' => '万州区',
			'涪陵区' => '涪陵区',
			'长寿区' => '长寿区',
			'黔江区' => '黔江区',
			'永川区' => '永川区',
			'江津区' => '江津区',
			'南川区' => '南川区',
			'合川区' => '合川区',
			'大足区' => '大足区',
			'綦江区' => '綦江区',
			'璧山区' => '璧山区',
			'潼南县' => '潼南县',
			'铜梁区' => '铜梁区',
			'荣昌区' => '荣昌区',
			'梁平县' => '梁平县',
			'城口县' => '城口县',
			'丰都县' => '丰都县',
			'垫江县' => '垫江县',
			'武隆县' => '武隆县',
			'忠县' => '忠县',
			'开县' => '开县',
			'云阳县' => '云阳县',
			'奉节县' => '奉节县',
			'巫山县' => '巫山县',
			'巫溪县' => '巫溪县',
			'石柱土家族自治县' => '石柱土家族自治县',
			'秀山土家族苗族自治县' => '秀山土家族苗族自治县',
			'酉阳土家族苗族自治县' => '酉阳土家族苗族自治县',
			'彭水苗族土家族自治县' => '彭水苗族土家族自治县',
		),
	),
	'clientsource' => array(
		'remark' => '客户来源',
		'status' => '1',
		'name' => '客户来源',
		'conftype' => '0',
		'level' => '15',
		'clientsource' => array(
			'大众媒体' => '大众媒体',
			'网络' => '网络',
			'区县工商联' => '区县工商联',
			'区县中小企业局' => '区县中小企业局',
			'商会协会' => '商会协会',
			'园区' => '园区',
			'客户推荐' => '客户推荐',
			'其他' => '其他',
		),
	),
	'test' => array(
		'remark' => '木',
		'status' => '1',
		'name' => '木',
		'conftype' => '0',
		'level' => '15',
		'test' => array(
			'2' => '苛',
		),
	),
	'roleinday' => array(
		'remark' => '提醒 时间',
		'status' => '1',
		'name' => NULL,
		'conftype' => '0',
		'level' => '15',
		'roleinday' => array(
			'day' => '天',
			'month' => '月',
			'year' => '年',
		),
	),
	'ABC' => array(
		'remark' => 'ces',
		'status' => '1',
		'name' => '123456',
		'conftype' => '0',
		'level' => '15',
		'ABC' => array(
			'' => '',
		),
	),
	'tool' => array(
		'remark' => '客户端类型',
		'status' => '1',
		'name' => '客户端类型',
		'conftype' => '0',
		'level' => '15',
		'tool' => array(
			'1' => '内网',
			'2' => '移动端',
			'3' => '内部系统',
			'4' => '其他渠道',
		),
	),
	'businessstatus' => array(
		'remark' => '商机状态',
		'status' => '1',
		'name' => '商机状态',
		'conftype' => '0',
		'level' => '15',
		'businessstatus' => array(
			'1' => '新建',
			'2' => '转交',
			'3' => '待处理',
			'4' => '转项目',
			'5' => '转储备',
			'6' => '审核中',
		),
	),
	'endstatus' => array(
		'remark' => '是否超期',
		'status' => '1',
		'name' => '是否超期',
		'conftype' => '0',
		'level' => '15',
		'endstatus' => array(
			'0' => '未超期',
			'1' => '已超期',
		),
	),
	'turnstatus' => array(
		'remark' => '是否转交',
		'status' => '1',
		'name' => '是否转交',
		'conftype' => '0',
		'level' => '15',
		'turnstatus' => array(
			'0' => '未转交',
			'1' => '已转交',
		),
	),
	'projectstatus' => array(
		'remark' => '参照项目状态',
		'status' => '1',
		'name' => '参照项目状态',
		'conftype' => '0',
		'level' => '15',
		'projectstatus' => array(
			'未完成' => '未完成',
			'进行中' => '进行中',
			'已完成' => '已完成',
		),
	),
	'YesOrNo' => array(
		'remark' => '标准是否判断',
		'status' => '1',
		'name' => '标准是否',
		'conftype' => '0',
		'level' => '15',
		'YesOrNo' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'taskComplete' => array(
		'remark' => '项目是否完成',
		'status' => '1',
		'name' => '项目是否完成',
		'conftype' => '0',
		'level' => '15',
		'taskComplete' => array(
			'未完成' => '未完成',
			'已完成' => '已完成',
		),
	),
	'systemRoamMas' => array(
		'remark' => '漫游数据类型',
		'status' => '1',
		'name' => '漫游数据类型',
		'conftype' => '0',
		'level' => '15',
		'systemRoamMas' => array(
			'0' => '未选择类型',
			'1' => '新增',
			'2' => '修改',
			'3' => '删除',
			'4' => '生成单据',
		),
	),
	'typeOfReviewMeeting' => array(
		'remark' => '评审会类型',
		'status' => '1',
		'name' => '评审会类型',
		'conftype' => '0',
		'level' => '15',
		'typeOfReviewMeeting' => array(
			'内部评审会' => '内部评审会',
			'专家评审会' => '专家评审会',
		),
	),
	'dateformatchoice' => array(
		'remark' => '日期格式',
		'status' => '1',
		'name' => '日期格式',
		'conftype' => '0',
		'level' => '15',
		'dateformatchoice' => array(
			'1' => 'yyyy-MM-dd',
			'2' => 'yyyy-MM-dd HH:mm',
			'3' => 'HH:mm',
			'4' => 'yyyy',
		),
	),
	'LD客户职务' => array(
		'remark' => 'LD客户职务',
		'status' => '1',
		'name' => 'enum001',
		'conftype' => '0',
		'level' => '15',
		'LD客户职务' => array(
			'法定代表人' => '法定代表人',
			'总经理' => '总经理',
			'技术总监' => '技术总监',
			'财务总监' => '财务总监',
			'副总经理' => '副总经理',
		),
	),
	'LD证件类型' => array(
		'remark' => 'LD证件类型',
		'status' => '1',
		'name' => 'enum002',
		'conftype' => '0',
		'level' => '15',
		'LD证件类型' => array(
			'身份证' => '身份证',
			'军官证' => '军官证',
		),
	),
	'LD性别' => array(
		'remark' => 'LD性别',
		'status' => '1',
		'name' => 'enum003',
		'conftype' => '0',
		'level' => '15',
		'LD性别' => array(
			'男' => '男',
			'女' => '女',
			'未知' => '未知',
		),
	),
	'LD是否' => array(
		'remark' => 'LD是否',
		'status' => '1',
		'name' => 'enum004',
		'conftype' => '0',
		'level' => '15',
		'LD是否' => array(
			'否' => '否',
			'是' => '是',
		),
	),
	'enum005' => array(
		'remark' => 'LD文化程度',
		'status' => '1',
		'name' => 'LD文化程度',
		'conftype' => '0',
		'level' => '15',
		'enum005' => array(
			'小学' => '小学',
			'初中' => '初中',
			'高中' => '高中',
			'大学' => '大学',
			'硕士' => '硕士',
			'博士' => '博士',
			'中专' => '中专',
		),
	),
	'nuem005' => array(
		'remark' => 'LD婚姻状况',
		'status' => '1',
		'name' => 'LD婚姻状况',
		'conftype' => '0',
		'level' => '15',
		'nuem005' => array(
			'未婚' => '未婚',
			'已婚' => '已婚',
			'未知' => '未知',
			'离异' => '离异',
		),
	),
	'LD民族' => array(
		'remark' => 'LD民族',
		'status' => '1',
		'name' => 'nuem006',
		'conftype' => '0',
		'level' => '15',
		'LD民族' => array(
			'汉族' => '汉族',
		),
	),
	'LD有无' => array(
		'remark' => 'LD有无',
		'status' => '1',
		'name' => 'nuem007',
		'conftype' => '0',
		'level' => '15',
		'LD有无' => array(
			'有' => '有',
			'无' => '无',
		),
	),
	'LD借贷方向' => array(
		'remark' => 'LD借贷方向',
		'status' => '1',
		'name' => 'nuem008',
		'conftype' => '0',
		'level' => '15',
		'LD借贷方向' => array(
			'借方' => '借方',
			'贷方' => '贷方',
		),
	),
	'ld00020' => array(
		'remark' => 'LD是否有效',
		'status' => '1',
		'name' => 'LD是否有效',
		'conftype' => '0',
		'level' => '15',
		'ld00020' => array(
			'有效' => '有效',
			'无效' => '无效',
		),
	),
	'NDCH' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND称呼',
		'conftype' => '0',
		'level' => '15',
		'NDCH' => array(
			'先生' => '先生',
			'女士' => '女士',
			'小姐' => '小姐',
		),
	),
	'ndclqq' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND材料是否齐全',
		'conftype' => '0',
		'level' => '15',
		'ndclqq' => array(
			'材料齐全' => '材料齐全',
			'材料不全' => '材料不全',
		),
	),
	'sfty' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND是否同意',
		'conftype' => '0',
		'level' => '15',
		'sfty' => array(
			'同意' => '同意',
			'不同意' => '不同意',
		),
	),
	'ywyy' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND是否有异议',
		'conftype' => '0',
		'level' => '15',
		'ywyy' => array(
			'有异议' => '有异议',
			'无异议' => '无异议',
		),
	),
	'zsdbhwcqk' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND正式担保函完成情况',
		'conftype' => '0',
		'level' => '15',
		'zsdbhwcqk' => array(
			'未完成' => '未完成',
			'已完成' => '已完成',
		),
	),
	'misdrules' => array(
		'remark' => '',
		'status' => '1',
		'name' => '动态表单隐藏条件符',
		'conftype' => '0',
		'level' => '15',
		'misdrules' => array(
			'1' => '==',
			'2' => '!=',
			'3' => '&gt;',
			'4' => '&gt;=',
			'5' => '&lt;',
			'6' => '&lt;=',
		),
	),
	'menu0021' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND落实情况',
		'conftype' => '0',
		'level' => '15',
		'menu0021' => array(
			'已落实' => '已落实',
			'已签订合同' => '已签订合同',
			'洽谈中' => '洽谈中',
		),
	),
	'menu00019' => array(
		'remark' => '逾期',
		'status' => '1',
		'name' => 'ND信用状况',
		'conftype' => '0',
		'level' => '15',
		'menu00019' => array(
			'逾期' => '逾期',
			'不良' => '不良',
		),
	),
	'menu00020' => array(
		'remark' => '有效',
		'status' => '1',
		'name' => 'ND状态',
		'conftype' => '0',
		'level' => '15',
		'menu00020' => array(
			'有效' => '有效',
			'无效' => '无效',
		),
	),
	'ListYesOrNo' => array(
		'remark' => '是否列表',
		'status' => '1',
		'name' => '是否列表',
		'conftype' => '0',
		'level' => '15',
		'ListYesOrNo' => array(
			'0' => '单数据',
			'1' => '多数据',
		),
	),
	'pingshenfangshi' => array(
		'remark' => '评审方式',
		'status' => '1',
		'name' => '评审方式',
		'conftype' => '0',
		'level' => '15',
		'pingshenfangshi' => array(
			'1' => '集中评审',
			'2' => '传签评审',
		),
	),
	'YesOrNoAgree' => array(
		'remark' => '是否同意',
		'status' => '1',
		'name' => '是否同意',
		'conftype' => '0',
		'level' => '15',
		'YesOrNoAgree' => array(
			'1' => '同意',
			'2' => '不同意',
		),
	),
	'AppraisalOpinion' => array(
		'remark' => '评审意见',
		'status' => '1',
		'name' => '专家评审意见',
		'conftype' => '0',
		'level' => '15',
		'AppraisalOpinion' => array(
			'1' => '同意',
			'2' => '不同意',
			'3' => '下次复议',
		),
	),
	'YesOrNoFinish' => array(
		'remark' => '完成情况',
		'status' => '1',
		'name' => '完成情况',
		'conftype' => '0',
		'level' => '15',
		'YesOrNoFinish' => array(
			'1' => '进行中',
			'2' => '已完成',
			'3' => '已终止',
		),
	),
	'menu00022' => array(
		'remark' => '应收',
		'status' => '1',
		'name' => 'ND保证金类型',
		'conftype' => '0',
		'level' => '15',
		'menu00022' => array(
			'应收' => '应收',
			'应付' => '应付',
		),
	),
	'menu00023' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND当前情况',
		'conftype' => '0',
		'level' => '15',
		'menu00023' => array(
			'学龄前儿童' => '学龄前儿童',
			'读书' => '读书',
			'就业' => '就业',
			'待业' => '待业',
		),
	),
	'ND01001' => array(
		'remark' => '胜诉或败诉',
		'status' => '1',
		'name' => '胜诉或败诉',
		'conftype' => '0',
		'level' => '15',
		'ND01001' => array(
			'胜诉' => '胜诉',
			'败诉' => '败诉',
		),
	),
	'menu0103' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND出入库类型',
		'conftype' => '0',
		'level' => '15',
		'menu0103' => array(
			'入库' => '入库',
			'出库' => '出库',
		),
	),
	'menu00101' => array(
		'remark' => 'ND放款次数',
		'status' => '1',
		'name' => 'ND放款次数',
		'conftype' => '0',
		'level' => '15',
		'menu00101' => array(
			'第一笔' => '第一笔',
			'第二笔' => '第二笔',
			'第三笔' => '第三笔',
			'第四笔' => '第四笔',
			'第五笔' => '第五笔',
			'一次性' => '一次性',
		),
	),
	'StartOrForbidden' => array(
		'remark' => '',
		'status' => '1',
		'name' => '启用禁用',
		'conftype' => '0',
		'level' => '15',
		'StartOrForbidden' => array(
			'1' => '启用',
			'0' => '禁用',
		),
	),
	'AutotypEnum' => array(
		'remark' => '',
		'status' => '1',
		'name' => '表单类型',
		'conftype' => '0',
		'level' => '15',
		'AutotypEnum' => array(
			'1' => '基础档案',
			'2' => '普通表单',
			'3' => '组合表单',
			'4' => '主从表单',
		),
	),
	'targettype' => array(
		'remark' => '',
		'status' => '1',
		'name' => '目标动作',
		'conftype' => '0',
		'level' => '15',
		'targettype' => array(
			'1' => '新增',
			'2' => '修改',
			'3' => '删除',
			'4' => '生成表单',
		),
	),
	'sourcetype' => array(
		'remark' => '',
		'status' => '1',
		'name' => '来源动作',
		'conftype' => '0',
		'level' => '15',
		'sourcetype' => array(
			'1' => '新增',
			'2' => '修改',
			'3' => '删除',
			'4' => '生成表单',
		),
	),
	'YesOrNoPass' => array(
		'remark' => '',
		'status' => '1',
		'name' => '是否通过',
		'conftype' => '0',
		'level' => '15',
		'YesOrNoPass' => array(
			'未通过' => '未通过',
			'通过' => '通过',
		),
	),
	'operateidVal' => array(
		'remark' => '普通单据',
		'status' => '1',
		'name' => '普通单据',
		'conftype' => '0',
		'level' => '15',
		'operateidVal' => array(
			'0' => '未确认提交',
			'1' => '确认提交',
		),
	),
	'ME10013' => array(
		'remark' => '办理实效',
		'status' => '1',
		'name' => '办理实效',
		'conftype' => '0',
		'level' => '15',
		'ME10013' => array(
			'放款前完善' => '放款前完善',
			'延期办理' => '延期办理',
		),
	),
	'ND83883' => array(
		'remark' => '承诺种类',
		'status' => '1',
		'name' => '承诺种类',
		'conftype' => '0',
		'level' => '15',
		'ND83883' => array(
			'签订合同' => '签订合同',
			'承诺书' => '承诺书',
		),
	),
	'ND00332' => array(
		'remark' => '价值评估方式',
		'status' => '1',
		'name' => 'ND价值评估方式',
		'conftype' => '0',
		'level' => '15',
		'ND00332' => array(
			'直接评估' => '直接评估',
			'购买\\账面值' => '购买\\账面值',
			'评估公司评估' => '评估公司评估',
		),
	),
	'ND00225' => array(
		'remark' => '龙头企业',
		'status' => '1',
		'name' => 'ND龙头企业',
		'conftype' => '0',
		'level' => '15',
		'ND00225' => array(
			'否' => '否',
			'县级' => '县级',
			'市级' => '市级',
		),
	),
	'ND00226' => array(
		'remark' => '示范社',
		'status' => '1',
		'name' => 'ND示范社',
		'conftype' => '0',
		'level' => '15',
		'ND00226' => array(
			'县级' => '县级',
			'市级' => '市级',
		),
	),
	'auditStateVal' => array(
		'remark' => '',
		'status' => '1',
		'name' => '审核状态',
		'conftype' => '0',
		'level' => '15',
		'auditStateVal' => array(
			'0' => '新增',
			'1' => '启动',
			'2' => '审核中',
			'3' => '审核完毕',
			'-1' => '打回',
			'4' => '变更',
		),
	),
	'ND0113' => array(
		'remark' => '健康状况',
		'status' => '1',
		'name' => 'ND健康状况',
		'conftype' => '0',
		'level' => '15',
		'ND0113' => array(
			'健康' => '健康',
			'疾病' => '疾病',
		),
	),
	'neibupingshenyijian' => array(
		'remark' => '内部评审意见',
		'status' => '1',
		'name' => '内部评审意见-old',
		'conftype' => '0',
		'level' => '15',
		'neibupingshenyijian' => array(
			'1' => '同意',
			'2' => '不同意',
		),
	),
	'CommunicationType' => array(
		'remark' => '',
		'status' => '1',
		'name' => '沟通方式',
		'conftype' => '0',
		'level' => '15',
		'CommunicationType' => array(
			'1' => '电话',
			'2' => '现场',
		),
	),
	'NDGrouptype' => array(
		'remark' => '项目组类别',
		'status' => '1',
		'name' => '项目组类别',
		'conftype' => '0',
		'level' => '15',
		'NDGrouptype' => array(
			'组' => '组',
			'角色' => '角色',
		),
	),
	'ND0010393' => array(
		'remark' => '项目人员属性',
		'status' => '1',
		'name' => '项目人员属性',
		'conftype' => '0',
		'level' => '15',
		'ND0010393' => array(
			'分派人' => '分派人',
			'执行人' => '执行人',
		),
	),
	'ND00341' => array(
		'remark' => '存栏量类型',
		'status' => '1',
		'name' => '存栏量类型',
		'conftype' => '0',
		'level' => '15',
		'ND00341' => array(
			'当期数量（只、头、羽）' => '当期数量（只、头、羽）',
			'去年同期数量（只、头、羽）' => '去年同期数量（只、头、羽）',
		),
	),
	'NDZLLX01' => array(
		'remark' => '资料类型',
		'status' => '1',
		'name' => 'ND资料类型',
		'conftype' => '0',
		'level' => '15',
		'NDZLLX01' => array(
			'模板' => '模板',
			'业务' => '业务',
		),
	),
	'sys0011' => array(
		'remark' => '是否拷贝',
		'status' => '1',
		'name' => '是否拷贝',
		'conftype' => '0',
		'level' => '15',
		'sys0011' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'ND00450' => array(
		'remark' => '月份',
		'status' => '1',
		'name' => '月份',
		'conftype' => '0',
		'level' => '15',
		'ND00450' => array(
			'1' => '1',
			'2' => '2',
			'3' => '3',
			'4' => '4',
			'5' => '5',
			'6' => '6',
			'7' => '7',
			'8' => '8',
			'9' => '9',
			'10' => '10',
			'11' => '11',
			'12' => '12',
		),
	),
	'PublishOrRecover' => array(
		'remark' => '',
		'status' => '1',
		'name' => '发布或收回',
		'conftype' => '0',
		'level' => '15',
		'PublishOrRecover' => array(
			'1' => '发布',
			'2' => '收回',
		),
	),
	'ExecutiveCondition' => array(
		'remark' => '',
		'status' => '1',
		'name' => '执行情况',
		'conftype' => '0',
		'level' => '15',
		'ExecutiveCondition' => array(
			'1' => '未领取',
			'2' => '已领取',
			'3' => '已验收',
			'4' => '已提交',
			'5' => '已退回',
		),
	),
	'ND00288' => array(
		'remark' => '亲属关系',
		'status' => '1',
		'name' => '亲属关系',
		'conftype' => '0',
		'level' => '15',
		'ND00288' => array(
			'父母' => '父母',
			'配偶' => '配偶',
			'子女' => '子女',
		),
	),
	'ND00249' => array(
		'remark' => '抵押物价值确认方法',
		'status' => '1',
		'name' => '抵押物价值确认方法',
		'conftype' => '0',
		'level' => '15',
		'ND00249' => array(
			'（一）' => '（一）',
			'（二）' => '（二）',
		),
	),
	'ND00239' => array(
		'remark' => '项',
		'status' => '1',
		'name' => '项',
		'conftype' => '0',
		'level' => '15',
		'ND00239' => array(
			'（1）' => '（1）',
			'（2）' => '（2）',
		),
	),
	'ExpertOrInsider' => array(
		'remark' => '',
		'status' => '1',
		'name' => '外部专家或内部人员',
		'conftype' => '0',
		'level' => '15',
		'ExpertOrInsider' => array(
			'1' => '内部人员',
			'2' => '外部专家',
		),
	),
	'ND00219' => array(
		'remark' => '支付方式',
		'status' => '1',
		'name' => '支付方式',
		'conftype' => '0',
		'level' => '15',
		'ND00219' => array(
			'（1）' => '转账支付',
			'（2）' => '现金支付',
		),
	),
	'ND00321' => array(
		'remark' => '是否配合',
		'status' => '1',
		'name' => '是否配合',
		'conftype' => '0',
		'level' => '15',
		'ND00321' => array(
			'配合' => '配合',
			'不配合' => '不配合',
		),
	),
	'ND00350' => array(
		'remark' => '资料性质',
		'status' => '1',
		'name' => '资料性质',
		'conftype' => '0',
		'level' => '15',
		'ND00350' => array(
			'业务' => '业务',
			'综合' => '综合',
		),
	),
	'ND00400' => array(
		'remark' => '保管期限',
		'status' => '1',
		'name' => '保管期限',
		'conftype' => '0',
		'level' => '15',
		'ND00400' => array(
			'长期' => '长期',
			'短期' => '短期',
		),
	),
	'ND00318' => array(
		'remark' => '是否合格',
		'status' => '1',
		'name' => '是否合格',
		'conftype' => '0',
		'level' => '15',
		'ND00318' => array(
			'合格' => '合格',
			'不合格' => '不合格',
		),
	),
	'ND00349' => array(
		'remark' => '报销方式',
		'status' => '1',
		'name' => '报销方式',
		'conftype' => '0',
		'level' => '15',
		'ND00349' => array(
			'1' => '现金',
			'2' => '支票',
			'3' => '汇票',
			'4' => '冲销借款',
			'5' => '其它',
		),
	),
	'ND00361' => array(
		'remark' => '报销类型',
		'status' => '1',
		'name' => '报销类型',
		'conftype' => '0',
		'level' => '15',
		'ND00361' => array(
			'1' => '个人',
			'2' => '部门',
			'3' => '分部',
		),
	),
	'ND00378' => array(
		'remark' => '紧急程度',
		'status' => '1',
		'name' => '紧急程度',
		'conftype' => '0',
		'level' => '15',
		'ND00378' => array(
			'2' => '紧急',
			'1' => '特急',
			'3' => '一般',
		),
	),
	'ND00359' => array(
		'remark' => '秘密等级',
		'status' => '1',
		'name' => '秘密等级',
		'conftype' => '0',
		'level' => '15',
		'ND00359' => array(
			'2' => '机密',
			'1' => '绝密',
			'3' => '秘密',
			'21' => '普通',
		),
	),
	'ND00374' => array(
		'remark' => '合同资料',
		'status' => '1',
		'name' => '合同资料',
		'conftype' => '0',
		'level' => '15',
		'ND00374' => array(
			'1' => '合同文稿',
			'2' => '其它',
		),
	),
	'delayStatus' => array(
		'remark' => '',
		'status' => '1',
		'name' => '延期状态',
		'conftype' => '0',
		'level' => '15',
		'delayStatus' => array(
			'0' => '未延期',
			'1' => '已延期',
		),
	),
	'ND00377' => array(
		'remark' => '保证金来源',
		'status' => '1',
		'name' => '保证金来源',
		'conftype' => '0',
		'level' => '15',
		'ND00377' => array(
			'冲销' => '冲销',
			'存入' => '存入',
		),
	),
	'ND00398' => array(
		'remark' => '收取方式',
		'status' => '1',
		'name' => '收取方式',
		'conftype' => '0',
		'level' => '15',
		'ND00398' => array(
			'冲销' => '冲销',
			'收取' => '收取',
		),
	),
	'enum006' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND是否',
		'conftype' => '0',
		'level' => '15',
		'enum006' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'CYLB01' => array(
		'remark' => '联络站成员类别',
		'status' => '1',
		'name' => '联络站成员类别',
		'conftype' => '0',
		'level' => '15',
		'CYLB01' => array(
			'站长' => '站长',
			'成员' => '成员',
		),
	),
	'cwgwxywtsx' => array(
		'remark' => '',
		'status' => '1',
		'name' => '财务顾问协议委托事项',
		'conftype' => '0',
		'level' => '15',
		'cwgwxywtsx' => array(
			'1' => '（一）',
			'2' => '（二）',
			'3' => '（三）',
			'4' => '（四）',
			'5' => '（五）',
		),
	),
	'NDzj01' => array(
		'remark' => 'ND增减方向',
		'status' => '1',
		'name' => 'ND增减方向',
		'conftype' => '0',
		'level' => '15',
		'NDzj01' => array(
			'增' => '增',
			'减' => '减',
		),
	),
	'NDSF' => array(
		'remark' => '先是再否',
		'status' => '1',
		'name' => 'ND是否',
		'conftype' => '0',
		'level' => '15',
		'NDSF' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'FundsNeedTime' => array(
		'remark' => '',
		'status' => '1',
		'name' => '资金需求时间',
		'conftype' => '0',
		'level' => '15',
		'FundsNeedTime' => array(
			'无需求' => '无需求',
			'1月' => '1月',
			'2月' => '2月',
			'3月' => '3月',
			'4月' => '4月',
			'5月' => '5月',
			'6月' => '6月',
			'7月' => '7月',
			'8月' => '8月',
			'9月' => '9月',
			'10月' => '10月',
			'11月' => '11月',
			'12月' => '12月',
		),
	),
	'chanpinxiaoshoufangshi' => array(
		'remark' => '',
		'status' => '1',
		'name' => '产品销售方式',
		'conftype' => '0',
		'level' => '15',
		'chanpinxiaoshoufangshi' => array(
			'批发' => '批发',
			'零售' => '零售',
		),
	),
	'romaoperate' => array(
		'remark' => '数据漫游字段比较操作方式',
		'status' => '1',
		'name' => '数据漫游字段比较操作方式',
		'conftype' => '0',
		'level' => '15',
		'romaoperate' => array(
			'1' => '选择字段',
			'2' => '设置定值',
		),
	),
	'UserOrInterfaceLocation' => array(
		'remark' => '',
		'status' => '1',
		'name' => '用户与联络站',
		'conftype' => '0',
		'level' => '15',
		'UserOrInterfaceLocation' => array(
			'1' => '公司员工',
			'2' => '金融联络站',
		),
	),
	'NDsfjy' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND启用禁用',
		'conftype' => '0',
		'level' => '15',
		'NDsfjy' => array(
			'1' => '启用',
			'0' => '禁用',
		),
	),
	'ndzsfw01' => array(
		'remark' => '用于流程审批节点转授',
		'status' => '1',
		'name' => '转授范围',
		'conftype' => '0',
		'level' => '15',
		'ndzsfw01' => array(
			'部分' => '部分',
			'全部' => '全部',
		),
	),
	'pxlx01' => array(
		'remark' => '内训，外训',
		'status' => '1',
		'name' => '培训类型',
		'conftype' => '0',
		'level' => '15',
		'pxlx01' => array(
			'内训' => '内训',
			'外训' => '外训',
		),
	),
	'pxpj01' => array(
		'remark' => '对培训结果评价：差、一般、好、很好',
		'status' => '1',
		'name' => '培训评价',
		'conftype' => '0',
		'level' => '15',
		'pxpj01' => array(
			'差' => '差',
			'一般' => '一般',
			'好' => '好',
			'很好' => '很好',
		),
	),
	'gqynpxgj' => array(
		'remark' => '1、    您认为，过去一年内举办的培训课程哪些地方有待改进',
		'status' => '1',
		'name' => '培训课程哪些地方有待改进',
		'conftype' => '0',
		'level' => '15',
		'gqynpxgj' => array(
			'1' => '培训内容理论程度应深化',
			'2' => '培训内容实用程度应加强',
			'3' => '提高讲师水平',
			'4' => '培训组织服务更完善',
			'5' => '培训形式应多样化',
			'6' => '培训次数太少，可适当增加',
			'7' => '培训应少而精',
			'8' => '培训时间安排更合理',
			'9' => '其他',
		),
	),
	'xznzlxdjs' => array(
		'remark' => '公司在安排培训时，您倾向于选择哪种类型的讲师',
		'status' => '1',
		'name' => '您倾向于选择哪种类型的讲师',
		'conftype' => '0',
		'level' => '15',
		'xznzlxdjs' => array(
			'1' => '实战派知名企业专家，有标杆企业经验',
			'2' => '学院派知名教授学者，理论功底深厚，知识渊博',
			'3' => '职业培训师，丰富的授课技巧和经验',
			'4' => '咨询公司高级顾问，丰富的项目经验',
			'5' => '本职位优秀员工，对公司业务很了解',
			'6' => '其他',
		),
	),
	'btjdrmymkcdnbjs' => array(
		'remark' => '假如，鉴于您在某一领域的丰富经验，您被推荐担任某一门课程的内部讲师，您是否乐意',
		'status' => '1',
		'name' => '您被推荐担任某一门课程的内部讲师，您是否乐意',
		'conftype' => '0',
		'level' => '15',
		'btjdrmymkcdnbjs' => array(
			'1' => '非常乐意，既可以锻炼自己，又可以分享知识，何乐而不为',
			'2' => '乐意，但是没有经验，希望公司能提供关于讲授技巧方面的培训',
			'3' => '乐意，但是没有时间做这个事情',
			'4' => '需要考虑一下',
			'5' => '不会担任',
		),
	),
	'dcdkcsjnbjjs' => array(
		'remark' => '您认为，对于某一次课程来讲，多长的时间您比较能接受',
		'status' => '1',
		'name' => '多长的课程时间您比较能接受',
		'conftype' => '0',
		'level' => '15',
		'dcdkcsjnbjjs' => array(
			'1' => '2-3小时',
			'2' => '7小时（1天）',
			'3' => '14小时（2天）',
			'4' => '14小时以上',
			'5' => '无所谓，看课程需要来定',
			'6' => '其他',
		),
	),
	'pxsjapzsmshbjhs' => array(
		'remark' => '您认为培训时间安排在什么时候比较合适',
		'status' => '1',
		'name' => '培训时间安排在什么时候比较合适',
		'conftype' => '0',
		'level' => '15',
		'pxsjapzsmshbjhs' => array(
			'1' => '上班期间，如周五下午2-3小时',
			'2' => '工作日下班后2-3小时',
			'3' => '周末1天',
			'4' => '双休日2天',
			'5' => '无所谓，看课程需要来定',
			'6' => '其他',
		),
	),
	'snjsdpxdpl' => array(
		'remark' => '您希望的或者所能接受的培训的频率是怎样的',
		'status' => '1',
		'name' => '所能接受的培训的频率',
		'conftype' => '0',
		'level' => '15',
		'snjsdpxdpl' => array(
			'1' => '每周一次',
			'2' => '半月一次',
			'3' => '每月一次',
			'4' => '两月一次',
			'5' => '每季度一次',
			'6' => '半年一次',
			'7' => '每年一次',
			'8' => '其他',
		),
	),
	'tyjnkc' => array(
		'remark' => '您认为，以下哪些通用技能课程能帮助本部门员工提升工作绩效（可多选）',
		'status' => '1',
		'name' => '通用技能课程',
		'conftype' => '0',
		'level' => '15',
		'tyjnkc' => array(
			'1' => '《人际关系处理技巧》',
			'2' => '《公司产品及市场》',
			'3' => '《商务礼仪》',
			'4' => '《压力与情绪管理》',
			'5' => '《沟通技巧》',
			'6' => '《时间管理》',
			'7' => '《积极心态》',
			'8' => '《商务英语口语与写作》',
		),
	),
	'xsjnkc' => array(
		'remark' => '如果您所带领的是销售团队，您认为以下哪些销售技能课程能帮助部门员工提升工作绩效（请选出最紧迫的四个需求）',
		'status' => '1',
		'name' => '销售技能课程',
		'conftype' => '0',
		'level' => '15',
		'xsjnkc' => array(
			'1' => '《电话营销技巧》',
			'2' => '《人际关系行销》',
			'3' => '《优质客户服务》',
			'4' => '《产品呈现技巧》',
			'5' => '《销售谈判技巧》',
			'6' => '《销售心理学》',
			'7' => '《主动行销》',
			'8' => '《销售策略分析》',
			'9' => '《市场调研分析》',
			'10' => '《如何撰写销售报告》',
			'11' => '《成本控制》',
			'12' => '《销售技巧提升》',
			'13' => '《销售财务管理》',
			'14' => '《客户管理》',
			'15' => '《销售预测》',
			'16' => '《增值型销售技巧》',
		),
	),
	'gljnpx' => array(
		'remark' => '以下管理技能培训，请选择您所需要的最紧迫的四个培训需求',
		'status' => '1',
		'name' => '管理技能培训',
		'conftype' => '0',
		'level' => '15',
		'gljnpx' => array(
			'1' => '《项目管理》',
			'2' => '《目标管理》',
			'3' => '《危机管理》',
			'4' => '《问题分析与解决》',
			'5' => '《创新思维》',
			'6' => '《普通心理学》',
			'7' => '《组织行为学》',
			'8' => '《提升执行力》',
			'9' => '《提升领导力》',
			'10' => '《高层战略管理》',
			'11' => '《跨部门沟通与合作》',
			'12' => '《高绩效团队建设》',
			'13' => '《决策管理》',
			'14' => '《员工辅导与激励》',
			'15' => '《高效会议管理技巧》',
			'16' => '《劳动法及相关知识》',
			'17' => '《年度经营计划制订》',
			'18' => '《从优秀专才走向管理者》',
			'19' => '《授权管理》',
			'20' => '《商务演讲技巧》',
			'21' => '《营销战略规划与执行》',
			'22' => '《非财务经理的财务管理》',
			'23' => '《非人力资源经理的人力资源管理》',
		),
	),
	'cwgljbsglcsjkc' => array(
		'remark' => '以下财务管理、兼并收购、流程审计课程，如与您工作相关，请选择您认为最紧迫的三个培训需求',
		'status' => '1',
		'name' => '财务管理、兼并收购、流程审计课程',
		'conftype' => '0',
		'level' => '15',
		'cwgljbsglcsjkc' => array(
			'1' => '《财务报表的编制》',
			'2' => '《财务报表分析》',
			'3' => '《成本分析与成本管理》',
			'4' => '《全面预算管理与控制》',
			'5' => '《税法与税务筹划》',
			'6' => '《财务诊断及预警机制》',
			'7' => '《国际规范预算管理》',
			'8' => '《逾期账款管理实务》',
			'9' => '《项目投资分析与决策》',
			'10' => '《收购兼并实务》',
			'11' => '《内部审计与风险控制》',
			'12' => '《专项审计开展要点》',
		),
	),
	'jfly' => array(
		'remark' => '经费来源',
		'status' => '1',
		'name' => '经费来源',
		'conftype' => '0',
		'level' => '15',
		'jfly' => array(
			'1' => '公费',
			'2' => '自费',
			'3' => '双方承担',
		),
	),
	'syx' => array(
		'remark' => '适用性',
		'status' => '1',
		'name' => '适用性',
		'conftype' => '0',
		'level' => '15',
		'syx' => array(
			'1' => '很不适用',
			'2' => '不适用',
			'3' => '一般',
			'4' => '适用',
			'5' => '很适用',
		),
	),
	'skdzsjz' => array(
		'remark' => '授课知识的价值',
		'status' => '1',
		'name' => '授课知识的价值',
		'conftype' => '0',
		'level' => '15',
		'skdzsjz' => array(
			'1' => '很低',
			'2' => '低',
			'3' => '普通',
			'4' => '高',
			'5' => '很高',
		),
	),
	'sfhs' => array(
		'remark' => '是否合适',
		'status' => '1',
		'name' => '是否合适',
		'conftype' => '0',
		'level' => '15',
		'sfhs' => array(
			'1' => '很不合适',
			'2' => '不合适',
			'3' => '一般',
			'4' => '合适',
			'5' => '很合适',
		),
	),
	'ztpj' => array(
		'remark' => '整体评价',
		'status' => '1',
		'name' => '整体评价',
		'conftype' => '0',
		'level' => '15',
		'ztpj' => array(
			'1' => '很差',
			'2' => '差',
			'3' => '一般',
			'4' => '好',
			'5' => '很好',
		),
	),
	'zyxdpxff' => array(
		'remark' => '您认为最有效的培训方法是什么? 请选出您认为最有效的2—3种',
		'status' => '1',
		'name' => '最有效的培训方法',
		'conftype' => '0',
		'level' => '15',
		'zyxdpxff' => array(
			'1' => '讲授法',
			'2' => '案例分析',
			'3' => '游戏',
			'4' => '情境模拟',
			'5' => '课堂讨论',
			'6' => '观看多媒体资料',
			'7' => '互动练习',
			'8' => '其它方式(请说明)',
		),
	),
	'pxjsxyznxdfzdgh' => array(
		'remark' => '您希望培训讲师以后需要在哪些方面做得更好',
		'status' => '1',
		'name' => '培训讲师需要在哪些方面做得更好',
		'conftype' => '0',
		'level' => '15',
		'pxjsxyznxdfzdgh' => array(
			'1' => '准备更充分',
			'2' => '内容能理论与实际相结合',
			'3' => '生动有趣，通俗易懂',
			'4' => '增强学员参与性',
			'5' => '引导学员思考',
			'6' => '内容与工作联系紧密',
			'7' => '其它地方（请说明）',
		),
	),
	'gwxqly' => array(
		'remark' => '岗位需求理由',
		'status' => '1',
		'name' => '岗位需求理由',
		'conftype' => '0',
		'level' => '15',
		'gwxqly' => array(
			'1' => '缺员补充',
			'2' => '扩大编制',
			'3' => '储备人力',
			'4' => '其他需要',
		),
	),
	'NDxl' => array(
		'remark' => '学历',
		'status' => '1',
		'name' => '学历',
		'conftype' => '0',
		'level' => '15',
		'NDxl' => array(
			'小学' => '小学',
			'初中' => '初中',
			'中专' => '中专',
			'高中' => '高中',
			'专科' => '专科',
			'本科' => '本科',
			'硕士' => '硕士',
			'博士' => '博士',
		),
	),
	'NDsex' => array(
		'remark' => '性别',
		'status' => '1',
		'name' => '性别',
		'conftype' => '0',
		'level' => '15',
		'NDsex' => array(
			'1' => '男',
			'2' => '女',
		),
	),
	'yryb' => array(
		'remark' => '仪容仪表',
		'status' => '1',
		'name' => '仪容仪表',
		'conftype' => '0',
		'level' => '15',
		'yryb' => array(
			'1' => '穿着整齐、得体，稳重、大方，走路、敲门、坐姿符合礼节，口语文雅、礼貌',
			'2' => '一般',
			'3' => '较差',
		),
	),
	'xxqz' => array(
		'remark' => '形象气质',
		'status' => '1',
		'name' => '形象气质',
		'conftype' => '0',
		'level' => '15',
		'xxqz' => array(
			'1' => '形象气质俱佳',
			'2' => '形象气质一般',
			'3' => '较差',
		),
	),
	'csjg' => array(
		'remark' => '初试结果',
		'status' => '1',
		'name' => '初试结果',
		'conftype' => '0',
		'level' => '15',
		'csjg' => array(
			'1' => '通过初试，建议进入笔试',
			'2' => '初试不合格',
		),
	),
	'xlfhqk' => array(
		'remark' => '学历符合情况',
		'status' => '1',
		'name' => '学历符合情况',
		'conftype' => '0',
		'level' => '15',
		'xlfhqk' => array(
			'1' => '符合公司岗位要求',
			'2' => '不符合公司岗位要求',
		),
	),
	'NDsyzk' => array(
		'remark' => '生育状况',
		'status' => '1',
		'name' => '生育状况',
		'conftype' => '0',
		'level' => '15',
		'NDsyzk' => array(
			'1' => '已育',
			'2' => '未育',
		),
	),
	'luichenganyu' => array(
		'remark' => '',
		'status' => '1',
		'name' => '流程干预类型',
		'conftype' => '0',
		'level' => '15',
		'luichenganyu' => array(
			'退回' => '退回',
			'跨级' => '跨级',
			'审核人' => '审核人',
		),
	),
	'jbclyj' => array(
		'remark' => '部门负责人对加班处理意见',
		'status' => '1',
		'name' => '部门负责人对加班处理意见',
		'conftype' => '0',
		'level' => '15',
		'jbclyj' => array(
			'调休' => '调休',
			'发放加班工资' => '发放加班工资',
			'因个人工作失误或延迟造成的加班，不发放加班工资或调休' => '因个人工作失误或延迟造成的加班，不发放加班工资或调休',
		),
	),
	'sys01' => array(
		'remark' => '系统开发分类',
		'status' => '1',
		'name' => '系统开发分类',
		'conftype' => '0',
		'level' => '15',
		'sys01' => array(
			'存储过程' => '存储过程',
			'视图' => '视图',
			'函数' => '函数',
		),
	),
	'CCLB' => array(
		'remark' => '',
		'status' => '1',
		'name' => '出差类别',
		'conftype' => '0',
		'level' => '15',
		'CCLB' => array(
			'1' => '工作',
			'2' => '培训',
			'3' => '考察',
		),
	),
	'NDtzlx' => array(
		'remark' => '调整类型',
		'status' => '1',
		'name' => '调整类型',
		'conftype' => '0',
		'level' => '15',
		'NDtzlx' => array(
			'1' => '入职调整',
			'2' => '变更调整',
		),
	),
	'zpxp' => array(
		'remark' => 'nd招聘性别',
		'status' => '1',
		'name' => 'nd招聘性别',
		'conftype' => '0',
		'level' => '15',
		'zpxp' => array(
			'男' => '男',
			'女' => '女',
			'不限' => '不限',
		),
	),
	'jclb' => array(
		'remark' => '奖惩对象',
		'status' => '1',
		'name' => '奖惩对象',
		'conftype' => '0',
		'level' => '15',
		'jclb' => array(
			'员工' => '员工',
			'部门' => '部门',
		),
	),
	'season' => array(
		'remark' => '',
		'status' => '1',
		'name' => '季度',
		'conftype' => '0',
		'level' => '15',
		'season' => array(
			'第一季度' => '第一季度',
			'第二季度' => '第二季度',
			'第三季度' => '第三季度',
			'第四季度' => '第四季度',
		),
	),
	'ryzwlb' => array(
		'remark' => '人员职务类别',
		'status' => '1',
		'name' => '人员职务类别',
		'conftype' => '0',
		'level' => '15',
		'ryzwlb' => array(
			'员工' => '员工',
			'领导' => '领导',
		),
	),
	'SBZLZXBZ' => array(
		'remark' => '',
		'status' => '1',
		'name' => '设备质量执行标准',
		'conftype' => '0',
		'level' => '15',
		'SBZLZXBZ' => array(
			'⑴' => '⑴',
			'⑵' => '⑵',
			'⑶' => '⑶',
		),
	),
	'aqdengj' => array(
		'remark' => '安全等级',
		'status' => '1',
		'name' => '安全等级',
		'conftype' => '0',
		'level' => '15',
		'aqdengj' => array(
			'1' => '1',
			'2' => '49',
			'3' => '79',
			'4' => '100',
		),
	),
	'CTJJFL' => array(
		'remark' => '',
		'status' => '1',
		'name' => '创投基金分类',
		'conftype' => '0',
		'level' => '15',
		'CTJJFL' => array(
			'直投' => '直投',
			'跟贷' => '跟贷',
		),
	),
	'WBHTLX' => array(
		'remark' => '',
		'status' => '1',
		'name' => '委保合同类型',
		'conftype' => '0',
		'level' => '15',
		'WBHTLX' => array(
			'普通' => '普通版本',
			'小微' => '含连带责任担保版本',
			'P2P' => 'P2P版本',
		),
	),
	'HZGX' => array(
		'remark' => '',
		'status' => '1',
		'name' => '合作关系',
		'conftype' => '0',
		'level' => '15',
		'HZGX' => array(
			'1' => '上游',
			'2' => '下游',
			'3' => '其他',
		),
	),
	'TJGX' => array(
		'remark' => '',
		'status' => '1',
		'name' => '推荐关系',
		'conftype' => '0',
		'level' => '15',
		'TJGX' => array(
			'1' => '推荐人',
			'2' => '被推荐人',
		),
	),
	'FSYJ' => array(
		'remark' => '',
		'status' => '1',
		'name' => '复试意见',
		'conftype' => '0',
		'level' => '15',
		'FSYJ' => array(
			'1' => '同意录用',
			'2' => '储备',
			'3' => '不同意录用',
		),
	),
	'P2PJKCP' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'P2P借款产品',
		'conftype' => '0',
		'level' => '15',
		'P2PJKCP' => array(
			'1' => '担保借款',
			'2' => '公益借款',
		),
	),
	'P2PDBFS' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'P2P担保方式',
		'conftype' => '0',
		'level' => '15',
		'P2PDBFS' => array(
			'1' => '本金担保',
			'2' => '本息担保',
		),
	),
	'P2PHKFS' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'P2P还款方式',
		'conftype' => '0',
		'level' => '15',
		'P2PHKFS' => array(
			'1' => '按月还款、等额本息',
			'2' => '每月付息、到期还本',
			'3' => '到期还本付息',
			'4' => '按季付息、到期还本',
			'5' => '按年付息、到期还本',
		),
	),
	'NBPSYJ' => array(
		'remark' => '',
		'status' => '1',
		'name' => '内部评审意见',
		'conftype' => '0',
		'level' => '15',
		'NBPSYJ' => array(
			'同意' => '同意',
			'有条件同意' => '有条件同意',
			'不同意' => '不同意',
			'下次复议' => '下次复议',
		),
	),
	'XMPSHZYJ' => array(
		'remark' => '',
		'status' => '1',
		'name' => '项目评审汇总意见',
		'conftype' => '0',
		'level' => '15',
		'XMPSHZYJ' => array(
			'1' => '同意',
			'2' => '不同意',
			'3' => '下次复议',
			'4' => '原则同意',
			'5' => '有条件同意',
		),
	),
	'FWLB' => array(
		'remark' => '',
		'status' => '1',
		'name' => '发文类别',
		'conftype' => '0',
		'level' => '15',
		'FWLB' => array(
			'公司发文' => '公司发文',
			'董办发文' => '董办发文',
		),
	),
	'HKQK' => array(
		'remark' => '',
		'status' => '1',
		'name' => '还款情况',
		'conftype' => '0',
		'level' => '15',
		'HKQK' => array(
			'正常还款' => '正常还款',
			'逾期还款' => '逾期还款',
			'代偿还款' => '代偿还款',
			'循环贷' => '循环贷',
			'冲贷还款' => '冲贷还款',
		),
	),
	'ZXCXYY' => array(
		'remark' => '',
		'status' => '1',
		'name' => '查询原因',
		'conftype' => '0',
		'level' => '15',
		'ZXCXYY' => array(
			'贷前' => '贷前',
			'贷后' => '贷后',
		),
	),
	'PFCBYY' => array(
		'remark' => '',
		'status' => '1',
		'name' => '批复储备原因',
		'conftype' => '0',
		'level' => '15',
		'PFCBYY' => array(
			'公司原因' => '公司原因',
			'客户原因' => '客户原因',
			'银行原因' => '银行原因',
		),
	),
	'KHLX' => array(
		'remark' => '',
		'status' => '1',
		'name' => '客户类型',
		'conftype' => '0',
		'level' => '15',
		'KHLX' => array(
			'新客户' => '新客户',
			'老客户' => '老客户',
		),
	),
	'CTXMJD' => array(
		'remark' => '',
		'status' => '1',
		'name' => '创投项目阶段',
		'conftype' => '0',
		'level' => '15',
		'CTXMJD' => array(
			'种子期' => '种子期',
			'初创期' => '初创期',
			'成长期' => '成长期',
		),
	),
	'NBLX' => array(
		'remark' => '',
		'status' => '1',
		'name' => '农本部门类型',
		'conftype' => '0',
		'level' => '15',
		'NBLX' => array(
			'农本综合部' => '农本综合部',
			'农哈哈项目部' => '农哈哈项目部',
			'渝哈哈项目部' => '渝哈哈项目部',
		),
	),
	'BHQK' => array(
		'remark' => '',
		'status' => '1',
		'name' => '变化情况',
		'conftype' => '0',
		'level' => '15',
		'BHQK' => array(
			'有变化' => '有变化',
			'无变化' => '无变化',
		),
	),
	'BHQK1' => array(
		'remark' => '',
		'status' => '1',
		'name' => '变化情况-1',
		'conftype' => '0',
		'level' => '15',
		'BHQK1' => array(
			'增加' => '增加',
			'维持' => '维持',
			'减少' => '减少',
		),
	),
	'HKLY' => array(
		'remark' => '',
		'status' => '1',
		'name' => '还款来源',
		'conftype' => '0',
		'level' => '15',
		'HKLY' => array(
			'自筹' => '自筹',
			'公司解决' => '公司解决',
		),
	),
	'JYFS' => array(
		'remark' => '',
		'status' => '1',
		'name' => '借阅方式',
		'conftype' => '0',
		'level' => '15',
		'JYFS' => array(
			'借阅' => '借阅',
			'借出' => '借出',
		),
	),
	'XCQRLB' => array(
		'remark' => '',
		'status' => '1',
		'name' => '薪酬确认类别',
		'conftype' => '0',
		'level' => '15',
		'XCQRLB' => array(
			'试用' => '试用',
			'转正' => '转正',
		),
	),
	'H001' => array(
		'remark' => '',
		'status' => '1',
		'name' => '土地来源-黑',
		'conftype' => '0',
		'level' => '15',
		'H001' => array(
			'自有' => '自有',
			'租赁' => '租赁',
			'带地入社' => '带地入社',
		),
	),
	'projectyj' => array(
		'remark' => '',
		'status' => '1',
		'name' => '项目方案意见',
		'conftype' => '0',
		'level' => '15',
		'projectyj' => array(
			'1' => '同意项目方案',
			'2' => '不同意项目方案',
			'3' => '有条件同意，提出建议',
		),
	),
	'HND0001' => array(
		'remark' => '法人、实际人 贷款情况',
		'status' => '1',
		'name' => '身份类别（法人、实际人）',
		'conftype' => '0',
		'level' => '15',
		'HND0001' => array(
			'法定代表人' => '法定代表人',
			'法定代表人配偶' => '法定代表人配偶',
			'实际控制人' => '实际控制人',
			'实际控制人配偶' => '实际控制人配偶',
			'股东贷款情况（占股比例高）' => '股东贷款情况（占股比例高）',
			'本单位' => '本单位',
			'关联方' => '关联方',
			'理事长及主要成员' => '理事长及主要成员',
		),
	),
	'HND0002' => array(
		'remark' => '合作社资产类别 尽调  资产情况',
		'status' => '1',
		'name' => '合作社资产类别',
		'conftype' => '0',
		'level' => '15',
		'HND0002' => array(
			'存货' => '存货',
			'农机具' => '农机具',
			'场库棚建设面积' => '场库棚建设面积',
			'车辆' => '车辆',
			'其他' => '其他',
		),
	),
	'HND0003' => array(
		'remark' => '合作社主要交易对手情况',
		'status' => '1',
		'name' => '合作社主要交易对手情况',
		'conftype' => '0',
		'level' => '15',
		'HND0003' => array(
			'最大' => '最大',
			'次大' => '次大',
			'第三大' => '第三大',
			'第四大' => '第四大',
			'第五大' => '第五大',
		),
	),
	'HND0004' => array(
		'remark' => '合作社交易类别',
		'status' => '1',
		'name' => '合作社交易类别',
		'conftype' => '0',
		'level' => '15',
		'HND0004' => array(
			'供应商' => '供应商',
			'客户' => '客户',
		),
	),
	'dedbqk' => array(
		'remark' => '',
		'status' => '1',
		'name' => '对外担保情况类型',
		'conftype' => '0',
		'level' => '15',
		'dedbqk' => array(
			'0' => '法定代表人',
			'1' => '法定代表人配偶',
			'2' => '实际控制人',
			'3' => '实际控制人配偶',
			'4' => '股东',
			'5' => '企业',
			'6' => '关联方',
		),
	),
	'proje68' => array(
		'remark' => '',
		'status' => '1',
		'name' => '生成成本项目类型',
		'conftype' => '0',
		'level' => '15',
		'proje68' => array(
			'0' => '原材料',
			'1' => '机械制造',
			'2' => '水电费',
			'3' => '人工费',
			'4' => '折旧',
			'5' => '包装物',
			'6' => '运输费',
			'7' => '其他',
		),
	),
	'dklxwh' => array(
		'remark' => '',
		'status' => '1',
		'name' => '贷款时间',
		'conftype' => '0',
		'level' => '15',
		'dklxwh' => array(
			'0' => '季节性使用',
			'1' => '临时性使用',
			'2' => '长期占用',
		),
	),
	'bzlxj' => array(
		'remark' => '',
		'status' => '1',
		'name' => '保证类型',
		'conftype' => '0',
		'level' => '15',
		'bzlxj' => array(
			'1' => '一般保证',
			'0' => '连带责任保证',
		),
	),
	'rongzzl' => array(
		'remark' => '',
		'status' => '1',
		'name' => '融资种类',
		'conftype' => '0',
		'level' => '15',
		'rongzzl' => array(
			'0' => '流动资金借款',
			'1' => '固定资产借款',
		),
	),
	'HND0006' => array(
		'remark' => '指标方向 基础指标库',
		'status' => '1',
		'name' => '指标方向',
		'conftype' => '0',
		'level' => '15',
		'HND0006' => array(
			'增' => '增',
			'减' => '减',
			'公式' => '公式',
			'描述类' => '描述类',
		),
	),
	'HND0007' => array(
		'remark' => '指标分析方式',
		'status' => '1',
		'name' => '指标分析方式',
		'conftype' => '0',
		'level' => '15',
		'HND0007' => array(
			'增加类' => '增加类',
			'减少类' => '减少类',
			'描述类' => '描述类',
			'计算类' => '计算类',
		),
	),
	'HND0008' => array(
		'remark' => '指标归口类别:贷款用途类 成本预测类 收入预测类',
		'status' => '1',
		'name' => '指标归口类别',
		'conftype' => '0',
		'level' => '15',
		'HND0008' => array(
			'贷款用途类' => '贷款用途类',
			'成本预测类' => '成本预测类',
			'收入预测类' => '收入预测类',
		),
	),
	'HND00083' => array(
		'remark' => '家庭成员情况',
		'status' => '1',
		'name' => '家庭成员情况',
		'conftype' => '0',
		'level' => '15',
		'HND00083' => array(
			'配偶' => '配偶',
			'子女' => '子女',
			'父母' => '父母',
		),
	),
	'HND00011' => array(
		'remark' => '农产品认证情况',
		'status' => '1',
		'name' => '农产品认证情况',
		'conftype' => '0',
		'level' => '15',
		'HND00011' => array(
			'绿色' => '绿色',
			'无公害' => '无公害',
			'有机' => '有机',
			'地理标志' => '地理标志',
		),
	),
	'SFYLXJCDA' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'Sun费用类型',
		'conftype' => '0',
		'level' => '15',
		'SFYLXJCDA' => array(
			'1' => '是',
			'0' => '否',
		),
	),
	'XWCJK01' => array(
		'remark' => '',
		'status' => '1',
		'name' => '是否冲借款',
		'conftype' => '0',
		'level' => '15',
		'XWCJK01' => array(
			'1' => '是',
			'0' => '否',
		),
	),
	'XWHKFS01' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'xw还款方式',
		'conftype' => '0',
		'level' => '15',
		'XWHKFS01' => array(
			'0' => '直接还款',
			'1' => '报销冲还款',
		),
	),
	'LHRCJK001' => array(
		'remark' => '是否冲借款',
		'status' => '1',
		'name' => 'LHRCJK',
		'conftype' => '0',
		'level' => '15',
		'LHRCJK001' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'LHRHKFS001' => array(
		'remark' => '还款方式',
		'status' => '1',
		'name' => 'LHR还款方式',
		'conftype' => '0',
		'level' => '15',
		'LHRHKFS001' => array(
			'0' => '直接还款',
			'1' => '报销冲还款',
		),
	),
	'LHRXFLX' => array(
		'remark' => 'LHR消费类型',
		'status' => '1',
		'name' => 'LHR消费类型',
		'conftype' => '0',
		'level' => '15',
		'LHRXFLX' => array(
			'01' => '客户费',
			'0101' => '关系维护费',
			'0102' => '礼品费',
			'02' => '个人费用',
			'0201' => '会客费',
			'0202' => '差旅费',
		),
	),
	'YPHKFS001' => array(
		'remark' => '还款方式',
		'status' => '1',
		'name' => 'YP还款方式',
		'conftype' => '0',
		'level' => '15',
		'YPHKFS001' => array(
			'0' => '直接还款',
			'1' => '报销冲还款',
		),
	),
	'LDsyszb' => array(
		'remark' => 'LD指标取数方式',
		'status' => '1',
		'name' => 'LD指标取数方式',
		'conftype' => '0',
		'level' => '15',
		'LDsyszb' => array(
			'直接取数' => '直接取数',
			'表取数' => '表取数',
		),
	),
	'NDsf001' => array(
		'remark' => 'ND是否默认是',
		'status' => '1',
		'name' => 'ND是否默认是',
		'conftype' => '0',
		'level' => '15',
		'NDsf001' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'LDczfs001' => array(
		'remark' => 'LD出资方式',
		'status' => '1',
		'name' => 'LD出资方式',
		'conftype' => '0',
		'level' => '15',
		'LDczfs001' => array(
			'货币' => '货币',
			'实物' => '实物',
			'知识产权' => '知识产权',
			'土地使用权' => '土地使用权',
			'其他' => '其他',
		),
	),
	'LDsftyxm' => array(
		'remark' => '是否同意项目意见',
		'status' => '1',
		'name' => '是否同意项目意见',
		'conftype' => '0',
		'level' => '15',
		'LDsftyxm' => array(
			'同意项目方案' => '同意项目方案',
			'不同意项目方案' => '不同意项目方案（提出建议）',
		),
	),
	'LDsfaqhk' => array(
		'remark' => 'LD是否按期还款',
		'status' => '1',
		'name' => 'LD是否按期还款',
		'conftype' => '0',
		'level' => '15',
		'LDsfaqhk' => array(
			'是' => '是',
			'否' => '否',
			'未到期' => '未到期',
		),
	),
	'HNDhttype' => array(
		'remark' => '',
		'status' => '1',
		'name' => '黑龙担合同类型',
		'conftype' => '0',
		'level' => '15',
		'HNDhttype' => array(
			'主合同' => '主合同',
			'子合同' => '子合同',
		),
	),
	'HLDdyfdclx' => array(
		'remark' => '黑农担反担保抵押类型',
		'status' => '1',
		'name' => '黑农担反担保抵押类型',
		'conftype' => '0',
		'level' => '15',
		'HLDdyfdclx' => array(
			'登记' => '登记',
			'协议' => '协议',
			'公证' => '公证',
		),
	),
	'HLDfdbzylx' => array(
		'remark' => '黑农担反担保质押类型',
		'status' => '1',
		'name' => '黑农担反担保质押类型',
		'conftype' => '0',
		'level' => '15',
		'HLDfdbzylx' => array(
			'登记' => '登记',
			'协议' => '协议',
			'公证' => '公证',
		),
	),
	'NDczgq' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND出质股权权利状态',
		'conftype' => '0',
		'level' => '15',
		'NDczgq' => array(
			'查封' => '查封',
			'质押' => '质押',
			'正常' => '正常',
		),
	),
	'NDtyfk' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND是否同意放款',
		'conftype' => '0',
		'level' => '15',
		'NDtyfk' => array(
			'全部办理完毕，同意放款' => '全部办理完毕，同意放款',
			'未办理完毕，同意放款' => '未办理完毕，同意放款',
		),
	),
	'HNDzhxz' => array(
		'remark' => '黑农担合作社银行账户账户性质',
		'status' => '1',
		'name' => '黑农担合作社账户性质',
		'conftype' => '0',
		'level' => '15',
		'HNDzhxz' => array(
			'银行卡' => '银行卡',
			'基本户' => '基本户',
			'一般户' => '一般户',
		),
	),
	'HNDdklx' => array(
		'remark' => '黑农担合作社贷款情况贷款类型',
		'status' => '1',
		'name' => '黑农担合作社贷款类型',
		'conftype' => '0',
		'level' => '15',
		'HNDdklx' => array(
			'短期贷款' => '短期贷款',
			'长期贷款' => '长期贷款',
			'流动资金贷款' => '流动资金贷款',
			'固定资金贷款' => '固定资金贷款',
			'其他' => '其他',
		),
	),
	'HNDzclb' => array(
		'remark' => '黑农担合作社资产类别',
		'status' => '1',
		'name' => '黑农担合作社资产类别',
		'conftype' => '0',
		'level' => '15',
		'HNDzclb' => array(
			'存货' => '存货',
			'农机具' => '农机具',
			'场库棚' => '场库棚',
			'车辆' => '车辆',
			'其他' => '其他',
		),
	),
	'HNDyszklx' => array(
		'remark' => '黑农担合作社应收账款类型',
		'status' => '1',
		'name' => '黑农担合作社应收账款类型',
		'conftype' => '0',
		'level' => '15',
		'HNDyszklx' => array(
			'应收账款' => '应收账款',
			'其他应收款' => '其他应收款',
		),
	),
	'HNDjglx' => array(
		'remark' => '黑农担存量客户监管报告监管类型',
		'status' => '1',
		'name' => '黑农担监管类型',
		'conftype' => '0',
		'level' => '15',
		'HNDjglx' => array(
			'首次监管' => '首次监管',
			'不定期监管' => '不定期监管',
			'到期前监管' => '到期前监管',
		),
	),
	'HNDjgfs' => array(
		'remark' => '黑农担存量客户监管报告监管方式',
		'status' => '1',
		'name' => '黑农担监管方式',
		'conftype' => '0',
		'level' => '15',
		'HNDjgfs' => array(
			'实地监管' => '实地监管',
			'委托监管' => '委托监管',
			'通讯监管' => '通讯监管',
		),
	),
	'HNDbdbr' => array(
		'remark' => '',
		'status' => '1',
		'name' => '被担保人关系类型',
		'conftype' => '0',
		'level' => '15',
		'HNDbdbr' => array(
			'上下游企业' => '上下游企业',
			'关联企业' => '关联企业',
			'其他' => '其他',
		),
	),
	'hnddkyttype' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'HND贷款用途类别',
		'conftype' => '0',
		'level' => '15',
		'hnddkyttype' => array(
			'流动资金贷款' => '流动资金贷款',
			'固定资产贷款' => '固定资产贷款',
		),
	),
	'HNDQYYCL' => array(
		'remark' => '黑农担企业库存情况',
		'status' => '1',
		'name' => '黑农担企业库存情况',
		'conftype' => '0',
		'level' => '15',
		'HNDQYYCL' => array(
			'原材料' => '原材料',
			'半成品' => '半成品',
			'产成品' => '产成品',
			'包装物' => '包装物',
		),
	),
	'HNDfxcz' => array(
		'remark' => '',
		'status' => '1',
		'name' => '风险处置计划',
		'conftype' => '0',
		'level' => '15',
		'HNDfxcz' => array(
			'降低风险分类上迁' => '降低风险分类上迁',
			'压缩回收' => '压缩回收',
			'其他' => '其他',
		),
	),
	'HNDfxdj' => array(
		'remark' => '',
		'status' => '1',
		'name' => '风险等级',
		'conftype' => '0',
		'level' => '15',
		'HNDfxdj' => array(
			'正常' => '正常',
			'关注' => '关注',
			'预警' => '预警',
			'风险' => '风险',
			'损失' => '损失',
		),
	),
	'hnddklb' => array(
		'remark' => '贷款用途类别',
		'status' => '1',
		'name' => '贷款用途类别',
		'conftype' => '0',
		'level' => '15',
		'hnddklb' => array(
			'流动资金贷款' => '流动资金贷款',
			'固定资产贷款' => '固定资产贷款',
		),
	),
	'hndbhjgfs01' => array(
		'remark' => '保后监管方式',
		'status' => '1',
		'name' => '保后监管方式',
		'conftype' => '0',
		'level' => '15',
		'hndbhjgfs01' => array(
			'实地监管' => '实地监管',
			'委托监管' => '委托监管',
			'通讯监管' => '通讯监管',
		),
	),
	'HNDhtmb' => array(
		'remark' => '',
		'status' => '1',
		'name' => '合同模板',
		'conftype' => '0',
		'level' => '15',
		'HNDhtmb' => array(
			'承诺书' => '承诺书',
			'委托担保合同' => '委托担保合同',
		),
	),
	'NDsys001' => array(
		'remark' => '操作类型',
		'status' => '1',
		'name' => '操作类型',
		'conftype' => '0',
		'level' => '15',
		'NDsys001' => array(
			'控制' => '控制',
			'计算' => '计算',
		),
	),
	'NDsys002' => array(
		'remark' => '控制时点',
		'status' => '1',
		'name' => '控制时点',
		'conftype' => '0',
		'level' => '15',
		'NDsys002' => array(
			'保存前' => '保存前',
			'保存后' => '保存后',
			'提交前' => '提交前',
			'提交后' => '提交后',
			'删除前' => '删除前',
			'删除后' => '删除后',
		),
	),
	'HNDztblqk' => array(
		'remark' => '',
		'status' => '1',
		'name' => '总体办理情况',
		'conftype' => '0',
		'level' => '15',
		'HNDztblqk' => array(
			'全部办理完毕' => '全部办理完毕',
			'未办理完毕' => '未办理完毕',
		),
	),
	'HNDbllb' => array(
		'remark' => '',
		'status' => '1',
		'name' => '办理类别',
		'conftype' => '0',
		'level' => '15',
		'HNDbllb' => array(
			'出库' => '出库',
			'入库' => '入库',
		),
	),
	'HNDsqd' => array(
		'remark' => '',
		'status' => '1',
		'name' => '申请单变更类型',
		'conftype' => '0',
		'level' => '15',
		'HNDsqd' => array(
			'备案类' => '备案类',
			'报批类' => '报批类',
		),
	),
	'HNDytje' => array(
		'remark' => '',
		'status' => '1',
		'name' => '应退金额',
		'conftype' => '0',
		'level' => '15',
		'HNDytje' => array(
			'担保费' => '担保费',
			'监管费' => '监管费',
		),
	),
	'HNDjsfs' => array(
		'remark' => '',
		'status' => '1',
		'name' => '结算方式',
		'conftype' => '0',
		'level' => '15',
		'HNDjsfs' => array(
			'支票' => '支票',
			'汇款' => '汇款',
		),
	),
	'HND00830' => array(
		'remark' => '黑放还款操作类型，放款计划、还款计划的识别类型',
		'status' => '1',
		'name' => '黑放还款操作类型',
		'conftype' => '0',
		'level' => '15',
		'HND00830' => array(
			'放款' => '放款',
			'还款' => '还款',
		),
	),
	'HNDfkfs' => array(
		'remark' => '',
		'status' => '1',
		'name' => '付款方式',
		'conftype' => '0',
		'level' => '15',
		'HNDfkfs' => array(
			'一年一付' => '一年一付',
			'两年一付' => '两年一付',
			'一次付清' => '一次付清',
		),
	),
	'wttype' => array(
		'remark' => '问题类别',
		'status' => '1',
		'name' => '问题类别',
		'conftype' => '0',
		'level' => '15',
		'wttype' => array(
			'基础数据完善' => '基础数据完善',
			'流程完善' => '流程完善',
			'表单调整' => '表单调整',
			'Word模板完善' => 'Word模板完善',
			'数据调整' => '数据调整',
			'后台处理' => '后台处理',
			'程序BUG' => '程序BUG',
			'其他' => '其他',
		),
	),
);

?>