<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'status' => '1',
		'isexport' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '单号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'name',
		'showname' => '设备名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'10' => array(
		'name' => 'falut_type',
		'showname' => '故障类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'falut_type',
		'sortnum' => '4',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.falut_type',
		'table' => 'mis_logistics_fix_logtype',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_logistics_fix_logtype',
				),
			),
		),
	),
	'3' => array(
		'name' => 'report_name',
		'showname' => '报修人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'report_name',
		'sortnum' => '5',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.report_name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '1',
		'message' => '1',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'department_name',
		'showname' => '报修部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'department_name',
		'sortnum' => '6',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.department_name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'12' => array(
		'name' => 'createtime',
		'showname' => '报修日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '13',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'fix_man',
		'showname' => '检修人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fix_man',
		'sortnum' => '8',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.fix_man',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'6' => array(
		'name' => 'fault_cause',
		'showname' => '故障描述',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fault_cause',
		'sortnum' => '9',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'missubstr',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '40',
					'2' => '1',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.fault_cause',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'fix_time',
		'showname' => '检修日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fix_time',
		'sortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.fix_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'solution',
		'showname' => '处理方法',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'solution',
		'sortnum' => '11',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'missubstr',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '40',
					'2' => '1',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.solution',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'fixed',
		'showname' => '结果',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fixed',
		'sortnum' => '12',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '0:未处理,1:修复,2:未修复,3:报废,4:外修,5:其它',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_logistics_fix_log.fixed',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|fixed',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'68' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'sortname' => 'auditState',
		'sortnum' => '13',
		'issearch' => '0',
		'searchField' => 'mis_logistics_fix_log.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '68',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'69' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '14',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '日常维护记录',
					'7' => '630',
					'8' => '550',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
);

?>