<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'1' => array(
		'name' => 'name',
		'showname' => '计算机标识',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '1',
		'searchField' => 'mis_computer.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
	),
	'2' => array(
		'name' => 'type',
		'showname' => '类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'type',
		'sortnum' => '2',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:台式机,2:笔记本,3:相机,4:服务器,5:打印机,6:网络设备,7:电话机,8:其它',
				),
			),
		),
		'searchField' => 'mis_computer.type',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|dnbzgltype',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '2',
	),
	'3' => array(
		'name' => 'oem',
		'showname' => '品牌',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'oem',
		'sortnum' => '3',
		'searchField' => 'mis_computer.oem',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'4' => array(
		'name' => 'department_id',
		'showname' => '使用部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'department_id',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'searchField' => 'mis_computer.department_id',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
	),
	'5' => array(
		'name' => 'principal',
		'showname' => '负责人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'principal',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'sortnum' => '5',
		'searchField' => 'mis_computer.principal',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '5',
	),
	'6' => array(
		'name' => 'user_id',
		'showname' => '当前用户',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'user_id',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'sortnum' => '6',
		'searchField' => 'mis_computer.user_id',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
	),
	'7' => array(
		'name' => 'buy_time',
		'showname' => '购买时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'buy_time',
		'sortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_computer.buy_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '7',
	),
	'8' => array(
		'name' => 'price',
		'showname' => '价格',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'price',
		'sortnum' => '8',
		'searchField' => 'mis_computer.price',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '8',
	),
	'16' => array(
		'name' => 'modisplay_screen',
		'showname' => '显示器',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modisplay_screen',
		'sortnum' => '8',
		'searchField' => 'mis_computer.modisplay_screen',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '8',
	),
	'9' => array(
		'name' => 'model',
		'showname' => '型号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'model',
		'sortnum' => '9',
		'searchField' => 'mis_computer.model',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '9',
	),
	'10' => array(
		'name' => 'os',
		'showname' => '系统',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => '系统',
		'sortnum' => '10',
		'searchField' => 'mis_computer.os',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '10',
	),
	'11' => array(
		'name' => 'cpu',
		'showname' => '处理器',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'cpu',
		'sortnum' => '11',
		'searchField' => 'mis_computer.cpu',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '11',
	),
	'12' => array(
		'name' => 'ram',
		'showname' => '内存',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'ram',
		'sortnum' => '12',
		'searchField' => 'mis_computer.ram',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '12',
	),
	'13' => array(
		'name' => 'hardisk',
		'showname' => '硬盘',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hardisk',
		'sortnum' => '13',
		'searchField' => 'mis_computer.hardisk',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '13',
	),
	'14' => array(
		'name' => 'mainboard',
		'showname' => '主板',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mainboard',
		'sortnum' => '14',
		'searchField' => 'mis_computer.mainboard',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '14',
	),
	'15' => array(
		'name' => 'graphics_card',
		'showname' => '显卡',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'graphics_card',
		'sortnum' => '15',
		'searchField' => 'mis_computer.graphics_card',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '15',
	),
	'17' => array(
		'name' => 'cd_rom',
		'showname' => '光驱',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'cd_rom',
		'sortnum' => '17',
		'searchField' => 'mis_computer.cd_rom',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '17',
	),
	'18' => array(
		'name' => 'network_card',
		'showname' => '网卡',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'network_card',
		'sortnum' => '18',
		'searchField' => 'mis_computer.network_card',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '18',
	),
	'19' => array(
		'name' => 'other_hardware',
		'showname' => '其它硬件',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'other_hardware',
		'sortnum' => '19',
		'searchField' => 'mis_computer.other_hardware',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '19',
	),
	'20' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '20',
		'searchField' => 'mis_computer.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '20',
	),
	'21' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '21',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '电脑配置',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
	),
);

?>