<?php 
return array(
	'0' => array(
		'name' => '序号',
		'showname' => 'id',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => 'mis_officialdocument_in.id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '0',
	),
	'1' => array(
		'name' => 'referencenum',
		'showname' => '文号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'referencenum',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_officialdocument_in.referencenum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'isexport' => '1',
	),
	'9' => array(
		'name' => 'filename',
		'showname' => '文件名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'filename',
		'sortnum' => '3',
		'issearch' => '0',
		'searchField' => 'mis_officialdocument_in.filename',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '0',
	),
	'2' => array(
		'name' => 'typeid',
		'showname' => '类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'typeid',
		'sortnum' => '4',
		'issearch' => '0',
		'searchField' => 'mis_officialdocument_type.typeid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
		'isexport' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_officialdocument_type',
				),
			),
		),
	),
	'5' => array(
		'name' => 'incompany',
		'showname' => '来文单位',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'incompany',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_officialdocument_in.incompany',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '0',
	),
	'3' => array(
		'name' => 'secrecylevel',
		'showname' => '密级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'secrecylevel',
		'sortnum' => '7',
		'issearch' => '0',
		'searchField' => 'mis_officialdocument_in.secrecylevel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
		'isexport' => '0',
	),
	'8' => array(
		'name' => 'copynum',
		'showname' => '份数',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'copynum',
		'sortnum' => '10',
		'issearch' => '0',
		'searchField' => 'mis_officialdocument_in.copynum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '0',
	),
	'12' => array(
		'name' => 'undertakeempId',
		'showname' => '承办人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisHrBasicEmployee',
				),
			),
		),
		'sortname' => 'undertakeempId',
		'sortnum' => '13',
		'issearch' => '1',
		'searchField' => 'mis_officialdocument_in.undertakeempId',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'isexport' => '1',
	),
	'13' => array(
		'name' => 'phone',
		'showname' => '电话',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'phone',
		'sortnum' => '14',
		'issearch' => '0',
		'searchField' => 'mis_officialdocument_in.phone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '0',
	),
	'15' => array(
		'name' => 'auditState',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'sortnum' => '16',
		'searchField' => 'mis_officialdocument_in.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '0',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '-1:打回,0:新建,1:批阅中,2:批阅中,3:批阅完成',
				),
			),
		),
	),
	'16' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '17',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getDestroyOption',
			),
			'2' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '收文批阅',
				),
			),
			'1' => array(
				'0' => array(
					'0' => 'MisBusinessContractAlarm',
					'1' => '#id#',
					'2' => '#auditState#',
					'3' => '#status#',
					'4' => '__MODULE__',
				),
			),
			'2' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'isexport' => '0',
	),
);

?>