<?php
/**
 * @Title: htViewModel
 * @Package package_name
 * @Description: todo(动态表单_自动生成-合同视图)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2017-05-17 17:42:41
 * @version V1.0
*/
class htViewModel extends ViewModel {
	public $viewFields = array(
		'mis_auto_bklne'=>array('_as'=>'mis_auto_bklne','projectid','id'=>'xiangmubianma','xiangmumingchen','kehumingchen','dangqiankehmc','zhuti','chanyelian','yewuleixing','shangjibianhao','canzhaoxiangmubianha','zixunxiangmubianma','zhudiao','fudiao','daikuanyongtu','daikuanyongtumiaoshu','rongzifangan','zaibaojine','shenqingjine','shenqingyewuqixian','yifangkuanjine','shengyujine','pifuqixian','pifujine','lixiangbumen','lixiangren','fengxiandengji','fengxianxiangmuzhuan','fengxianxiangmulixia','lixiangriqi','kehudizhi','youbian','xiangmujieduan','yewujianyijine','yewujianyiqixian','fengkongjianyijine','fengkongjianyiqixian','zhuanjiajianyijine','pifuchujuriqi','canzhaoxiangmuyewule','canzhaoxiangmufengxi','zhutileixing','zhuanjiajianyiqixian','yewuyuanjianyijine','yewuyuanjianyiqixian','fengkongyuanjianyiji','fengkongyuanjianyiqi','yewuyuanyijian','fengkongyuanyijian','yewubuyijian','fengkongbuyijian','zhuanjiayijian','chaoeshouyibiaozhun','chaoeshouyijine','peiyumubiao','_type'=>'LEFT'),
		'mis_auto_fqtej'=>array('_as'=>'mis_auto_fqtej','orderno'=>'zhuhetongbianma','pifudanhao','hezuoyinxing','jiekuanhetonghao','jiekuanhetongmingche','jiekuanjine','jiekuanhetongqiandin','baozhenghetonghao','baozhenghetongqiandi','weituodaikuanjiekuanhetonghao','weituodaikuanweituohetonghao','fangkuanriqi'=>'yinghangfangkuanriqi','huaikuanriqi'=>'yinghanghuankuanriqi','weituobaozhenghetong','weituobaozhenghetongk','lvxingzhaiwukaishiri','lvxingzhaiwujiezhiri','weituodaikuanhetongb','weituodaikuanhetongq','weituodaikuanhetongm','daikuannianlilv','caiwuguwenxieyibianh','caiwuguwenxieyiqiand','caiwuguwenfei','danbaofeilv','weidaifeilv','danbaodaikuanleixing'=>'danbaojiekuanleixing','weituodaikuanweituoh','weituodaikuanweituohb','chuangtoujijinfenlei','rugubili','touzixieyibianhao','touzijine','touzixieyiqiandingri','touzikaishiriqi','touzijiezhiriqi','menjianshouyi','jijianfuwufeilv','jiekuanqixian','jingjizixunfuwuxieyi','_on'=>'mis_auto_bklne.xiangmubianma=mis_auto_fqtej.xiangmubianma'),
		'mis_auto_zbotm'=>array('_as'=>'mis_auto_zbotm','orderno'=>'zihetongbianma','fenshu','fandanbaocuoshibianh','fandanbaocuoshizhong','pinggujigou','_on'=>'mis_auto_fqtej.orderno=mis_auto_zbotm.zhuhetonghao'),
		'mis_auto_offsz'=>array('_as'=>'mis_auto_offsz','gongsiquanchen','zhusuodi'=>'jiafangzhusuodi','zhuyaojingyingjigous'=>'jiafangzhuyaojingyingjigous','farendaibiao'=>'jiafangfarendaibiao','kaihuyinxing'=>'jiafangkaihuyinxing','kaihuyinxingzhanghao'=>'jiafangkaihuyinxingzhanghao','dianhuahaoma'=>'jiafangdianhuahaoma','chuanzhen'=>'jiafangchuanzhen','youbian'=>'jiafangyoubian','yingyezhizhaozhuceha'=>'jiafangyingyezhizhaozhuceha','_on'=>'mis_auto_bklne.jiekuanzhuti=mis_auto_offsz.gongsimingchen'),
		'mis_auto_banmo'=>array('_as'=>'mis_auto_banmo','zhucedizhi','fadingdaibiaorenxing','jibenhukaihuyinxing'=>'yifangjibenhukaihuyinxing','kaihuzhanghu'=>'yifangkaihuzhanghu','chuanzhen'=>'yifangchuanzhen','youzhengbianma'=>'yifangyouzhengbianma','yingyezhizhaozhuceha','fadingdaibiaorenzhenj'=>'yifangfadingdaibiaorenzhenj','_on'=>'mis_auto_bklne.kehumingchen=mis_auto_banmo.orderno'),
		'mis_auto_feiof'=>array('_as'=>'mis_auto_feiof','orderno'=>'weituobaozhenghetongbianma','jiekuanhetongmingche'=>'wtjiekuanhetongmingche','jiedaikuanhetongbian'=>'wtjiedaikuanhetongbian','jiekuanbenjinxiaoxie'=>'wtjiekuanbenjinxiaoxie','jiekuanhetongqiandina'=>'wtjiekuanhetongqiandina','qixianyue','danbaofeijinexiaoxie','fengxianbaozhengjinb','fengxianbaozhengjin','_on'=>'mis_auto_fqtej.orderno=mis_auto_feiof.zhuhetongbianhao'),
		'mis_auto_pherk'=>array('_as'=>'mis_auto_pherk','hetongleixing','cuoshileixing','shifushangdingjiaweiyuanhui','shifuweipaipinggujigou','pinggujiazhi','zuojia','quyu','yongtu','tudixingzhi','mianjijianzhu','pinggubaogao','jutidizhi','chanquanshiyongquanren','fentantudimianji','danjia','shebeishuliang','guquanbili','shangpinmingchenshoufeiquanmingchen','yupingriqi','zhengpingriqi','pinggufeiyong','chengnuoqitatiaojian','fandanbaocuoshifenxi','xiangmumingchen','quanzhengshifuruku','zhuangtai','dizhiyadangan','suoyouren','quanzhengbianhao','weizhi','zongjia','zhenghao','yushoufangxukezhengh','pingguzhizhangmianzh','lindimianjimu','guquanfene','jine','shangbiaodeng','zongdimianji','banlishixiao','jiazhipinggufangshi','yanqibanlimiaoshu','banlileixing','gujia','mingchen','jiegou','danwei','hejijine','beizhu','shouyiquanleixing','nizhuanranggongsimin','zhiyaguquansuozaigon','chengnuoren','chengnuorenmiaoshu','baoxianpinzhong','guanlianxiangmubianm','narongyinyong','xiangmuleixing','youwubianhua','pifushifusheji','_on'=>'mis_auto_zbotm.fandanbaocuoshibianh=mis_auto_pherk.orderno'),
		'mis_auto_nthzg'=>array('_as'=>'mis_auto_nthzg','name'=>'pgjg','_on'=>'mis_auto_pherk.pinggujigou=mis_auto_nthzg.orderno'),
		''=>array('_as'=>'','zhuyaojingyingjigous'=>'yifangzhuyaojingyingjigous','dianhuahaoma'=>'yifangdianhuahaoma',),
);
}
?>