<?php 
return array(
	'1' => array(
		'name' => 'title',
		'showname' => '标题',
		'shows' => '1',
		'widths' => '10',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '1',
		'searchField' => 'check_for_obj.title',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'filter_condition',
		'showname' => '过滤条件',
		'shows' => '1',
		'widths' => '55',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'data',
		'sortnum' => '2',
		'searchField' => 'check_for_obj.filter_condition',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'3' => array(
		'name' => 'show_fields',
		'showname' => '显示字段',
		'shows' => '1',
		'widths' => '5',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'data',
		'sortnum' => '3',
		'searchField' => 'check_for_obj.show_fields',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'4' => array(
		'name' => 'fields',
		'showname' => '列表显示字段',
		'shows' => '1',
		'widths' => '20',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'data',
		'sortnum' => '4',
		'searchField' => 'check_for_obj.fields',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'5' => array(
		'name' => 'hidden_field',
		'showname' => '隐藏字段',
		'shows' => '1',
		'widths' => '20',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'data',
		'sortnum' => '4',
		'searchField' => 'check_for_obj.hidden_field',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'sort_condition',
		'showname' => '排序条件',
		'shows' => '1',
		'widths' => '5',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'data',
		'sortnum' => '5',
		'searchField' => 'check_for_obj.sort_condition',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '5',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
);

?>