<?php 
// return array(
// 	'0' => array(
// 		'name' => 'id',
// 		'showname' => '编号',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'id',
// 		'sortnum' => '1',
// 	),
// 	'1' => array(
// 		'name' => 'code',
// 		'showname' => '编号',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'code',
// 		'sortnum' => '1',
// 	),
// 	'2' => array(
// 		'name' => 'name',
// 		'showname' => '专家',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'name',
// 		'sortnum' => '2',
// 	),
// 	'3' => array(
// 		'name' => 'typename',
// 		'showname' => '类型',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'typename',
// 		'sortnum' => '3',
// 	),
// 	'4' => array(
// 		'name' => 'email',
// 		'showname' => '邮箱',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'email',
// 		'sortnum' => '4',
// 	),
// 	'5' => array(
// 		'name' => 'qq',
// 		'showname' => 'QQ号',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'qq',
// 		'sortnum' => '5',
// 	),
// 	'6' => array(
// 		'name' => 'tel',
// 		'showname' => '电话',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'tel',
// 		'sortnum' => '6',
// 	),
// 	'7' => array(
// 		'name' => 'text',
// 		'showname' => '备注',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'text',
// 		'sortnum' => '7',
// 	),
// 	'8' => array(
// 		'name' => 'action',
// 		'showname' => '操作',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'status',
// 		'func' => array(
// 			'0' => array(
// 				'0' => 'showStatus',
// 			),
// 		),
// 		'funcdata' => array(
// 			'0' => array(
// 				'0' => array(
// 					'0' => '#status#',
// 					'1' => '#id#',
// 				),
// 			),
// 		),
// 		'sortnum' => '9',
// 	),
// );

// ?>