<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-data)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2016-08-24 11:08:06
 * @version V1.0
*/
return array(
	'id' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'id',
		'type' => 'int(11)',
		'nullable' => 'NO',
		'default' => NULL,
		'primary' => 'PRI',
		'autoinc' => 'auto_increment',
		'comment' => 'ID',
	),
	'pingshenweiyuanleixi' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'pingshenweiyuanleixi',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审委员类型',
	),
	'fandanbaocuoshishifu' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fandanbaocuoshishifu',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '反担保措施是否合理',
	),
	'shifushoufei' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shifushoufei',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否收费',
	),
	'pinggufeiyong' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'pinggufeiyong',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评估费用',
	),
	'pingshenyijian' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'pingshenyijian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审意见',
	),
	'jianyijine' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jianyijine',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '建议借(贷)款金额',
	),
	'jianyidanbaolv' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jianyidanbaolv',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '建议担保费率',
	),
	'jianyiqixian' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jianyiqixian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '建议借(贷)款期限',
	),
	'jianyi' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jianyi',
		'type' => 'text',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审表决理由及建议',
	),
	'bindid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'bindid',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '绑定id',
	),
	'orderno' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'orderno',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '编号',
	),
	'status' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'status',
		'type' => 'tinyint(1)',
		'nullable' => 'YES',
		'default' => '1',
		'primary' => '',
		'autoinc' => '',
		'comment' => '状态',
	),
	'companyid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'companyid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '公司ID',
	),
	'createid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'createid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '创建人ID',
	),
	'createtime' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'createtime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '创建时间',
	),
	'updateid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'updateid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '修改人ID',
	),
	'updatetime' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'updatetime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '修改时间',
	),
	'operateid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'operateid',
		'type' => 'int(1)',
		'nullable' => 'NO',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否确认',
	),
	'departmentid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'departmentid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '部门ID',
	),
	'projectid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'projectid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目ID',
	),
	'projectworkid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'projectworkid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '任务ID',
	),
	'sysdutyid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'sysdutyid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '职级ID',
	),
	'relationmodelname' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'relationmodelname',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '关系型表单关联model',
	),
	'ptmptid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'ptmptid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '固定流程ID',
	),
	'flowid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'flowid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '自定义流程ID',
	),
	'ostatus' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'ostatus',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前审核节点',
	),
	'auditState' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'auditState',
		'type' => 'tinyint(1)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前审核状态',
	),
	'curAuditUser' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'curAuditUser',
		'type' => 'varchar(300)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前可审核人清单',
	),
	'curNodeUser' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'curNodeUser',
		'type' => 'varchar(300)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前待审核人清单',
	),
	'alreadyAuditUser' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'alreadyAuditUser',
		'type' => 'varchar(500)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前已审核人',
	),
	'alreadyauditnode' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'alreadyauditnode',
		'type' => 'varchar(200)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前并行时已审核节点',
	),
	'auditUser' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'auditUser',
		'type' => 'varchar(500)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '所有审核人清单',
	),
	'allnode' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'allnode',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '所有流程节点',
	),
	'informpersonid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'informpersonid',
		'type' => 'varchar(500)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '节点知道会人',
	),
	'parentid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'parentid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '父类ID',
	),
	'name' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'name',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '名称',
	),
	'kehumingchen' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'kehumingchen',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户名称',
	),
	'xiangmumingchen' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'xiangmumingchen',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目名称',
	),
	'xiangmubianma' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'xiangmubianma',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目编码',
	),
	'zijinyongtu' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'zijinyongtu',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '资金用途',
	),
	'yewuleixing' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yewuleixing',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务类型',
	),
	'fengxiandingjialiyou' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengxiandingjialiyou',
		'type' => 'text',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风险定价理由及建议',
	),
	'fengxiandingjiayijia' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengxiandingjiayijia',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风险定价意见',
	),
	'shenqingjine' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shenqingjine',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户申请金额',
	),
	'shenqingqixian' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shenqingqixian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户申请期限',
	),
	'shouqubaozhengjinbil' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shouqubaozhengjinbil',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '保证金减免率',
	),
	'pingshenhuiid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'pingshenhuiid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审会id',
	),
	'zhaojidanid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'zhaojidanid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '召集单id',
	),
	'zhaojidansubid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'zhaojidansubid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '召集单subid',
	),
	'shifunabu' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shifunabu',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否内部',
	),
	'pingshenhuileixing' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'pingshenhuileixing',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审会类型',
	),
	'expertid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'expertid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '专家表决id',
	),
	'userid' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'userid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '用户表决id',
	),
	'shifoujieshu' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shifoujieshu',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否结束',
	),
	'biaojueren' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'biaojueren',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '表决人',
	),
	'jiekuanzhuti' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jiekuanzhuti',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '借款主体',
	),
	'shifuzhuanjia' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shifuzhuanjia',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否专家',
	),
	'biaojueriqi' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'biaojueriqi',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '表决日期',
	),
	'jianyiweidaifeilv' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jianyiweidaifeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '建议委贷费率',
	),
	'xiangmuxinxina' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'xiangmuxinxina',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目信息(内）',
	),
	'xiangmuxinxiwai' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'xiangmuxinxiwai',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目信息(外)',
	),
	'danbaojiekuanleixing' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'danbaojiekuanleixing',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '担保借款类型',
	),
	'rugubili' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'rugubili',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '入股比例',
	),
	'peiyumubiao' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'peiyumubiao',
		'type' => 'text',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '培育目标',
	),
	'zhitoujine' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'zhitoujine',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '直投金额',
	),
	'shanghuishunxu' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shanghuishunxu',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '上会顺序',
	),
	'jianyizongjine' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jianyizongjine',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '建议总金额',
	),
	'zhitouqixian' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'zhitouqixian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '直投期限',
	),
	'zhudiao' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'zhudiao',
		'type' => 'varchar(80)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '主调',
	),
	'fengkongrenyuan' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengkongrenyuan',
		'type' => 'varchar(80)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员',
	),
	'baozhengjinjianmianl' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'baozhengjinjianmianl',
		'type' => 'varchar(300)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '保证金减免率',
	),
	'yixiangdanbaofeilv' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yixiangdanbaofeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '意向担保费率',
	),
	'shifuduixiangmurenyu' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shifuduixiangmurenyu',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否对项目人员评分',
	),
	'touzirennianhuashouy' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'touzirennianhuashouy',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '投资人年化收益率',
	),
	'yewurenyuanyijian' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yewurenyuanyijian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员意见',
	),
	'yewurenyuanjianyijie' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yewurenyuanjianyijie',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议借(贷)款金额',
	),
	'yewurenyuanjianyijier' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yewurenyuanjianyijier',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议借(贷)款期限',
	),
	'yewurenyuanjianyizhi' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yewurenyuanjianyizhi',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议直投金额',
	),
	'yewurenyuanjianyizhiy' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yewurenyuanjianyizhiy',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议直投期限',
	),
	'yewurenyuanjianyizon' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'yewurenyuanjianyizon',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议总金额',
	),
	'fengkongrenyuanyijia' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengkongrenyuanyijia',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员意见',
	),
	'fengkongrenyuanjiany' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengkongrenyuanjiany',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议借(贷)款金额',
	),
	'fengkongrenyuanjianye' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengkongrenyuanjianye',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议借(贷)款期限',
	),
	'fengkongrenyuanjianyg' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengkongrenyuanjianyg',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议直投金额',
	),
	'fengkongrenyuanjianyi' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengkongrenyuanjianyi',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议直投期限',
	),
	'fengkongrenyuanjianyk' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'fengkongrenyuanjianyk',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议总金额',
	),
	'kehujichuxinyonglian' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'kehujichuxinyonglian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户基础信用量化',
	),
	'chanpinleixing' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'chanpinleixing',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '产品类型',
	),
	'jijianfuwufeilv' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'jijianfuwufeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '居间服务费率',
	),
	'shifusanchanronghexi' => array(
		'tablename' => 'mis_auto_njzcw',
		'name' => 'shifusanchanronghexi',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否三产融合项目',
	),
);

?>