<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-系统视图list.inc 配置文件)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2015-01-28 15:56:51
 * @version V1.0
*/
return array(
	'zhtbh' => array(
		'name' => 'zhtbh',
		'showname' => '主合同编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhtbh',
		'sortnum' => '5',
		'searchField' => 'mis_auto_zbotm.zhuhetonghao',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
	'hzyh' => array(
		'name' => 'hzyh',
		'showname' => '合作银行',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hzyh',
		'sortnum' => '5',
		'searchField' => 'mis_auto_fqtej.hezuoyinxing',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'helpvalue' => '',
	),
	'jkhth' => array(
		'name' => 'jkhth',
		'showname' => '借款合同号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jkhth',
		'sortnum' => '5',
		'searchField' => 'mis_auto_fqtej.jiekuanhetonghao',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'helpvalue' => '',
	),
	'bzhth' => array(
		'name' => 'bzhth',
		'showname' => '保证合同号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bzhth',
		'sortnum' => '5',
		'searchField' => 'mis_auto_fqtej.baozhenghetonghao',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'helpvalue' => '',
	),
	'jkje' => array(
		'name' => 'jkje',
		'showname' => '借款金额',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jkje',
		'sortnum' => '5',
		'searchField' => 'mis_auto_fqtej.jiekuanjine',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'helpvalue' => '',
	),
	'wtdkjkhth' => array(
		'name' => 'wtdkjkhth',
		'showname' => '委托贷款借款合同号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'wtdkjkhth',
		'sortnum' => '5',
		'searchField' => 'mis_auto_fqtej.weituodaikuanjiekuanhetonghao',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'helpvalue' => '',
	),
	'wtdkwthth' => array(
		'name' => 'wtdkwthth',
		'showname' => '委托贷款委托合同号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'wtdkwthth',
		'sortnum' => '5',
		'searchField' => 'mis_auto_fqtej.weituodaikuanweituohetonghao',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'helpvalue' => '',
	),
	'htfs' => array(
		'name' => 'htfs',
		'showname' => '合同份数',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'htfs',
		'sortnum' => '5',
		'searchField' => 'mis_auto_zbotm.fenshu',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'helpvalue' => '',
	),
);

?>