<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-list.inc 配置文件)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2017-12-03 15:48:48
 * @version V1.0
*/
$original = array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'status' => '1',
		'sortname' => 'id',
		'sortnum' => '0',
		'searchField' => 'mis_auto_sxlpg.id',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'message' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '表决编号',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '0',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.orderno',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '1',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'xiangmubianma' => array(
		'name' => 'xiangmubianma',
		'showname' => '项目编码',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoPvb',
		'sortname' => 'xiangmubianma',
		'sortnum' => '1',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sxlpg.xiangmubianma',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_bklne',
				),
			),
		),
		'table' => 'mis_auto_bklne',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_bklne',
				),
			),
		),
	),
	'kehumingchen' => array(
		'name' => 'kehumingchen',
		'showname' => '客户名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'kehumingchen',
		'sortnum' => '2',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.kehumingchen',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'kehumingchen',
					'3' => 'mis_auto_banmo',
				),
			),
		),
		'table' => 'mis_auto_banmo',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'kehumingchen',
					'3' => 'mis_auto_banmo',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '2',
	),
	'xiangmumingchen' => array(
		'name' => 'xiangmumingchen',
		'showname' => '项目名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmumingchen',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.xiangmumingchen',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'yewuleixing' => array(
		'name' => 'yewuleixing',
		'showname' => '业务类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewuleixing',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.yewuleixing',
		'conditions' => 'outlinelevel=1',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'table' => 'mis_system_flow_type',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '4',
	),
	'zijinyongtu' => array(
		'name' => 'zijinyongtu',
		'showname' => '资金用途',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zijinyongtu',
		'sortnum' => '5',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.zijinyongtu',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_hgwtp',
				),
			),
		),
		'table' => 'mis_auto_hgwtp',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_hgwtp',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '5',
	),
	'shenqingjine' => array(
		'name' => 'shenqingjine',
		'showname' => '客户申请金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingjine',
		'sortnum' => '6',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.shenqingjine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
	),
	'shenqingqixian' => array(
		'name' => 'shenqingqixian',
		'showname' => '客户申请期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingqixian',
		'sortnum' => '7',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.shenqingqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '7',
	),
	'danbaojiekuanleixing' => array(
		'name' => 'danbaojiekuanleixing',
		'showname' => '担保借款类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'danbaojiekuanleixing',
		'sortnum' => '8',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.danbaojiekuanleixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_xacre',
				),
			),
		),
		'table' => 'mis_auto_xacre',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_xacre',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '8',
	),
	'baozhengjinjianmianl' => array(
		'name' => 'baozhengjinjianmianl',
		'showname' => '保证金减免率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'baozhengjinjianmianl',
		'sortnum' => '9',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.baozhengjinjianmianl',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '9',
	),
	'yewupinzhong' => array(
		'name' => 'yewupinzhong',
		'showname' => '业务品种',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewupinzhong',
		'sortnum' => '10',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.yewupinzhong',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_rsild',
				),
			),
		),
		'table' => 'mis_auto_rsild',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_rsild',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '10',
	),
	'fandanbaocuoshifenxi' => array(
		'name' => 'fandanbaocuoshifenxi',
		'showname' => '反担保措施分析单号',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoAbo',
		'sortname' => 'fandanbaocuoshifenxi',
		'sortnum' => '11',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'projectid',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sxlpg.fandanbaocuoshifenxi',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'projectid',
					'2' => 'orderno',
					'3' => 'mis_auto_vgzgn',
				),
			),
		),
		'table' => 'mis_auto_vgzgn',
		'field' => 'projectid',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'projectid',
					'2' => 'orderno',
					'3' => 'mis_auto_vgzgn',
				),
			),
		),
	),
	'biangenghuizongdanha' => array(
		'name' => 'biangenghuizongdanha',
		'showname' => '被变更汇总单号',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoUid',
		'sortname' => 'biangenghuizongdanha',
		'sortnum' => '12',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sxlpg.biangenghuizongdanha',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_dzzvn',
				),
			),
		),
		'table' => 'mis_auto_dzzvn',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '12',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_dzzvn',
				),
			),
		),
	),
	'biangengshenqingdanh' => array(
		'name' => 'biangengshenqingdanh',
		'showname' => '被变更申请单号',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoHxr',
		'sortname' => 'biangengshenqingdanh',
		'sortnum' => '13',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sxlpg.biangengshenqingdanh',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_sdkln',
				),
			),
		),
		'table' => 'mis_auto_sdkln',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '13',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_sdkln',
				),
			),
		),
	),
	'biangengshenqingdan' => array(
		'name' => 'biangengshenqingdan',
		'showname' => '变更申请单',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoLpr',
		'sortname' => 'biangengshenqingdan',
		'sortnum' => '14',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sxlpg.biangengshenqingdan',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_vvhjl',
				),
			),
		),
		'table' => 'mis_auto_vvhjl',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '14',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_vvhjl',
				),
			),
		),
	),
	'pingshenyijian' => array(
		'name' => 'pingshenyijian',
		'showname' => '评审意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenyijian',
		'sortnum' => '15',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.pingshenyijian',
		'conditions' => '',
		'type' => 'select|NBPSYJ',
		'validate' => NULL,
		'unique' => '0',
		'required' => '1',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'NBPSYJ',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'NBPSYJ',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '15',
	),
	'jianyijine' => array(
		'name' => 'jianyijine',
		'showname' => '建议借(贷)款金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyijine',
		'sortnum' => '16',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.jianyijine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '16',
	),
	'jianyiqixian' => array(
		'name' => 'jianyiqixian',
		'showname' => '建议借(贷)款期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyiqixian',
		'sortnum' => '17',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.jianyiqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '17',
	),
	'yixiangdanbaofeilv' => array(
		'name' => 'yixiangdanbaofeilv',
		'showname' => '担保费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yixiangdanbaofeilv',
		'sortnum' => '18',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.yixiangdanbaofeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '18',
	),
	'fandanbaocuoshi' => array(
		'name' => 'fandanbaocuoshi',
		'showname' => '反担保措施',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fandanbaocuoshi',
		'sortnum' => '19',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_sxlpg.fandanbaocuoshi',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '19',
	),
	'caozuoyaodian' => array(
		'name' => 'caozuoyaodian',
		'showname' => '操作要点',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'caozuoyaodian',
		'sortnum' => '20',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_sxlpg.caozuoyaodian',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '20',
	),
	'jianyi' => array(
		'name' => 'jianyi',
		'showname' => '评审表决理由及建议',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyi',
		'sortnum' => '21',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_sxlpg.jianyi',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '1',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '21',
	),
	'pingweiqianzi' => array(
		'name' => 'pingweiqianzi',
		'showname' => '评委签字',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingweiqianzi',
		'sortnum' => '22',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.pingweiqianzi',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '22',
	),
	'pingshenhuiid' => array(
		'name' => 'pingshenhuiid',
		'showname' => '评审会id',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenhuiid',
		'sortnum' => '23',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_sxlpg.pingshenhuiid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'zhaojidanid' => array(
		'name' => 'zhaojidanid',
		'showname' => '召集单id',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhaojidanid',
		'sortnum' => '24',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_sxlpg.zhaojidanid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'zhaojidansubid' => array(
		'name' => 'zhaojidansubid',
		'showname' => '召集单subid',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhaojidansubid',
		'sortnum' => '25',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_sxlpg.zhaojidansubid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'pingshenhuileixing' => array(
		'name' => 'pingshenhuileixing',
		'showname' => '评审会类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenhuileixing',
		'sortnum' => '26',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.pingshenhuileixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_fwvvg',
				),
			),
		),
		'table' => 'mis_auto_fwvvg',
		'field' => 'id',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_fwvvg',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '26',
	),
	'jianyifengxiandengji' => array(
		'name' => 'jianyifengxiandengji',
		'showname' => '建议风险等级',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyifengxiandengji',
		'sortnum' => '27',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.jianyifengxiandengji',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dwodg',
				),
			),
		),
		'table' => 'mis_auto_dwodg',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dwodg',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '27',
	),
	'dangqianfengxiandeng' => array(
		'name' => 'dangqianfengxiandeng',
		'showname' => '当前风险等级',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dangqianfengxiandeng',
		'sortnum' => '28',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.dangqianfengxiandeng',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dwodg',
				),
			),
		),
		'table' => 'mis_auto_dwodg',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dwodg',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '28',
	),
	'biaojueriqi' => array(
		'name' => 'biaojueriqi',
		'showname' => '表决日期',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'biaojueriqi',
		'sortnum' => '29',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_sxlpg.biaojueriqi',
		'conditions' => '',
		'type' => 'time',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '29',
		'unfunc' => array(
			'0' => array(
				'0' => 'untransTime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d',
				),
			),
		),
	),
	'baohouleixing' => array(
		'name' => 'baohouleixing',
		'showname' => '保后类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'baohouleixing',
		'sortnum' => '30',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.baohouleixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_iehbc',
				),
			),
		),
		'table' => 'mis_auto_iehbc',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_iehbc',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '30',
	),
	'shifuhege' => array(
		'name' => 'shifuhege',
		'showname' => '是否合格',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifuhege',
		'sortnum' => '31',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.shifuhege',
		'conditions' => '',
		'type' => 'select|ND00318',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'ND00318',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'ND00318',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '31',
	),
	'shanghuishunxu' => array(
		'name' => 'shanghuishunxu',
		'showname' => '上会顺序',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shanghuishunxu',
		'sortnum' => '32',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sxlpg.shanghuishunxu',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '32',
	),
	'baohouzhixingdanhao' => array(
		'name' => 'baohouzhixingdanhao',
		'showname' => '保后执行单号',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoTkv',
		'sortname' => 'baohouzhixingdanhao',
		'sortnum' => '33',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sxlpg.baohouzhixingdanhao',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_wmahy',
				),
			),
		),
		'table' => 'mis_auto_wmahy',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '33',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_wmahy',
				),
			),
		),
	),
	'departmentid' => array(
		'name' => 'departmentid',
		'showname' => '部门',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'departmentid',
		'sortnum' => '34',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sxlpg.departmentid',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'table' => 'mis_system_department',
		'field' => 'id',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '34',
	),
	'action' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '37',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'operateid' => array(
		'name' => 'operateid',
		'showname' => '是否确认',
		'rules' => '1',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'operateidVal',
					'1' => '###',
				),
			),
		),
		'sortname' => 'operateid',
		'sortnum' => '38',
		'searchField' => 'mis_auto_sxlpg.operateid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'companyid' => array(
		'name' => 'companyid',
		'showname' => '公司',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemCompany',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
		'sortname' => 'companyid',
		'sortnum' => '39',
		'issearch' => '1',
		'table' => 'mis_system_company',
		'searchField' => 'mis_auto_sxlpg.companyid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
	),
	'projectid' => array(
		'name' => 'projectid',
		'showname' => '项目ID',
		'rules' => '0',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectid',
		'sortnum' => '40',
		'searchField' => 'mis_auto_sxlpg.projectid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'createid' => array(
		'name' => 'createid',
		'rules' => '1',
		'showname' => '创建人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'sortname' => 'createid',
		'issearch' => '1',
		'table' => 'user',
		'sortnum' => '41',
		'searchField' => 'mis_auto_sxlpg.createid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
	),
	'createtime' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '42',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_sxlpg.createtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'helpvalue' => '',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'untranstime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
);

$extedsList = require 'listExtend.inc.php';
return array_merge($original , $extedsList);
?>