<?php 
return array(
	'34' => array(
		'name' => 'orderno',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '1',
		'searchField' => 'mis_auto_kimpu.orderno',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'name' => array(
		'name' => 'name',
		'showname' => '项目名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '2',
		'searchField' => 'mis_auto_kimpu.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'1' => array(
		'name' => 'typeid',
		'showname' => '业务类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'typeid',
		'sortnum' => '3',
		'searchField' => 'mis_auto_kimpu.typeid',
		'conditions' => 'outlinelevel,1',
		'type' => 'select',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'table' => 'mis_system_flow_type',
		'field' => 'name',
		'helpvalue' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
	),
	'2' => array(
		'name' => 'zt',
		'showname' => '主体',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zt',
		'sortnum' => '4',
		'searchField' => 'mis_auto_kimpu.zt',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'table' => 'mis_sale_client_type',
		'field' => 'name',
		'helpvalue' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_sale_client_type',
				),
			),
		),
	),
	'3' => array(
		'name' => 'hy',
		'showname' => '行业',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hy',
		'sortnum' => '5',
		'searchField' => 'mis_auto_kimpu.hy',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'table' => 'mis_sale_profession',
		'field' => 'name',
		'helpvalue' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_sale_profession',
				),
			),
		),
	),
	'4' => array(
		'name' => 'cyl',
		'showname' => '产业链',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'cyl',
		'sortnum' => '6',
		'searchField' => 'mis_auto_kimpu.cyl',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'table' => 'mis_sale_industry',
		'field' => 'name',
		'helpvalue' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_sale_industry',
				),
			),
		),
	),
	'5' => array(
		'name' => 'sjid',
		'showname' => '商机编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sjid',
		'sortnum' => '7',
		'searchField' => 'mis_auto_kimpu.sjid',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'sjuserid',
		'showname' => '商机所属人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sjuserid',
		'sortnum' => '8',
		'searchField' => 'mis_auto_kimpu.sjuserid',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'7' => array(
		'name' => 'projectcode',
		'showname' => '参照项目编码',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectcode',
		'sortnum' => '9',
		'searchField' => 'mis_auto_kimpu.projectcode',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'projectname',
		'showname' => '参照项目名称',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectname',
		'sortnum' => '10',
		'searchField' => 'mis_auto_kimpu.projectname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'9' => array(
		'name' => 'projectstatus',
		'showname' => '参照项目状态',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectstatus',
		'sortnum' => '11',
		'searchField' => 'mis_auto_kimpu.projectstatus',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'debit',
				),
			),
		),
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'10' => array(
		'name' => 'zd',
		'showname' => '主调',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zd',
		'sortnum' => '12',
		'searchField' => 'mis_auto_kimpu.zd',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'name',
		'helpvalue' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'11' => array(
		'name' => 'fd',
		'showname' => '副调',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fd',
		'sortnum' => '13',
		'searchField' => 'mis_auto_kimpu.fd',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'name',
		'helpvalue' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'36' => array(
		'name' => 'customerid',
		'showname' => '客户',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'customerid',
		'sortnum' => '14',
		'issearch' => '0',
		'searchField' => 'mis_auto_kimpu.customerid',
		'table' => 'mis_auto_kimpu',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '0',
		'searchsortnum' => '37',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'kehumingchen',
					'3' => 'MisAutoCbj',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'37' => array(
		'name' => 'zddeptname',
		'showname' => '主调部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zddeptname',
		'sortnum' => '37',
		'issearch' => '0',
		'searchField' => 'mis_auto_kimpu.zddeptname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '38',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'type' => array(
		'name' => 'type',
		'showname' => '是否完成',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'type',
		'sortnum' => '38',
		'issearch' => '1',
		'searchField' => 'mis_auto_kimpu.type',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|YesOrNoFinish',
		'isallsearch' => '1',
		'searchsortnum' => '39',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'YesOrNoFinish',
				),
			),
		),
	),
	'35' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '39',
		'helpvalue' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
);

?>