<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'1' => array(
		'name' => 'roid',
		'showname' => '申请人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'roid',
		'sortnum' => '2',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'usename',
					'3' => 'mis_request_car',
				),
			),
		),
		'searchField' => 'mis_car_return.roid',
		'table' => 'mis_request_car',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db|usename',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'carID',
		'showname' => '车辆名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'carID',
		'sortnum' => '3',
		'extention_html_end' => array(
			'0' => '-',
		),
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
			'1' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'carno',
					'3' => 'mis_system_car',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_car',
				),
			),
		),
		'searchField' => 'mis_car_return.carID',
		'table' => 'mis_system_car,mis_request_car',
		'field' => '',
		'conditions' => '',
		'type' => 'db|name,carID',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'3' => array(
		'name' => 'totalKM',
		'showname' => '总里数',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'totalKM',
		'sortnum' => '4',
		'searchField' => 'mis_car_return.totalKM',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'5' => array(
		'name' => 'runKM',
		'showname' => '运行里程',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'runKM',
		'sortnum' => '6',
		'searchField' => 'mis_car_return.runKM',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'addOilNo',
		'showname' => '加油量',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'addOilNo',
		'sortnum' => '7',
		'searchField' => 'mis_car_return.addOilNo',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'7' => array(
		'name' => 'returnTime',
		'showname' => '返回时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'returnTime',
		'sortnum' => '8',
		'searchField' => 'mis_car_return.returnTime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:m',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'keepTimeTrue',
		'showname' => '实际使用时长',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'keepTimeTrue',
		'sortnum' => '9',
		'searchField' => 'mis_car_return.keepTimeTrue',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'9' => array(
		'name' => 'trueJourney',
		'showname' => '实际行程（由司机填写）',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'trueJourney',
		'sortnum' => '10',
		'searchField' => 'mis_car_return.trueJourney',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '10',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'10' => array(
		'name' => 'helthStatus',
		'showname' => '有/无异常',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'helthStatus',
		'sortnum' => '11',
		'searchField' => 'mis_car_return.helthStatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'46' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '47',
		'status' => '1',
		'isexport' => '0',
		'rules' => '0',
		'message' => '0',
	),
);

?>