<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'1' => array(
		'name' => 'code',
		'showname' => '单位代码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'code',
		'sortnum' => '2',
		'searchField' => 'mis_product_unittype.code',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '单位名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'searchField' => 'mis_product_unittype.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'3' => array(
			'name' => 'unittypeid',
			'showname' => '单位类型',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'unittypeid',
			'sortnum' => '4',
			'searchField' => 'mis_product_unittype.unittypeid',
			'table' => '',
			'field' => '',
			'conditions' => '',
			'type' => 'text',
			'issearch' => '1',
			'isallsearch' => '4',
			'searchsortnum' => '0',
			'func' => array(
					'0' => array(
							'0' => 'getSelectByName',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => 'unittype',
									'1' => '###',
							),
					),
			),
	),
	'4' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '产品单位类型',
					'7'=>'680',
					'8'=>'200',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
	),
);

?>