<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'status' => '1',
		'isexport' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '申请单号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'organization',
		'showname' => '单位名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.organization',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'leisure',
		'showname' => '是否闲置',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leisure',
		'sortnum' => '4',
		'status' => '-1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_room.leisure',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#objid#',
					'1' => 'id',
					'2' => 'leisure',
					'3' => '#objmodelname#',
					'4' => '',
				),
				'1' => array(
					'0' => '###',
					'1' => '1:闲置,0:使用中',
				),
			),
		),
	),
	'5' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '5',
		'status' => '-1',
		'isexport' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'linkman',
		'showname' => '联系人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'linkman',
		'sortnum' => '6',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.linkman',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'linktel',
		'showname' => '联系电话',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'linktel',
		'sortnum' => '7',
		'status' => '-1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.linktel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'10' => array(
		'name' => 'meetingtime',
		'showname' => '使用日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'meetingtime',
		'sortnum' => '8',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.meetingtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
	'11' => array(
		'name' => 'estimatedStrtime',
		'showname' => '使用开始时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'estimatedStrtime',
		'sortnum' => '9',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.estimatedStrtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
	'12' => array(
		'name' => 'estimatedEndtime',
		'showname' => '结束开始时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'estimatedEndtime',
		'sortnum' => '10',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.estimatedEndtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
	'13' => array(
		'name' => 'objid',
		'showname' => '会议室ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'objid',
		'sortnum' => '11',
		'status' => '-1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.objid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'14' => array(
		'name' => 'estimatedcount',
		'showname' => '会议人数',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'estimatedcount',
		'sortnum' => '12',
		'status' => '-1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.estimatedcount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'15' => array(
		'name' => 'amount',
		'showname' => '会务费',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'amount',
		'sortnum' => '13',
		'status' => '-1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.amount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
	'17' => array(
		'name' => 'abolish',
		'showname' => '记录状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'abolish',
		'sortnum' => '15',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.abolish',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:作废,2:正常',
				),
			),
		),
	),
	'18' => array(
		'name' => 'principal',
		'showname' => '负责人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'principal',
		'sortnum' => '16',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.principal',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'19' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '17',
		'status' => '-1',
		'isexport' => '1',
		'searchField' => 'mis_meeting_use_record.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'rules' => '0',
		'message' => '1',
		'helpvalue' => '',
	),
	'22' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '18',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '-1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '会议室使用',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
);

?>