<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-data)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2015-05-11 19:11:31
 * @version V1.0
*/
return array(
	'id' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'id',
		'type' => 'int(11)',
		'nullable' => 'NO',
		'default' => NULL,
		'primary' => 'PRI',
		'autoinc' => 'auto_increment',
		'comment' => 'ID',
	),
	'clientname' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'clientname',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户名称',
	),
	'businessstatus' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'businessstatus',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => '1',
		'primary' => '',
		'autoinc' => '',
		'comment' => '商机状态',
	),
	'controller' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'controller',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '实际控制人',
	),
	'mobile' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'mobile',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '手机',
	),
	'sourceid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'sourceid',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '商机来源',
	),
	'intentiontypesid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'intentiontypesid',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '意向业务类型',
	),
	'areaid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'areaid',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '区域',
	),
	'customertypeid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'customertypeid',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户主体',
	),
	'professionid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'professionid',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '行业',
	),
	'industryid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'industryid',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '产业链',
	),
	'address' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'address',
		'type' => 'varchar(255)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '经营地址',
	),
	'linkman' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'linkman',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '联系人',
	),
	'acquiretime' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'acquiretime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '获取时间',
	),
	'endtime' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'endtime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '效期截止日',
	),
	'userid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'userid',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务员',
	),
	'provider' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'provider',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '商机提供人',
	),
	'name' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'name',
		'type' => 'varchar(255)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '商机描述',
	),
	'days' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'days',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '有效天数',
	),
	'toolid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'toolid',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户端类型',
	),
	'orderno' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'orderno',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '编号',
	),
	'status' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'status',
		'type' => 'tinyint(1)',
		'nullable' => 'YES',
		'default' => '1',
		'primary' => '',
		'autoinc' => '',
		'comment' => '状态',
	),
	'companyid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'companyid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '公司ID',
	),
	'departmentid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'departmentid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '部门ID',
	),
	'createid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'createid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '创建人ID',
	),
	'createtime' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'createtime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '创建时间',
	),
	'updatetime' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'updatetime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '修改时间',
	),
	'updateid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'updateid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '修改人ID',
	),
	'remark' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'remark',
		'type' => 'varchar(255)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '备注',
	),
	'detailaddress' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'detailaddress',
		'type' => 'varchar(255)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '详细地址',
	),
	'mapx' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'mapx',
		'type' => 'varchar(255)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '经度',
	),
	'mapy' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'mapy',
		'type' => 'varchar(255)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '纬度',
	),
	'sysdutyid' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'sysdutyid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => 'èŒçº§ID',
	),
	'relationmodelname' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'relationmodelname',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '关系型表单关联model',
	),
	'turncustomer' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'turncustomer',
		'type' => 'tinyint(1)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否转客户  0未转1转',
	),
	'bangongdianhua' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'bangongdianhua',
		'type' => 'varchar(20)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '办公电话',
	),
	'chuanzhen' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'chuanzhen',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '传真',
	),
	'zhucedizhi' => array(
		'tablename' => 'mis_sale_business',
		'name' => 'zhucedizhi',
		'type' => 'varchar(500)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '注册地址',
	),
);

?>