<?php 
return array(
	'clientname' => array(
		'name' => 'clientname',
		'showname' => '客户名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'clientname',
		'sortnum' => '1',
		'searchField' => 'mis_sale_business.clientname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'kehujichuxinyongping' => array(
		'name' => 'kehujichuxinyongping',
		'showname' => '客户基础信用评分表',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoRec',
		'sortname' => 'kehujichuxinyongping',
		'sortnum' => '2',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_sale_business.kehujichuxinyongping',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_rec',
				),
			),
		),
		'table' => 'mis_auto_rec',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_rec',
				),
			),
		),
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'shifuzhuanweixiangmu' => array(
		'name' => 'shifuzhuanweixiangmu',
		'showname' => '是否转为项目',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifuzhuanweixiangmu',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'tinyint',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_rulcn.shifuzhuanweixiangmu',
		'conditions' => '',
		'type' => 'select|YesOrNo',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'YesOrNo',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'YesOrNo',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'xiangmubianhao' => array(
		'name' => 'xiangmubianhao',
		'showname' => '项目编号',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmubianhao',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_rulcn.xiangmubianhao',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '商机编码',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_sale_business.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '1',
		'searchsortnum' => '21',
		'status' => NULL,
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'supcategory' => array(
		'name' => 'supcategory',
		'showname' => '业务类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'supcategory',
		'sortnum' => '6',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_rulcn.supcategory',
		'conditions' => 'outlinelevel=1',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'table' => 'mis_system_flow_type',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'controller' => array(
		'name' => 'controller',
		'showname' => '实际控制人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'controller',
		'sortnum' => '7',
		'searchField' => 'mis_sale_business.controller',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'mobile' => array(
		'name' => 'mobile',
		'showname' => '移动电话',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mobile',
		'sortnum' => '8',
		'issearch' => '0',
		'searchField' => 'mis_sale_business.mobile',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => NULL,
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'category' => array(
		'name' => 'category',
		'showname' => '项目阶段',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'category',
		'sortnum' => '9',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_rulcn.category',
		'conditions' => 'outlinelevel=2',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'table' => 'mis_system_flow_type',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'sourceid' => array(
		'name' => 'sourceid',
		'showname' => '商机来源',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sourceid',
		'sortnum' => '10',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.sourceid',
		'table' => 'mis_sale_business_source',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => NULL,
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_business_source',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'pifujine' => array(
		'name' => 'pifujine',
		'showname' => '批复金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pifujine',
		'sortnum' => '11',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_rulcn.pifujine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'intentiontypesid' => array(
		'name' => 'intentiontypesid',
		'showname' => '业务类型',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'intentiontypesid',
		'sortnum' => '12',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.intentiontypesid',
		'table' => 'mis_system_flow_type',
		'field' => 'orderno',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => NULL,
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'areaid' => array(
		'name' => 'areaid',
		'showname' => '区域',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'areaid',
		'sortnum' => '13',
		'searchField' => 'mis_sale_business.areaid',
		'conditions' => '',
		'type' => 'group',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'MisAutoMji',
				),
			),
		),
		'table' => 'mis_auto_jcztc',
		'field' => 'orderno',
		'helpvalue' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'pifuqixian' => array(
		'name' => 'pifuqixian',
		'showname' => '批复期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pifuqixian',
		'sortnum' => '14',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_rulcn.pifuqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '7',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'customertypeid' => array(
		'name' => 'customertypeid',
		'showname' => '客户主体',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'customertypeid',
		'sortnum' => '15',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.customertypeid',
		'table' => 'mis_sale_client_type',
		'field' => 'orderno',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'status' => NULL,
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_sale_client_type',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'fangkuanjine' => array(
		'name' => 'fangkuanjine',
		'showname' => '放款金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fangkuanjine',
		'sortnum' => '16',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_rulcn.fangkuanjine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'professionid' => array(
		'name' => 'professionid',
		'showname' => '行业',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'professionid',
		'sortnum' => '17',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.professionid',
		'table' => 'mis_sale_profession',
		'field' => 'orderno',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '7',
		'status' => NULL,
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_sale_profession',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'fangkuanqixian' => array(
		'name' => 'fangkuanqixian',
		'showname' => '放款期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fangkuanqixian',
		'sortnum' => '18',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_rulcn.fangkuanqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '9',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'industryid' => array(
		'name' => 'industryid',
		'showname' => '产业链',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'industryid',
		'sortnum' => '19',
		'searchField' => 'mis_sale_business.industryid',
		'conditions' => '',
		'type' => 'group',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'table' => 'mis_sale_industry',
		'field' => 'orderno',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_sale_industry',
				),
			),
		),
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'address' => array(
		'name' => 'address',
		'showname' => '经营地址',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'address',
		'sortnum' => '20',
		'searchField' => 'mis_sale_business.address',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'linkman' => array(
		'name' => 'linkman',
		'showname' => '联系人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'linkman',
		'sortnum' => '21',
		'searchField' => 'mis_sale_business.linkman',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'xiangmuzhudiao' => array(
		'name' => 'xiangmuzhudiao',
		'showname' => '项目主调',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmuzhudiao',
		'sortnum' => '22',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_sale_business.xiangmuzhudiao',
		'conditions' => '',
		'type' => 'db|name',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '12',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'acquiretime' => array(
		'name' => 'acquiretime',
		'showname' => '获取时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'acquiretime',
		'sortnum' => '23',
		'searchField' => 'mis_sale_business.acquiretime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'endtime' => array(
		'name' => 'endtime',
		'showname' => '有效日期',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'endtime',
		'sortnum' => '24',
		'searchField' => 'mis_sale_business.endtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '12',
		'func' => array(
			'0' => array(
				'0' => 'getDayBiaozhu',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#endtime#',
					'1' => 'endtime',
					'2' => '#businessstatus#',
				),
			),
		),
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'provider' => array(
		'name' => 'provider',
		'showname' => '商机提供人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'provider',
		'sortnum' => '25',
		'searchField' => 'mis_sale_business.provider',
		'conditions' => '',
		'type' => 'group',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'helpvalue' => '',
		'table' => 'User',
		'field' => 'id',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'name' => array(
		'name' => 'name',
		'showname' => '商机描述',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '26',
		'searchField' => 'mis_sale_business.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '15',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'toolid' => array(
		'name' => 'toolid',
		'showname' => '客户端类型',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'toolid',
		'sortnum' => '27',
		'searchField' => 'mis_sale_business.toolid',
		'conditions' => '',
		'type' => 'select|tool',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '16',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'tool',
				),
			),
		),
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'businessstatus' => array(
		'name' => 'businessstatus',
		'showname' => '商机状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'businessstatus',
		'sortnum' => '28',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.businessstatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|businessstatus',
		'isallsearch' => '1',
		'searchsortnum' => '17',
		'status' => NULL,
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'businessstatus',
				),
			),
		),
		'rules' => '1',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'remark' => array(
		'name' => 'remark',
		'showname' => '转储备说明',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '29',
		'searchField' => 'mis_sale_business.remark',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '18',
		'helpvalue' => '',
		'table' => '',
		'field' => '',
		'status' => NULL,
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'action' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '30',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => NULL,
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'days' => array(
		'name' => 'days',
		'showname' => '有效天数',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'days',
		'sortnum' => '31',
		'issearch' => '0',
		'searchField' => '',
		'table' => 'mis_sale_business.days',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '22',
		'status' => NULL,
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'chuanzhen' => array(
		'name' => 'chuanzhen',
		'showname' => '传真',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chuanzhen',
		'sortnum' => '32',
		'issearch' => '0',
		'searchField' => 'mis_sale_business.chuanzhen',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '23',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'zhucedizhi' => array(
		'name' => 'zhucedizhi',
		'showname' => '注册地址',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhucedizhi',
		'sortnum' => '33',
		'issearch' => '0',
		'searchField' => 'mis_sale_business.zhucedizhi',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '23',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'bangongdianhua' => array(
		'name' => 'bangongdianhua',
		'showname' => '办公电话',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bangongdianhua',
		'sortnum' => '34',
		'issearch' => '0',
		'searchField' => 'mis_sale_business.bangongdianhua',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '23',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'shixiao' => array(
		'name' => 'shixiao',
		'showname' => '是否失效',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shixiao',
		'sortnum' => '35',
		'issearch' => '1',
		'searchField' => 'mis_sale_business_allot.shixiao',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|YesOrNo',
		'isallsearch' => '1',
		'searchsortnum' => '28',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'YesOrNo',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'allotuserid' => array(
		'name' => 'allotuserid',
		'showname' => '业务员',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'userid',
		'sortnum' => '36',
		'issearch' => '0',
		'searchField' => 'mis_sale_business_allot.userid',
		'table' => 'User',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '0',
		'searchsortnum' => '21',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'endstatus' => array(
		'name' => 'endstatus',
		'showname' => '是否超期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'endstatus',
		'sortnum' => '37',
		'searchField' => 'mis_sale_business_allot.endstatus',
		'conditions' => '',
		'type' => 'select|endstatus',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '18',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'endstatus',
				),
			),
		),
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'table' => '',
		'field' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'allotendtime' => array(
		'name' => 'allotendtime',
		'showname' => '处理截止日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'endtime',
		'sortnum' => '38',
		'issearch' => '0',
		'searchField' => 'mis_sale_business_allot.endtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '19',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getDayBiaozhu',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#allotendtime#',
					'1' => 'allotendtime',
					'2' => '#businessstatus#',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'xuqiushijian' => array(
		'name' => 'xuqiushijian',
		'showname' => '资金需求时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xuqiushijian',
		'sortnum' => '39',
		'searchField' => 'mis_sale_business.xuqiushijian',
		'conditions' => '',
		'type' => 'select|FundsNeedTime',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '18',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'FundsNeedTime',
				),
			),
		),
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'table' => '',
		'field' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'xuanzeleixing' => array(
		'name' => 'xuanzeleixing',
		'showname' => '提供人类型',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xuanzeleixing',
		'sortnum' => '40',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.xuanzeleixing',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|UserOrInterfaceLocation',
		'isallsearch' => '1',
		'searchsortnum' => '29',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'UserOrInterfaceLocation',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
);

?>