<?php 
return array(
	'0' => array(
		'name' => 'name',
		'showname' => '客户名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '1',
		'searchField' => 'mis_sale_client_basic.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'1' => array(
		'name' => 'mobile',
		'showname' => '手机',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mobile',
		'sortnum' => '2',
		'searchField' => 'mis_sale_client_basic.mobile',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
	),
	'2' => array(
		'name' => 'areaid',
		'showname' => '所在区域',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'areaid',
		'sortnum' => '3',
		'searchField' => 'mis_sale_client_basic.areaid',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sales_site',
				),
			),
		),
		'table' => 'a',
		'field' => 'name',
	),
	'3' => array(
		'name' => 'customertypeid',
		'showname' => '客户主体',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'customertypeid',
		'sortnum' => '4',
		'searchField' => 'mis_sale_client_basic.customertypeid',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_customer_type',
				),
			),
		),
		'table' => 'mis_sale_customer_type',
		'field' => 'name',
	),
	'4' => array(
		'name' => 'professionid',
		'showname' => '行业',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'professionid',
		'sortnum' => '5',
		'searchField' => 'mis_sale_client_basic.professionid',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_profession',
				),
			),
		),
		'table' => 'a',
		'field' => 'name',
	),
	'5' => array(
		'name' => 'industryid',
		'showname' => '产业链',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'industryid',
		'sortnum' => '6',
		'searchField' => 'mis_sale_client_basic.industryid',
		'conditions' => '',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSaleIndustry',
				),
			),
		),
		'table' => 'MisSaleIndustry',
		'field' => 'name',
	),
	'6' => array(
		'name' => 'address',
		'showname' => '地址',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'address',
		'sortnum' => '7',
		'searchField' => 'mis_sale_client_basic.address',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '6',
	),
	'7' => array(
		'name' => 'linkman',
		'showname' => '联系人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'linkman',
		'sortnum' => '8',
		'searchField' => 'mis_sale_client_basic.linkman',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
	),
	'8' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '9',
		'searchField' => 'mis_sale_client_basic.remark',
		'conditions' => '',
		'type' => 'textarea',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '8',
	),
	'9' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '10',
	),
);

?>