<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-data)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2016-09-23 14:11:25
 * @version V1.0
*/
return array(
	'id' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'id',
		'type' => 'int(11)',
		'nullable' => 'NO',
		'default' => NULL,
		'primary' => 'PRI',
		'autoinc' => 'auto_increment',
		'comment' => 'ID',
	),
	'xiangmubianhao' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'xiangmubianhao',
		'type' => 'varchar(60)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目编号',
	),
	'xiangmumingchen' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'xiangmumingchen',
		'type' => 'varchar(150)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目名称',
	),
	'kehumingchen' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'kehumingchen',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户名称',
	),
	'canpingjine' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'canpingjine',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '参评金额',
	),
	'pingshenjine' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenjine',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审金额',
	),
	'pingshenjianyijine' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenjianyijine',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审建议金额',
	),
	'xiangmujiedian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'xiangmujiedian',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '项目节点',
	),
	'pingshenleixing' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenleixing',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审类型',
	),
	'orderno' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'orderno',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '编号',
	),
	'conveneStatus' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'conveneStatus',
		'type' => 'tinyint(1)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '召集状态 0未召集 1已召集',
	),
	'status' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'status',
		'type' => 'tinyint(1)',
		'nullable' => 'YES',
		'default' => '1',
		'primary' => '',
		'autoinc' => '',
		'comment' => '状态',
	),
	'companyid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'companyid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '公司ID',
	),
	'createid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'createid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '创建人ID',
	),
	'createtime' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'createtime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '创建时间',
	),
	'updateid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'updateid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '修改人ID',
	),
	'bindid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'bindid',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '绑定id',
	),
	'updatetime' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'updatetime',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '修改时间',
	),
	'operateid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'operateid',
		'type' => 'int(1)',
		'nullable' => 'NO',
		'default' => '0',
		'primary' => 'MUL',
		'autoinc' => '',
		'comment' => '是否确认',
	),
	'departmentid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'departmentid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '部门ID',
	),
	'projectid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'projectid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => 'MUL',
		'autoinc' => '',
		'comment' => '项目ID',
	),
	'projectworkid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'projectworkid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '任务ID',
	),
	'sysdutyid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'sysdutyid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '职级ID',
	),
	'relationmodelname' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'relationmodelname',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '关系型表单关联model',
	),
	'ptmptid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'ptmptid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '固定流程ID',
	),
	'flowid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'flowid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '自定义流程ID',
	),
	'ostatus' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'ostatus',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前审核节点',
	),
	'auditState' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'auditState',
		'type' => 'tinyint(1)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前审核状态',
	),
	'curAuditUser' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'curAuditUser',
		'type' => 'varchar(300)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前可审核人清单',
	),
	'curNodeUser' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'curNodeUser',
		'type' => 'varchar(300)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前待审核人清单',
	),
	'alreadyAuditUser' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'alreadyAuditUser',
		'type' => 'varchar(500)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前已审核人',
	),
	'alreadyauditnode' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'alreadyauditnode',
		'type' => 'varchar(200)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前并行时已审核节点',
	),
	'auditUser' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'auditUser',
		'type' => 'varchar(500)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '所有审核人清单',
	),
	'allnode' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'allnode',
		'type' => 'varchar(100)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => 'MUL',
		'autoinc' => '',
		'comment' => '所有流程节点',
	),
	'informpersonid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'informpersonid',
		'type' => 'varchar(500)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '节点知道会人',
	),
	'name' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'name',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '名称',
	),
	'parentid' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'parentid',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => '0',
		'primary' => '',
		'autoinc' => '',
		'comment' => '父类ID',
	),
	'canpinglilv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'canpinglilv',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '参评利率',
	),
	'canpingqixian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'canpingqixian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '参评期限',
	),
	'pingshenlilv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenlilv',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审利率',
	),
	'pingshenqixian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenqixian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审期限',
	),
	'huizongshuoming' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'huizongshuoming',
		'type' => 'tinytext',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审结果',
	),
	'shenqingjine' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'shenqingjine',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户申请金额',
	),
	'shenqingqixian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'shenqingqixian',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户申请期限',
	),
	'datatable16' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'datatable16',
		'type' => 'varchar(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '表决明细',
	),
	'yewubujianyijine' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewubujianyijine',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务部建议金额',
	),
	'fengkongbujianyijine' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongbujianyijine',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控部建议金额',
	),
	'yewubujianyiqixian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewubujianyiqixian',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务部建议期限',
	),
	'fengkongbujianyiqixi' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongbujianyiqixi',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控部建议期限',
	),
	'shifufuyixiangmu' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'shifufuyixiangmu',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否复议项目',
	),
	'danbaofeilv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'danbaofeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '担保费率',
	),
	'yewuleixing' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewuleixing',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务类型',
	),
	'zijinyongtu' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'zijinyongtu',
		'type' => 'varchar(50)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '资金用途',
	),
	'shifupingshen' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'shifupingshen',
		'type' => 'varchar(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否评审',
	),
	'pingshenhuiyijiyaona' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenhuiyijiyaona',
		'type' => 'text',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务内部评审会决议',
	),
	'yewurenyuanyijian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanyijian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员意见',
	),
	'yewurenyuanjianyijin' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanjianyijin',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议金额',
	),
	'yewurenyuanjianyiqix' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanjianyiqix',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议期限',
	),
	'fengkongrenyuanyijia' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanyijia',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员意见',
	),
	'fengkongrenyuanjiany' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanjiany',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议金额',
	),
	'fengkongrenyuanjianyf' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanjianyf',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议期限',
	),
	'yewubuyijian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewubuyijian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务部意见',
	),
	'fengkongbuyijian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongbuyijian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控部意见',
	),
	'pingshenmoshi' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenmoshi',
		'type' => 'varchar(60)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审模式',
	),
	'datatable23' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'datatable23',
		'type' => 'varchar(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '内嵌数据表格_23',
	),
	'jiekuanzhuti' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'jiekuanzhuti',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '借款主体',
	),
	'weidaifeilv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'weidaifeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '委贷费率',
	),
	'baozhengjinlv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'baozhengjinlv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '保证金率',
	),
	'dangqianfengxiandeng' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'dangqianfengxiandeng',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '当前风险等级',
	),
	'pingshenjiyaoyinyong' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenjiyaoyinyong',
		'type' => 'varchar(60)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审纪要引用',
	),
	'pingshenfujian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenfujian',
		'type' => 'varchar(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务评审会附件',
	),
	'shifushanghui' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'shifushanghui',
		'type' => 'varchar(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否上会',
	),
	'shanghuishijian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'shanghuishijian',
		'type' => 'int(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '上会时间',
	),
	'zhaojidanhao' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'zhaojidanhao',
		'type' => 'varchar(140)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '召集单号',
	),
	'jianyidanbaofeilv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'jianyidanbaofeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '建议担保费率',
	),
	'danbaojiekuanleixing' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'danbaojiekuanleixing',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '担保借款类型',
	),
	'pingshenhuibeizhu' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'pingshenhuibeizhu',
		'type' => 'longtext',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '评审会备注',
	),
	'zhuanjiajianyizhitou' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'zhuanjiajianyizhitou',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '专家建议直投金额',
	),
	'zhuanjiajianyizhitoub' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'zhuanjiajianyizhitoub',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '专家建议直投期限',
	),
	'zhuanjiayijian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'zhuanjiayijian',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '专家意见',
	),
	'rugubili' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'rugubili',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '入股比例',
	),
	'peiyumubiao' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'peiyumubiao',
		'type' => 'text',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '培育目标',
	),
	'zhuanjiajianyizongji' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'zhuanjiajianyizongji',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '专家建议总金额',
	),
	'yewurenyuanjianyizhi' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanjianyizhi',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议直投金额',
	),
	'yewurenyuanjianyizhib' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanjianyizhib',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议直投期限',
	),
	'fengkongrenyuanjianyfg' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanjianyfg',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议直投金额',
	),
	'fengkongrenyuanjianyk' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanjianyk',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议直投期限',
	),
	'yewurenyuanjianyizon' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanjianyizon',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议总金额',
	),
	'fengkongrenyuanjianyr' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanjianyr',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议总金额',
	),
	'zhudiao' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'zhudiao',
		'type' => 'varchar(80)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '主调',
	),
	'fengkongrenyuan' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuan',
		'type' => 'varchar(80)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员',
	),
	'baozhengjinjianmianl' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'baozhengjinjianmianl',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '保证金减免率',
	),
	'yixiangdanbaofeilv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yixiangdanbaofeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '意向担保费率',
	),
	'touzirennianhuashouy' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'touzirennianhuashouy',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '投资人年化收益率',
	),
	'kehujichuxinyonglian' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'kehujichuxinyonglian',
		'type' => 'decimal(18,2)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '客户基础信用量化',
	),
	'yewurenyuanjianyijie' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanjianyijie',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议借(贷)款金额',
	),
	'yewurenyuanjianyijiet' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'yewurenyuanjianyijiet',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '业务人员建议借(贷)款期限',
	),
	'fengkongrenyuanjianyq' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanjianyq',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议借(贷)款金额',
	),
	'fengkongrenyuanjianyn' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'fengkongrenyuanjianyn',
		'type' => 'int(10)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '风控人员建议借(贷)款期限',
	),
	'chanpinleixing' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'chanpinleixing',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '产品类型',
	),
	'jijianfuwufeilv' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'jijianfuwufeilv',
		'type' => 'decimal(18,6)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '居间服务费率',
	),
	'shifusanchanronghexi' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'shifusanchanronghexi',
		'type' => 'varchar(30)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '是否三产融合项目',
	),
	'bushanghuimiaoshu' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'bushanghuimiaoshu',
		'type' => 'longtext',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '不上会描述',
	),
	'upload64' => array(
		'tablename' => 'mis_auto_sdkln',
		'name' => 'upload64',
		'type' => 'varchar(11)',
		'nullable' => 'YES',
		'default' => NULL,
		'primary' => '',
		'autoinc' => '',
		'comment' => '上传组件_64',
	),
);

?>