<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'1' => array(
		'name' => 'carid',
		'showname' => '车辆名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'carid',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.carid',
		'table' => 'mis_system_car',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'func' => array(
			'1' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'1' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_car',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'fixbegindate',
		'showname' => '送修日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'fixbegindate',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.fixbegindate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'3' => array(
		'name' => 'content',
		'showname' => '维修项目',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.content',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'4' => array(
		'name' => 'repaircompany',
		'showname' => '承修单位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'repaircompany',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.repaircompany',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'5' => array(
		'name' => 'recordsdate',
		'showname' => '登记备案日期',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'recordsdate',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.recordsdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '-1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'recordssigned',
		'showname' => '备案签章人员',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'recordssigned',
		'sortnum' => '7',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.recordssigned',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'status' => '-1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'7' => array(
		'name' => 'employeeid',
		'showname' => '登记人员',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'employeeid',
		'sortnum' => '8',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.employeeid',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'fixenddate',
		'showname' => '取车日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'fixenddate',
		'sortnum' => '9',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.fixenddate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'9' => array(
		'name' => 'fixamount',
		'showname' => '修理费',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'fixamount',
		'sortnum' => '10',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.fixamount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'10' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '11',
		'issearch' => '1',
		'searchField' => 'mis_car_fix.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'46' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '47',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
);

?>