<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-list.inc 配置文件)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2016-09-23 14:11:25
 * @version V1.0
*/
$original = array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'status' => '1',
		'sortname' => 'id',
		'sortnum' => '0',
		'searchField' => 'mis_auto_sdkln.id',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'message' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '单据编号',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '0',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.orderno',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '1',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'xiangmubianhao' => array(
		'name' => 'xiangmubianhao',
		'showname' => '项目编号',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmubianhao',
		'sortnum' => '1',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sdkln.xiangmubianhao',
		'conditions' => '',
		'type' => 'db|xiangmubianma',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'xiangmubianma',
					'3' => 'mis_auto_bklne',
				),
			),
		),
		'table' => 'mis_auto_bklne',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'xiangmubianma',
					'3' => 'mis_auto_bklne',
				),
			),
		),
	),
	'kehumingchen' => array(
		'name' => 'kehumingchen',
		'showname' => '客户名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'kehumingchen',
		'sortnum' => '2',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sdkln.kehumingchen',
		'conditions' => '',
		'type' => 'db|kehumingchen',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'kehumingchen',
					'3' => 'mis_auto_banmo',
				),
			),
		),
		'table' => 'mis_auto_banmo',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'kehumingchen',
					'3' => 'mis_auto_banmo',
				),
			),
		),
	),
	'xiangmumingchen' => array(
		'name' => 'xiangmumingchen',
		'showname' => '项目名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmumingchen',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.xiangmumingchen',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'yewuleixing' => array(
		'name' => 'yewuleixing',
		'showname' => '业务类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewuleixing',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.yewuleixing',
		'conditions' => 'outlinelevel=1',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'table' => 'mis_system_flow_type',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '4',
	),
	'zijinyongtu' => array(
		'name' => 'zijinyongtu',
		'showname' => '资金用途',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zijinyongtu',
		'sortnum' => '5',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.zijinyongtu',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_hgwtp',
				),
			),
		),
		'table' => 'mis_auto_hgwtp',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_hgwtp',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '5',
	),
	'danbaojiekuanleixing' => array(
		'name' => 'danbaojiekuanleixing',
		'showname' => '担保借款类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'danbaojiekuanleixing',
		'sortnum' => '6',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.danbaojiekuanleixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_xacre',
				),
			),
		),
		'table' => 'mis_auto_xacre',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_xacre',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '6',
	),
	'shenqingjine' => array(
		'name' => 'shenqingjine',
		'showname' => '客户申请金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingjine',
		'sortnum' => '7',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.shenqingjine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '7',
	),
	'shenqingqixian' => array(
		'name' => 'shenqingqixian',
		'showname' => '客户申请期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingqixian',
		'sortnum' => '8',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.shenqingqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '8',
	),
	'jianyidanbaofeilv' => array(
		'name' => 'jianyidanbaofeilv',
		'showname' => '建议担保费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyidanbaofeilv',
		'sortnum' => '9',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.jianyidanbaofeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '9',
	),
	'yewurenyuanyijian' => array(
		'name' => 'yewurenyuanyijian',
		'showname' => '业务人员意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanyijian',
		'sortnum' => '10',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.yewurenyuanyijian',
		'conditions' => '',
		'type' => 'select|neibupingshenyijian',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '10',
	),
	'yewurenyuanjianyijin' => array(
		'name' => 'yewurenyuanjianyijin',
		'showname' => '业务人员建议金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyijin',
		'sortnum' => '11',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewurenyuanjianyijin',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '11',
	),
	'yewurenyuanjianyiqix' => array(
		'name' => 'yewurenyuanjianyiqix',
		'showname' => '业务人员建议期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyiqix',
		'sortnum' => '12',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewurenyuanjianyiqix',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '12',
	),
	'yewubuyijian' => array(
		'name' => 'yewubuyijian',
		'showname' => '业务部意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewubuyijian',
		'sortnum' => '13',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.yewubuyijian',
		'conditions' => '',
		'type' => 'select|NBPSYJ',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'NBPSYJ',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'NBPSYJ',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '13',
	),
	'yewubujianyijine' => array(
		'name' => 'yewubujianyijine',
		'showname' => '业务部建议金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewubujianyijine',
		'sortnum' => '14',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewubujianyijine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '14',
	),
	'yewubujianyiqixian' => array(
		'name' => 'yewubujianyiqixian',
		'showname' => '业务部建议期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewubujianyiqixian',
		'sortnum' => '15',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewubujianyiqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '15',
	),
	'fengkongrenyuanyijia' => array(
		'name' => 'fengkongrenyuanyijia',
		'showname' => '风控人员意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanyijia',
		'sortnum' => '16',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanyijia',
		'conditions' => '',
		'type' => 'select|neibupingshenyijian',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '16',
	),
	'fengkongrenyuanjiany' => array(
		'name' => 'fengkongrenyuanjiany',
		'showname' => '风控人员建议金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjiany',
		'sortnum' => '17',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanjiany',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '17',
	),
	'fengkongrenyuanjianyf' => array(
		'name' => 'fengkongrenyuanjianyf',
		'showname' => '风控人员建议期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyf',
		'sortnum' => '18',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanjianyf',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '18',
	),
	'fengkongbuyijian' => array(
		'name' => 'fengkongbuyijian',
		'showname' => '风控部意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongbuyijian',
		'sortnum' => '19',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.fengkongbuyijian',
		'conditions' => '',
		'type' => 'select|NBPSYJ',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'NBPSYJ',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'NBPSYJ',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '19',
	),
	'fengkongbujianyijine' => array(
		'name' => 'fengkongbujianyijine',
		'showname' => '风控部建议金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongbujianyijine',
		'sortnum' => '20',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongbujianyijine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '20',
	),
	'fengkongbujianyiqixi' => array(
		'name' => 'fengkongbujianyiqixi',
		'showname' => '风控部建议期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongbujianyiqixi',
		'sortnum' => '21',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongbujianyiqixi',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '21',
	),
	'shifushanghui' => array(
		'name' => 'shifushanghui',
		'showname' => '是否上会',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifushanghui',
		'sortnum' => '22',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.shifushanghui',
		'conditions' => '',
		'type' => 'select|LD是否',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '22',
	),
	'pingshenjiyaoyinyong' => array(
		'name' => 'pingshenjiyaoyinyong',
		'showname' => '评审纪要引用',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoJwf',
		'sortname' => 'pingshenjiyaoyinyong',
		'sortnum' => '23',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sdkln.pingshenjiyaoyinyong',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_ixwla',
				),
			),
		),
		'table' => 'mis_auto_ixwla',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '23',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_ixwla',
				),
			),
		),
	),
	'bushanghuimiaoshu' => array(
		'name' => 'bushanghuimiaoshu',
		'showname' => '不上会描述',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bushanghuimiaoshu',
		'sortnum' => '24',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'longtext',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_sdkln.bushanghuimiaoshu',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '24',
	),
	'huizongshuoming' => array(
		'name' => 'huizongshuoming',
		'showname' => '评审结果',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'huizongshuoming',
		'sortnum' => '25',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.huizongshuoming',
		'conditions' => '',
		'type' => 'select|AppraisalOpinion',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'AppraisalOpinion',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'AppraisalOpinion',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '25',
	),
	'pingshenjine' => array(
		'name' => 'pingshenjine',
		'showname' => '评审金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenjine',
		'sortnum' => '26',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.pingshenjine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '26',
	),
	'pingshenqixian' => array(
		'name' => 'pingshenqixian',
		'showname' => '评审期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenqixian',
		'sortnum' => '27',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.pingshenqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '27',
	),
	'baozhengjinlv' => array(
		'name' => 'baozhengjinlv',
		'showname' => '保证金减免率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'baozhengjinlv',
		'sortnum' => '28',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.baozhengjinlv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '28',
	),
	'danbaofeilv' => array(
		'name' => 'danbaofeilv',
		'showname' => '担保费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'danbaofeilv',
		'sortnum' => '29',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.danbaofeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '29',
	),
	'shifufuyixiangmu' => array(
		'name' => 'shifufuyixiangmu',
		'showname' => '是否复议项目',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifufuyixiangmu',
		'sortnum' => '30',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.shifufuyixiangmu',
		'conditions' => '',
		'type' => 'select|LD是否',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '30',
	),
	'weidaifeilv' => array(
		'name' => 'weidaifeilv',
		'showname' => '委贷费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'weidaifeilv',
		'sortnum' => '31',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.weidaifeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'bfz',
					'2' => 'bfz',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'bfz',
					'2' => 'bfz',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '31',
	),
	'jiekuanzhuti' => array(
		'name' => 'jiekuanzhuti',
		'showname' => '借款主体',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemCompany',
		'sortname' => 'jiekuanzhuti',
		'sortnum' => '32',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'id',
		'fieldtype' => 'int',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sdkln.jiekuanzhuti',
		'conditions' => '',
		'type' => 'db|name',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_company',
				),
			),
		),
		'table' => 'mis_system_company',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '32',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_company',
				),
			),
		),
	),
	'pingshenhuiyijiyaona' => array(
		'name' => 'pingshenhuiyijiyaona',
		'showname' => '业务内部评审会决议',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenhuiyijiyaona',
		'sortnum' => '33',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_sdkln.pingshenhuiyijiyaona',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '33',
	),
	'pingshenhuibeizhu' => array(
		'name' => 'pingshenhuibeizhu',
		'showname' => '评审会备注',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenhuibeizhu',
		'sortnum' => '34',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'longtext',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_sdkln.pingshenhuibeizhu',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '34',
	),
	'pingshenfujian' => array(
		'name' => 'pingshenfujian',
		'showname' => '评审会附件',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenfujian',
		'sortnum' => '35',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'upload',
		'searchField' => 'mis_auto_sdkln.pingshenfujian',
		'conditions' => '',
		'type' => 'upload',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
	),
	'pingshenleixing' => array(
		'name' => 'pingshenleixing',
		'showname' => '评审类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenleixing',
		'sortnum' => '36',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.pingshenleixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_fwvvg',
				),
			),
		),
		'table' => 'mis_auto_fwvvg',
		'field' => 'id',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_fwvvg',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '36',
	),
	'pingshenmoshi' => array(
		'name' => 'pingshenmoshi',
		'showname' => '评审模式',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenmoshi',
		'sortnum' => '37',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.pingshenmoshi',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_svsxe',
				),
			),
		),
		'table' => 'mis_auto_svsxe',
		'field' => 'id',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_svsxe',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '37',
	),
	'datatable23' => array(
		'name' => 'datatable23',
		'showname' => '评审明细',
		'widths' => NULL,
		'sorts' => '0',
		'models' => '',
		'sortname' => 'datatable23',
		'sortnum' => '38',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'datatable',
		'searchField' => 'mis_auto_sdkln.datatable23',
		'conditions' => '',
		'type' => 'datatable',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'shanghuishijian' => array(
		'name' => 'shanghuishijian',
		'showname' => '上会时间',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shanghuishijian',
		'sortnum' => '39',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_sdkln.shanghuishijian',
		'conditions' => '',
		'type' => 'time',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '39',
		'unfunc' => array(
			'0' => array(
				'0' => 'untransTime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
	),
	'zhaojidanhao' => array(
		'name' => 'zhaojidanhao',
		'showname' => '召集单号',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoVph',
		'sortname' => 'zhaojidanhao',
		'sortnum' => '40',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sdkln.zhaojidanhao',
		'conditions' => '',
		'type' => 'db|orderno',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_fuhhu',
				),
			),
		),
		'table' => 'mis_auto_fuhhu',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '40',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'orderno',
					'3' => 'mis_auto_fuhhu',
				),
			),
		),
	),
	'zhudiao' => array(
		'name' => 'zhudiao',
		'showname' => '主调',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'sortname' => 'zhudiao',
		'sortnum' => '41',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'id',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sdkln.zhudiao',
		'conditions' => '',
		'type' => 'db|name',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '41',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
	),
	'fengkongrenyuan' => array(
		'name' => 'fengkongrenyuan',
		'showname' => '风控人员',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'sortname' => 'fengkongrenyuan',
		'sortnum' => '42',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'id',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuan',
		'conditions' => '',
		'type' => 'db|name',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '42',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
	),
	'baozhengjinjianmianl' => array(
		'name' => 'baozhengjinjianmianl',
		'showname' => '保证金减免率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'baozhengjinjianmianl',
		'sortnum' => '43',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.baozhengjinjianmianl',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '43',
	),
	'yixiangdanbaofeilv' => array(
		'name' => 'yixiangdanbaofeilv',
		'showname' => '意向担保费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yixiangdanbaofeilv',
		'sortnum' => '44',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yixiangdanbaofeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '44',
	),
	'touzirennianhuashouy' => array(
		'name' => 'touzirennianhuashouy',
		'showname' => '投资人年化收益率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'touzirennianhuashouy',
		'sortnum' => '45',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.touzirennianhuashouy',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '45',
	),
	'kehujichuxinyonglian' => array(
		'name' => 'kehujichuxinyonglian',
		'showname' => '客户基础信用量化',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'kehujichuxinyonglian',
		'sortnum' => '46',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.kehujichuxinyonglian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '46',
	),
	'yewurenyuanjianyijie' => array(
		'name' => 'yewurenyuanjianyijie',
		'showname' => '业务人员建议借(贷)款金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyijie',
		'sortnum' => '47',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewurenyuanjianyijie',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '47',
	),
	'yewurenyuanjianyijiet' => array(
		'name' => 'yewurenyuanjianyijiet',
		'showname' => '业务人员建议借(贷)款期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyijiet',
		'sortnum' => '48',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewurenyuanjianyijiet',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '48',
	),
	'fengkongrenyuanjianyq' => array(
		'name' => 'fengkongrenyuanjianyq',
		'showname' => '风控人员建议借(贷)款金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyq',
		'sortnum' => '49',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanjianyq',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '49',
	),
	'fengkongrenyuanjianyn' => array(
		'name' => 'fengkongrenyuanjianyn',
		'showname' => '风控人员建议借(贷)款期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyn',
		'sortnum' => '50',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanjianyn',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '50',
	),
	'yewurenyuanjianyizhi' => array(
		'name' => 'yewurenyuanjianyizhi',
		'showname' => '业务人员建议直投金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyizhi',
		'sortnum' => '51',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewurenyuanjianyizhi',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '51',
	),
	'yewurenyuanjianyizhib' => array(
		'name' => 'yewurenyuanjianyizhib',
		'showname' => '业务人员建议直投期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyizhib',
		'sortnum' => '52',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewurenyuanjianyizhib',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '52',
	),
	'fengkongrenyuanjianyfg' => array(
		'name' => 'fengkongrenyuanjianyfg',
		'showname' => '风控人员建议直投金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyfg',
		'sortnum' => '53',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanjianyfg',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '53',
	),
	'fengkongrenyuanjianyk' => array(
		'name' => 'fengkongrenyuanjianyk',
		'showname' => '风控人员建议直投期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyk',
		'sortnum' => '54',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanjianyk',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '54',
	),
	'yewurenyuanjianyizon' => array(
		'name' => 'yewurenyuanjianyizon',
		'showname' => '业务人员建议总金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyizon',
		'sortnum' => '55',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.yewurenyuanjianyizon',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '55',
	),
	'fengkongrenyuanjianyr' => array(
		'name' => 'fengkongrenyuanjianyr',
		'showname' => '风控人员建议总金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyr',
		'sortnum' => '56',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.fengkongrenyuanjianyr',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '56',
	),
	'chanpinleixing' => array(
		'name' => 'chanpinleixing',
		'showname' => '产品类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chanpinleixing',
		'sortnum' => '57',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.chanpinleixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dxmel',
				),
			),
		),
		'table' => 'mis_auto_dxmel',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dxmel',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '57',
	),
	'jijianfuwufeilv' => array(
		'name' => 'jijianfuwufeilv',
		'showname' => '居间服务费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jijianfuwufeilv',
		'sortnum' => '58',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_sdkln.jijianfuwufeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '58',
	),
	'shifusanchanronghexi' => array(
		'name' => 'shifusanchanronghexi',
		'showname' => '是否三产融合项目',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifusanchanronghexi',
		'sortnum' => '59',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_sdkln.shifusanchanronghexi',
		'conditions' => '',
		'type' => 'select|LD是否',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '59',
	),
	'upload64' => array(
		'name' => 'upload64',
		'showname' => '上传附件',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'upload64',
		'sortnum' => '60',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'upload',
		'searchField' => 'mis_auto_sdkln.upload64',
		'conditions' => '',
		'type' => 'upload',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
	),
	'action' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '63',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'operateid' => array(
		'name' => 'operateid',
		'showname' => '是否确认',
		'rules' => '1',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'operateidVal',
					'1' => '###',
				),
			),
		),
		'sortname' => 'operateid',
		'sortnum' => '64',
		'searchField' => 'mis_auto_sdkln.operateid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'companyid' => array(
		'name' => 'companyid',
		'showname' => '公司',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemCompany',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
		'sortname' => 'companyid',
		'sortnum' => '65',
		'issearch' => '1',
		'table' => 'mis_system_company',
		'searchField' => 'mis_auto_sdkln.companyid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
	),
	'projectid' => array(
		'name' => 'projectid',
		'showname' => '项目ID',
		'rules' => '0',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectid',
		'sortnum' => '66',
		'searchField' => 'mis_auto_sdkln.projectid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'createid' => array(
		'name' => 'createid',
		'rules' => '1',
		'showname' => '创建人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'sortname' => 'createid',
		'issearch' => '1',
		'table' => 'user',
		'sortnum' => '67',
		'searchField' => 'mis_auto_sdkln.createid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
	),
	'createtime' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '68',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_sdkln.createtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'helpvalue' => '',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'untranstime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
);

$extedsList = require 'listExtend.inc.php';
return array_merge($original , $extedsList);
?>