<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-list.inc 配置文件)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2016-08-24 11:08:06
 * @version V1.0
*/
$original = array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'status' => '1',
		'sortname' => 'id',
		'sortnum' => '0',
		'searchField' => 'mis_auto_njzcw.id',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'message' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '表决编号',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '0',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.orderno',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '1',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'xiangmubianma' => array(
		'name' => 'xiangmubianma',
		'showname' => '项目编码',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmubianma',
		'sortnum' => '1',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.xiangmubianma',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
	),
	'kehumingchen' => array(
		'name' => 'kehumingchen',
		'showname' => '客户名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'kehumingchen',
		'sortnum' => '2',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.kehumingchen',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'kehumingchen',
					'3' => 'mis_auto_banmo',
				),
			),
		),
		'table' => 'mis_auto_banmo',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'kehumingchen',
					'3' => 'mis_auto_banmo',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '2',
	),
	'xiangmumingchen' => array(
		'name' => 'xiangmumingchen',
		'showname' => '项目名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmumingchen',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.xiangmumingchen',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'yewuleixing' => array(
		'name' => 'yewuleixing',
		'showname' => '业务类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewuleixing',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.yewuleixing',
		'conditions' => 'outlinelevel=1',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'table' => 'mis_system_flow_type',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '4',
	),
	'zijinyongtu' => array(
		'name' => 'zijinyongtu',
		'showname' => '资金用途',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zijinyongtu',
		'sortnum' => '5',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.zijinyongtu',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_hgwtp',
				),
			),
		),
		'table' => 'mis_auto_hgwtp',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_hgwtp',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '5',
	),
	'shenqingjine' => array(
		'name' => 'shenqingjine',
		'showname' => '客户申请金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingjine',
		'sortnum' => '6',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.shenqingjine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
	),
	'shenqingqixian' => array(
		'name' => 'shenqingqixian',
		'showname' => '客户申请期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingqixian',
		'sortnum' => '7',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.shenqingqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'month',
					'2' => 'month',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'month',
					'2' => 'month',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '7',
	),
	'danbaojiekuanleixing' => array(
		'name' => 'danbaojiekuanleixing',
		'showname' => '担保借款类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'danbaojiekuanleixing',
		'sortnum' => '8',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.danbaojiekuanleixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_xacre',
				),
			),
		),
		'table' => 'mis_auto_xacre',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_xacre',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '8',
	),
	'yixiangdanbaofeilv' => array(
		'name' => 'yixiangdanbaofeilv',
		'showname' => '意向担保费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yixiangdanbaofeilv',
		'sortnum' => '9',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.yixiangdanbaofeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '9',
	),
	'baozhengjinjianmianl' => array(
		'name' => 'baozhengjinjianmianl',
		'showname' => '保证金减免率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'baozhengjinjianmianl',
		'sortnum' => '10',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.baozhengjinjianmianl',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '10',
	),
	'kehujichuxinyonglian' => array(
		'name' => 'kehujichuxinyonglian',
		'showname' => '客户基础信用量化',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'kehujichuxinyonglian',
		'sortnum' => '11',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.kehujichuxinyonglian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'mm',
					'2' => 'mm',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'mm',
					'2' => 'mm',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '11',
	),
	'chanpinleixing' => array(
		'name' => 'chanpinleixing',
		'showname' => '产品类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chanpinleixing',
		'sortnum' => '12',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.chanpinleixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dxmel',
				),
			),
		),
		'table' => 'mis_auto_dxmel',
		'field' => 'orderno',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_auto_dxmel',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '12',
	),
	'yewurenyuanyijian' => array(
		'name' => 'yewurenyuanyijian',
		'showname' => '业务人员意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanyijian',
		'sortnum' => '13',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.yewurenyuanyijian',
		'conditions' => '',
		'type' => 'select|neibupingshenyijian',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '13',
	),
	'yewurenyuanjianyijie' => array(
		'name' => 'yewurenyuanjianyijie',
		'showname' => '业务人员建议借(贷)款金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyijie',
		'sortnum' => '14',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.yewurenyuanjianyijie',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '14',
	),
	'yewurenyuanjianyijier' => array(
		'name' => 'yewurenyuanjianyijier',
		'showname' => '业务人员建议借(贷)款期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyijier',
		'sortnum' => '15',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.yewurenyuanjianyijier',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '15',
	),
	'yewurenyuanjianyizhi' => array(
		'name' => 'yewurenyuanjianyizhi',
		'showname' => '业务人员建议直投金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyizhi',
		'sortnum' => '16',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.yewurenyuanjianyizhi',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '16',
	),
	'yewurenyuanjianyizhiy' => array(
		'name' => 'yewurenyuanjianyizhiy',
		'showname' => '业务人员建议直投期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyizhiy',
		'sortnum' => '17',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.yewurenyuanjianyizhiy',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '17',
	),
	'yewurenyuanjianyizon' => array(
		'name' => 'yewurenyuanjianyizon',
		'showname' => '业务人员建议总金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yewurenyuanjianyizon',
		'sortnum' => '18',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.yewurenyuanjianyizon',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '18',
	),
	'fengkongrenyuanyijia' => array(
		'name' => 'fengkongrenyuanyijia',
		'showname' => '风控人员意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanyijia',
		'sortnum' => '19',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.fengkongrenyuanyijia',
		'conditions' => '',
		'type' => 'select|neibupingshenyijian',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'neibupingshenyijian',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '19',
	),
	'fengkongrenyuanjiany' => array(
		'name' => 'fengkongrenyuanjiany',
		'showname' => '风控人员建议借(贷)款金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjiany',
		'sortnum' => '20',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.fengkongrenyuanjiany',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '20',
	),
	'fengkongrenyuanjianye' => array(
		'name' => 'fengkongrenyuanjianye',
		'showname' => '风控人员建议借(贷)款期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianye',
		'sortnum' => '21',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.fengkongrenyuanjianye',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '21',
	),
	'fengkongrenyuanjianyg' => array(
		'name' => 'fengkongrenyuanjianyg',
		'showname' => '风控人员建议直投金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyg',
		'sortnum' => '22',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.fengkongrenyuanjianyg',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '22',
	),
	'fengkongrenyuanjianyi' => array(
		'name' => 'fengkongrenyuanjianyi',
		'showname' => '风控人员建议直投期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyi',
		'sortnum' => '23',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.fengkongrenyuanjianyi',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'months',
					'2' => 'months',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '23',
	),
	'fengkongrenyuanjianyk' => array(
		'name' => 'fengkongrenyuanjianyk',
		'showname' => '风控人员建议总金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengkongrenyuanjianyk',
		'sortnum' => '24',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.fengkongrenyuanjianyk',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '24',
	),
	'shifusanchanronghexi' => array(
		'name' => 'shifusanchanronghexi',
		'showname' => '是否三产融合项目',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifusanchanronghexi',
		'sortnum' => '25',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.shifusanchanronghexi',
		'conditions' => '',
		'type' => 'select|LD是否',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'LD是否',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '25',
	),
	'pingshenyijian' => array(
		'name' => 'pingshenyijian',
		'showname' => '评审意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenyijian',
		'sortnum' => '26',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.pingshenyijian',
		'conditions' => '',
		'type' => 'select|AppraisalOpinion',
		'validate' => NULL,
		'unique' => '0',
		'required' => '1',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'AppraisalOpinion',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'AppraisalOpinion',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '26',
	),
	'jianyijine' => array(
		'name' => 'jianyijine',
		'showname' => '建议借(贷)款金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyijine',
		'sortnum' => '27',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.jianyijine',
		'conditions' => '',
		'type' => 'text',
		'validate' => 'double',
		'unique' => '0',
		'required' => '1',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '27',
	),
	'jianyiqixian' => array(
		'name' => 'jianyiqixian',
		'showname' => '建议借(贷)款期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyiqixian',
		'sortnum' => '28',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.jianyiqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => 'double',
		'unique' => '0',
		'required' => '1',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'month',
					'2' => 'month',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'month',
					'2' => 'month',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '28',
	),
	'zhitoujine' => array(
		'name' => 'zhitoujine',
		'showname' => '直投金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhitoujine',
		'sortnum' => '29',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.zhitoujine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '29',
	),
	'zhitouqixian' => array(
		'name' => 'zhitouqixian',
		'showname' => '直投期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhitouqixian',
		'sortnum' => '30',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.zhitouqixian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'month',
					'2' => 'month',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'month',
					'2' => 'month',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '30',
	),
	'rugubili' => array(
		'name' => 'rugubili',
		'showname' => '入股比例',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'rugubili',
		'sortnum' => '31',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.rugubili',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '31',
	),
	'jianyizongjine' => array(
		'name' => 'jianyizongjine',
		'showname' => '建议总金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyizongjine',
		'sortnum' => '32',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.jianyizongjine',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '32',
	),
	'peiyumubiao' => array(
		'name' => 'peiyumubiao',
		'showname' => '培育目标',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'peiyumubiao',
		'sortnum' => '33',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_njzcw.peiyumubiao',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '33',
	),
	'jianyi' => array(
		'name' => 'jianyi',
		'showname' => '评审表决理由及建议',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyi',
		'sortnum' => '34',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_njzcw.jianyi',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '34',
	),
	'fengxiandingjiayijia' => array(
		'name' => 'fengxiandingjiayijia',
		'showname' => '风险定价意见',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengxiandingjiayijia',
		'sortnum' => '35',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.fengxiandingjiayijia',
		'conditions' => '',
		'type' => 'select|AppraisalOpinion',
		'validate' => NULL,
		'unique' => '0',
		'required' => '1',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'AppraisalOpinion',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'AppraisalOpinion',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '35',
	),
	'shouqubaozhengjinbil' => array(
		'name' => 'shouqubaozhengjinbil',
		'showname' => '保证金减免率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shouqubaozhengjinbil',
		'sortnum' => '36',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.shouqubaozhengjinbil',
		'conditions' => '',
		'type' => 'text',
		'validate' => 'double',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '36',
	),
	'jianyidanbaolv' => array(
		'name' => 'jianyidanbaolv',
		'showname' => '建议担保/委贷费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyidanbaolv',
		'sortnum' => '37',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.jianyidanbaolv',
		'conditions' => '',
		'type' => 'text',
		'validate' => 'double',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '37',
	),
	'jianyiweidaifeilv' => array(
		'name' => 'jianyiweidaifeilv',
		'showname' => '建议委贷费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jianyiweidaifeilv',
		'sortnum' => '38',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.jianyiweidaifeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '38',
	),
	'touzirennianhuashouy' => array(
		'name' => 'touzirennianhuashouy',
		'showname' => '投资人年化收益率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'touzirennianhuashouy',
		'sortnum' => '39',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.touzirennianhuashouy',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '39',
	),
	'jijianfuwufeilv' => array(
		'name' => 'jijianfuwufeilv',
		'showname' => '居间服务费率',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'jijianfuwufeilv',
		'sortnum' => '40',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.jijianfuwufeilv',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '3',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'percent',
					'2' => 'percent',
					'3' => '1',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '40',
	),
	'fengxiandingjialiyou' => array(
		'name' => 'fengxiandingjialiyou',
		'showname' => '风险定价理由及建议',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fengxiandingjialiyou',
		'sortnum' => '41',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'text',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_njzcw.fengxiandingjialiyou',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '41',
	),
	'xiangmuxinxiwai' => array(
		'name' => 'xiangmuxinxiwai',
		'showname' => '项目信息(外)',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoVrr',
		'sortname' => 'xiangmuxinxiwai',
		'sortnum' => '42',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'xiangmubianma',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_njzcw.xiangmuxinxiwai',
		'conditions' => '',
		'type' => 'db|xiangmubianma',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'xiangmubianma',
					'2' => 'xiangmubianma',
					'3' => 'mis_auto_bwkxf',
				),
			),
		),
		'table' => 'mis_auto_bwkxf',
		'field' => 'xiangmubianma',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '42',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'xiangmubianma',
					'2' => 'xiangmubianma',
					'3' => 'mis_auto_bwkxf',
				),
			),
		),
	),
	'xiangmuxinxina' => array(
		'name' => 'xiangmuxinxina',
		'showname' => '项目信息(内）',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisAutoPvb',
		'sortname' => 'xiangmuxinxina',
		'sortnum' => '43',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_njzcw.xiangmuxinxina',
		'conditions' => '',
		'type' => 'db|xiangmubianma',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'xiangmubianma',
					'3' => 'mis_auto_bklne',
				),
			),
		),
		'table' => 'mis_auto_bklne',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '43',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'xiangmubianma',
					'3' => 'mis_auto_bklne',
				),
			),
		),
	),
	'pingshenhuiid' => array(
		'name' => 'pingshenhuiid',
		'showname' => '评审会id',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenhuiid',
		'sortnum' => '44',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_njzcw.pingshenhuiid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'zhaojidanid' => array(
		'name' => 'zhaojidanid',
		'showname' => '召集单id',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhaojidanid',
		'sortnum' => '45',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_njzcw.zhaojidanid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'zhaojidansubid' => array(
		'name' => 'zhaojidansubid',
		'showname' => '召集单subid',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhaojidansubid',
		'sortnum' => '46',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_njzcw.zhaojidansubid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'shifunabu' => array(
		'name' => 'shifunabu',
		'showname' => '是否内部',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifunabu',
		'sortnum' => '47',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_njzcw.shifunabu',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'pingshenhuileixing' => array(
		'name' => 'pingshenhuileixing',
		'showname' => '评审会类型',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pingshenhuileixing',
		'sortnum' => '48',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.pingshenhuileixing',
		'conditions' => '',
		'type' => 'group',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_fwvvg',
				),
			),
		),
		'table' => 'mis_auto_fwvvg',
		'field' => 'id',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_fwvvg',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '48',
	),
	'shifuzhuanjia' => array(
		'name' => 'shifuzhuanjia',
		'showname' => '是否专家',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifuzhuanjia',
		'sortnum' => '49',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.shifuzhuanjia',
		'conditions' => '',
		'type' => 'select|ExpertOrInsider',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'ExpertOrInsider',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'ExpertOrInsider',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '49',
	),
	'biaojueriqi' => array(
		'name' => 'biaojueriqi',
		'showname' => '表决日期',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'biaojueriqi',
		'sortnum' => '50',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_njzcw.biaojueriqi',
		'conditions' => '',
		'type' => 'time',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '50',
		'unfunc' => array(
			'0' => array(
				'0' => 'untransTime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d',
				),
			),
		),
	),
	'shanghuishunxu' => array(
		'name' => 'shanghuishunxu',
		'showname' => '上会顺序',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shanghuishunxu',
		'sortnum' => '51',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.shanghuishunxu',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '51',
	),
	'zhudiao' => array(
		'name' => 'zhudiao',
		'showname' => '主调',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'sortname' => 'zhudiao',
		'sortnum' => '52',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'id',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_njzcw.zhudiao',
		'conditions' => '',
		'type' => 'db|name',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '52',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
	),
	'fengkongrenyuan' => array(
		'name' => 'fengkongrenyuan',
		'showname' => '风控人员',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'sortname' => 'fengkongrenyuan',
		'sortnum' => '53',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'id',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_njzcw.fengkongrenyuan',
		'conditions' => '',
		'type' => 'db|name',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '53',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
	),
	'shifuduixiangmurenyu' => array(
		'name' => 'shifuduixiangmurenyu',
		'showname' => '是否对项目人员评分',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shifuduixiangmurenyu',
		'sortnum' => '54',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_njzcw.shifuduixiangmurenyu',
		'conditions' => '',
		'type' => 'select|YesOrNo',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'YesOrNo',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'YesOrNo',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '54',
	),
	'action' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '57',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'operateid' => array(
		'name' => 'operateid',
		'showname' => '是否确认',
		'rules' => '1',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'operateidVal',
					'1' => '###',
				),
			),
		),
		'sortname' => 'operateid',
		'sortnum' => '58',
		'searchField' => 'mis_auto_njzcw.operateid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'companyid' => array(
		'name' => 'companyid',
		'showname' => '公司',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemCompany',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
		'sortname' => 'companyid',
		'sortnum' => '59',
		'issearch' => '1',
		'table' => 'mis_system_company',
		'searchField' => 'mis_auto_njzcw.companyid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
	),
	'projectid' => array(
		'name' => 'projectid',
		'showname' => '项目ID',
		'rules' => '0',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectid',
		'sortnum' => '60',
		'searchField' => 'mis_auto_njzcw.projectid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'createid' => array(
		'name' => 'createid',
		'rules' => '1',
		'showname' => '创建人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'sortname' => 'createid',
		'issearch' => '1',
		'table' => 'user',
		'sortnum' => '61',
		'searchField' => 'mis_auto_njzcw.createid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
	),
	'createtime' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '62',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_njzcw.createtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'helpvalue' => '',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'untranstime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
);

$extedsList = require 'listExtend.inc.php';
return array_merge($original , $extedsList);
?>