<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'1' => array(
		'name' => 'carid',
		'showname' => '车辆名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'carid',
		'sortnum' => '2',
		'extention_html_end' => array(
			'0' => '-',
		),
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
			'1' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'carno',
					'3' => 'mis_system_car',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_car',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_car_traffic_penalty.carid',
		'table' => 'mis_system_car',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'user_id',
		'showname' => '驾驶人员',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'user_id',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_car_traffic_penalty.user_id',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db|name',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'3' => array(
		'name' => 'get_time',
		'showname' => '违章时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'get_time',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'date',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'Y-m-d',
					'1' => '###',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_car_traffic_penalty.get_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'4' => array(
		'name' => 'content',
		'showname' => '违章明细',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_car_traffic_penalty.content',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'5' => array(
		'name' => 'penalty',
		'showname' => '罚款金额',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'penalty',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_car_traffic_penalty.penalty',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'point',
		'showname' => '扣分',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'point',
		'sortnum' => '7',
		'issearch' => '1',
		'searchField' => 'mis_car_traffic_penalty.point',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'7' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '8',
		'issearch' => '0',
		'searchField' => 'mis_car_traffic_penalty.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '-1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'createid',
		'showname' => '制单人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '9',
		'issearch' => '1',
		'searchField' => 'mis_car_traffic_penalty.createid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'9' => array(
		'name' => 'createtime',
		'showname' => '制单时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '10',
		'issearch' => '1',
		'searchField' => 'mis_car_traffic_penalty.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'46' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '47',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
);

?>