<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'isexport' => '1',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'title',
		'showname' => '标题',
		'shows' => '1',
		'isexport' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'code',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_knowledge_list.title',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'helpvalue' => '',
	),
	'3' => array(
		'name' => 'categoryid',
		'showname' => '分类名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'categoryid',
		'isexport' => '1',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_knowledge_type',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_knowledge_list.categoryid',
		'table' => 'mis_knowledge_type',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'levels',
		'showname' => '等级',
		'isexport' => '1',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'levels',
		'sortnum' => '4',
		'issearch' => '0',
		'searchField' => 'mis_knowledge_levels_visibility.levels',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'title',
					'3' => 'mis_knowledge_levels_visibility',
				),
			),
		),
	),
	'4' => array(
		'name' => 'createtime',
		'showname' => '发布时间',
		'isexport' => '1',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'timeDiff',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'searchField' => 'mis_knowledge_list.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'createid',
		'showname' => '发布人',
		'shows' => '1',
		'isexport' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '9',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_knowledge_list.createid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'widths' => '',
		'isexport' => '0',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'sortnum' => '10',
		'issearch' => '0',
		'searchField' => 'mis_knowledge_list.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'status' => '1',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'isexport' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '11',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '文章',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'auth_dutyid',
		'showname' => '职级',
		'shows' => '1',
		'isexport' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auth_dutyid',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_knowledge_list.auth_dutyid',
		'table' => 'mis_system_duty',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '10',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => 'id',
					'2' => 'duty_id',
					'3' => 'user',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_duty',
				),
			),
		),
	),
	'10' => array(
		'name' => 'auth_deptid',
		'showname' => '部门',
		'shows' => '1',
		'isexport' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auth_deptid',
		'sortnum' => '7',
		'issearch' => '1',
		'searchField' => 'mis_knowledge_list.auth_deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => 'id',
					'2' => 'dept_id',
					'3' => 'user',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
	),
	'11' => array(
		'name' => 'score',
		'showname' => '分数',
		'isexport' => '1',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'score',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_knowledge_levels_visibility.score',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#levels#',
					'1' => 'id',
					'2' => 'score',
					'3' => 'mis_knowledge_levels_visibility',
				),
			),
		),
	),
);

?>