<?php 
return array(
	'19' => array(
		'name' => 'createid',
		'showname' => '制单人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_sale_business_check.createid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '19',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'bid',
		'showname' => '商机',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bid',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_sale_business_check.bid',
		'table' => 'mis_sale_business',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'clientname',
					'3' => 'mis_sale_business',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'20' => array(
		'name' => 'createtime',
		'showname' => '制单时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_sale_business_check.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '1',
		'searchsortnum' => '20',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'5' => array(
		'name' => 'controller',
		'showname' => '实际控制人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'controller',
		'sortnum' => '4',
		'issearch' => '0',
		'searchField' => 'mis_sale_business.controller',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '申请单号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_sale_business_check.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '6',
		'issearch' => '0',
		'isearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'mobile',
		'showname' => '电话',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mobile',
		'sortnum' => '7',
		'issearch' => '0',
		'searchField' => 'mis_sale_business.mobile',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'sourceid',
		'showname' => '来源',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sourceid',
		'sortnum' => '8',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.sourceid',
		'table' => 'mis_sale_business_source',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_business_source',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'7' => array(
		'name' => 'intentiontypesid',
		'showname' => '业务类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'intentiontypesid',
		'sortnum' => '9',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.intentiontypesid',
		'table' => 'mis_system_flow_type',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
	),
	'3' => array(
		'name' => 'areaid',
		'showname' => '区域',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'areaid',
		'sortnum' => '10',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.areaid',
		'table' => 'mis_sales_site',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '15',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sales_site',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'14' => array(
		'name' => 'useexplain',
		'showname' => '转储备说明',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'useexplain',
		'sortnum' => '14',
		'issearch' => '1',
		'searchField' => 'mis_finance_borrowmas.useexplain',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '16',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'17' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'sortnum' => '15',
		'issearch' => '1',
		'searchField' => 'mis_sale_business_check.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '17',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'18' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '16',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '借款申请',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'21' => array(
		'name' => 'customertypeid',
		'showname' => '客户主体',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'customertypeid',
		'sortnum' => '11',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.customertypeid',
		'table' => 'mis_sale_client_type',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '22',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_client_type',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'22' => array(
		'name' => 'professionid',
		'showname' => '行业',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'professionid',
		'sortnum' => '12',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.professionid',
		'table' => 'mis_sale_profession',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '23',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_profession',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'23' => array(
		'name' => 'industryid',
		'showname' => '产业链',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'industryid',
		'sortnum' => '13',
		'issearch' => '1',
		'searchField' => 'mis_sale_business.industryid',
		'table' => 'mis_sale_industry',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '24',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_industry',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
	'upload' => array(
			'name' => 'upload',
			'showname' => '附件上传',
			'shows' => '0',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'upload',
			'sortnum' => '17',
			'fieldtype' => 'varchar',
			'fieldcategory' => 'upload',
			'searchField' => 'mis_sale_business_check.upload',
			'conditions' => '',
			'type' => 'upload',
			'ischosice' => '1',
	),
);

?>