<?php 
return array(
	'2' => array(
		'name' => 'orderno',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_sale_client_type.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'helpvalue' => '',
	),
	'0' => array(
		'name' => 'name',
		'showname' => '主体类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '2',
		'searchField' => 'mis_sale_client_type.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'table' => '',
		'field' => '',
	),
	'1' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '3',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'3' => array(
			'name' => 'remark',
			'showname' => '备注',
			'shows' => '0',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'remark',
			'sortnum' => '4',
			'searchField' => 'mis_sale_client_type.remark',
			'conditions' => '',
			'type' => 'text',
			'issearch' => '0',
			'isallsearch' => '0',
			'searchsortnum' => '2',
			'helpvalue' => '',
			'table' => '',
			'field' => '',
			'status' => '1',
			'rules' => '0',
			'message' => '0',
	),
		'4' => array(
				'name' => 'actionname',
				'showname' => '主体模块',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'actionname',
				'sortnum' => '5',
				'searchField' => 'mis_sale_client_type.actionname',
				'conditions' => '',
				'type' => 'text',
				'issearch' => '0',
				'isallsearch' => '0',
				'searchsortnum' => '2',
				'helpvalue' => '',
				'table' => '',
				'field' => '',
				'status' => '1',
				'rules' => '0',
				'message' => '0',
		),
);

?>