<?php 
return array(
	'xiangmubianma' => array(
		'name' => 'xiangmubianma',
		'showname' => '项目编码',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmubianma',
		'sortnum' => '1',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_fuhhu_sub_datatable5.xiangmubianma',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'table' => 'mis_auto_fuhhu_sub_datatable5',
		'field' => 'xiangmubianma',
		'helpvalue' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'kehumingchen' => array(
		'name' => 'kehumingchen',
		'showname' => '客户名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'kehumingchen',
		'sortnum' => '2',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_fuhhu_sub_datatable5.kehumingchen',
		'conditions' => '',
		'type' => 'group',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'kehumingchen',
					'3' => 'mis_auto_banmo',
				),
			),
		),
		'table' => 'mis_auto_banmo',
		'field' => 'orderno',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'helpvalue' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'xiangmumingchen' => array(
		'name' => 'xiangmumingchen',
		'showname' => '项目名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'xiangmumingchen',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_fuhhu_sub_datatable5.xiangmumingchen',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'table' => 'mis_auto_fuhhu_sub_datatable5',
		'field' => 'xiangmumingchen',
		'helpvalue' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'shenqingjine' => array(
		'name' => 'shenqingjine',
		'showname' => '客户申请金额',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingjine',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_fuhhu_sub_datatable5.shenqingjine',
		'conditions' => '',
		'type' => 'text',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'yuan',
					'2' => 'wan',
					'3' => '3',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'table' => 'mis_auto_fuhhu_sub_datatable5',
		'field' => 'shenqingjine',
		'helpvalue' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'shenqingqixian' => array(
		'name' => 'shenqingqixian',
		'showname' => '客户申请期限',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shenqingqixian',
		'sortnum' => '5',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_fuhhu_sub_datatable5.shenqingqixian',
		'conditions' => '',
		'type' => 'text',
		'func' => array(
			'0' => array(
				'0' => 'unitExchange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'month',
					'2' => 'month',
					'3' => '3',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '7',
		'table' => 'mis_auto_fuhhu_sub_datatable5',
		'field' => 'shenqingqixian',
		'helpvalue' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'companyid' => array(
		'name' => 'companyid',
		'showname' => '公司',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemCompany',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
		'sortname' => 'companyid',
		'sortnum' => '6',
		'issearch' => '1',
		'table' => 'mis_system_company',
		'searchField' => 'mis_auto_fuhhu.companyid',
		'field' => 'companyid',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'createid' => array(
		'name' => 'createid',
		'rules' => '1',
		'showname' => '创建人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'sortname' => 'createid',
		'issearch' => '1',
		'table' => 'user',
		'sortnum' => '7',
		'searchField' => 'mis_auto_fuhhu.createid',
		'field' => 'createid',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'createtime' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '8',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_fuhhu.createtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'helpvalue' => '',
		'sortsorder' => '0',
		'sortstype' => 'asc',
	),
	'shanghuishunxu' => array(
		'name' => 'shanghuishunxu',
		'showname' => '上会顺序',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'shanghuishunxu',
		'sortnum' => '9',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'int',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_njzcw.shanghuishunxu',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'sortsorder' => '1',
		'sortstype' => 'asc',
	),
);

?>