<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'isexport' => '1',
		'status' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'1' => array(
		'name' => 'car_id',
		'showname' => '车辆名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'car_id',
		'sortnum' => '2',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.oil_id',
		'table' => 'mis_system_car',
		'field' => 'oilID',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '40',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_car',
				),
			),
		),
	),
	'12' => array(
		'name' => 'carno',
		'showname' => '车牌号码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'carno',
		'sortnum' => '3',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.oil_id',
		'table' => 'mis_system_car',
		'field' => 'oilID',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '41',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#car_id#',
					'1' => 'id',
					'2' => 'carno',
					'3' => 'mis_system_car',
				),
			),
		),
	),
	'22' => array(
		'name' => 'oil_id',
		'showname' => '油卡号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'oil_id',
		'sortnum' => '4',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.oil_id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '21',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'oil_id',
					'3' => 'mis_car_card_bind',
				),
			),
		),
	),
	'2' => array(
		'name' => 'oil_number',
		'showname' => '加油量',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'oil_number',
		'sortnum' => '5',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.oil_number',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '44',
	),
	'23' => array(
		'name' => 'price',
		'showname' => '单价',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'price',
		'sortnum' => '6',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.price',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '45',
	),
	'3' => array(
		'name' => 'amount',
		'showname' => '金额',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'amount',
		'sortnum' => '7',
		'issearch' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.amount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '46',
	),
	'24' => array(
		'name' => 'oil_balance',
		'showname' => '油卡余额',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'oil_balance',
		'sortnum' => '8',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.oil_balance',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '47',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
	'4' => array(
		'name' => 'address',
		'showname' => '地点',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'address',
		'sortnum' => '9',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.address',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '48',
	),
	'5' => array(
		'name' => 'pay_type',
		'showname' => '付款类型',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pay_type',
		'sortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '油卡,现金,其他',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '0',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.pay_type',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '5',
	),
	'6' => array(
		'name' => 'persion',
		'showname' => '加油人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'persion',
		'sortnum' => '11',
		'issearch' => '0',
		'isexport' => '0',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.persion',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
	),
	'10' => array(
		'name' => 'invoice_number',
		'showname' => '发票号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'invoice_number',
		'sortnum' => '12',
		'issearch' => '0',
		'isexport' => '0',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.invoice_number',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '10',
	),
	'16' => array(
		'name' => 'month_oil_l',
		'showname' => '月加油量L',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'month_oil_l',
		'sortnum' => '13',
		'issearch' => '0',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.month_oil_l',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '15',
	),
	'17' => array(
		'name' => 'month_oil_money',
		'showname' => '月加油金额',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'month_oil_money',
		'sortnum' => '14',
		'issearch' => '0',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.month_oil_money',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '16',
	),
	'15' => array(
		'name' => 'last_oil_number',
		'showname' => '油卡余额',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'last_oil_number',
		'sortnum' => '15',
		'issearch' => '0',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.last_oil_number',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '17',
	),
	'19' => array(
		'name' => 'save_price',
		'showname' => '优惠价',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'save_price',
		'sortnum' => '16',
		'issearch' => '0',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.save_price',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '18',
	),
	'25' => array(
		'name' => 'integral',
		'showname' => '积分',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'integral',
		'sortnum' => '18',
		'issearch' => '0',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.integral',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '24',
	),
	'8' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '19',
		'issearch' => '0',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '25',
	),
	'14' => array(
		'name' => 'useNameID',
		'showname' => '负责人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'useNameID',
		'sortnum' => '21',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#oil_id#',
					'1' => 'oilID',
					'2' => 'useNameID',
					'3' => 'mis_system_car',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'searchField' => 'mis_car_add_oil_info.oil_id',
		'table' => 'mis_hr_personnel_person_info,mis_system_car',
		'field' => 'id,oilID',
		'conditions' => '',
		'type' => 'db|name,useNameID',
		'isallsearch' => '0',
		'searchsortnum' => '49',
	),
	'11' => array(
		'name' => 'departmentID',
		'showname' => '所属部门',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'departmentID',
		'sortnum' => '22',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#oil_id#',
					'1' => 'oilID',
					'2' => 'departmentID',
					'3' => 'mis_system_car',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'searchField' => 'mis_car_add_oil_info.oil_id',
		'table' => 'mis_system_department,mis_system_car',
		'field' => 'id,oilID',
		'conditions' => '',
		'type' => 'db|name,departmentID',
		'isallsearch' => '0',
		'searchsortnum' => '50',
	),
	'7' => array(
		'name' => 'add_time',
		'showname' => '时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'add_time',
		'sortnum' => '24',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.add_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '52',
	),
	'26' => array(
		'name' => 'business_type',
		'showname' => '业务类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'business_type',
		'sortnum' => '25',
		'issearch' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '0:圈存,1:加油,2:异地圈存',
				),
			),
		),
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.business_type',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|business_type',
		'isallsearch' => '0',
		'searchsortnum' => '42',
	),
	'20' => array(
		'name' => 'oil_type',
		'showname' => '类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'oil_type',
		'sortnum' => '26',
		'issearch' => '1',
		'isexport' => '1',
		'status' => '1',
		'searchField' => 'mis_car_add_oil_info.oil_type',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '43',
	),
	'46' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '47',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
);

?>