<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-系统视图list.inc 配置文件)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2016-03-03 14:00:31
 * @version V1.0
*/
return array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '5',
		'searchField' => 'tree_department.id',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
	'parentid' => array(
		'name' => 'parentid',
		'showname' => '父类id',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'parentid',
		'sortnum' => '5',
		'searchField' => 'tree_department.parentid',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'helpvalue' => '',
	),
	'name' => array(
		'name' => 'name',
		'showname' => '部门名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '5',
		'searchField' => 'tree_department.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'helpvalue' => '',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '部门编码',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '5',
		'searchField' => 'tree_department.orderno',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'helpvalue' => '',
	),
	'yongyouorderno' => array(
		'name' => 'yongyouorderno',
		'showname' => '部门用友编码',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yongyouorderno',
		'sortnum' => '5',
		'searchField' => 'tree_department.yongyouorderno',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'helpvalue' => '',
	),
	'quyu' => array(
		'name' => 'quyu',
		'showname' => '区域',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'quyu',
		'sortnum' => '5',
		'searchField' => 'tree_department.quyu',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'helpvalue' => '',
	),
	'cmpname' => array(
		'name' => 'cmpname',
		'showname' => '公司名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'cmpname',
		'sortnum' => '5',
		'searchField' => 'tree_department.cmpname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'helpvalue' => '',
	),
	'cmpid' => array(
		'name' => 'cmpid',
		'showname' => '公司ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'cmpid',
		'sortnum' => '5',
		'searchField' => 'tree_department.cmpid',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'helpvalue' => '',
	),
);
?>